### ISSUE TITLE
Display "Message History"

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#104]
### Goal

Indicate that a message has "a history" (i.e. delivery and processing time and timing data, past failures, retries etc.) and allow users to view the history of the message.

### Visualization

1. Add a "History" menu option to the context menu
   * Note: this can be instead or in addition to the exception data displayed in the context menu (it is displayed in the context menu when the status of the message is files or succeeded - after a successful retry)
* The History data display includes the following:
   1. Current status (Successfull / Failed / Repeated Failure / Retry Requested) 
   * Time sent (timestamp)
   * Delivery duration (timespan)
   * Processing started (timestamp)
   * Processing ended (timestamp)
   * Processing duration (timespan)
   * Number of 1st and 2nd Level Retries (integer; these are automated and configurable retries, as opposed to manual retries)
   * Exception details
      * type
      * message
      * stacktrace
      * Failed in Queue
      * Time of failure (timestamp)
      * Number of failures (integer)
      * Resolved at (timestamp; null if status is still failed / repeated failure)
   * Manual Retry History
      * Number of Manual Retries
      * For each manual retry request:
         * Action (RetryIssued / ErrorResolved)
         * Retry Timestamp

**Comment by johnsimons** [comment]
@dannycohen is this still something we should be doing ?
Have u had many requests for such a feature ?

**Comment by dannycohen** [comment]
@johnsimons - Not many requests. That's why we never proceeded much with this.
Close it and we'll re-open in Requirements if asked for.
