### ISSUE TITLE
Nodes in the message flow view not linked if OriginatingEndpoint and ProcessingEndpoint do not match

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#1196]
Nodes in the message flow view not linked if OriginatingEndpoint and ProcessingEndpoint do not match

- Resolved by https://github.com/Particular/ServiceInsight/pull/1171

**Comment by soujay** [comment]
This bug has been addressed in the [PR](https://github.com/Particular/ServiceInsight/pull/1171). Closing this bug
