### ISSUE TITLE
Endpoint Explorer vertical scroll does not work

### ISSUE THREAD

**Issue by JarredOddes** [Particular/ServiceInsight#1233]
### Symptoms
The endpoint explorer vertical scroll bar is greyed out and does not allow any scrolling.
I have attached and example image below.
![image](https://user-images.githubusercontent.com/46739159/178931829-e5c90751-13f1-47e8-9db1-3f4b3d93ce1e.png)

### Who's affected
Users of version 2.10

### Root cause
The root cause was the disabling of the virtualization feature in the Treeview control. This was done to fix this other bug: 
- https://github.com/Particular/ServiceInsight/issues/1212

**Comment by HEskandari** [comment]
This looks like an issue with the built-in WPF treeview control when run in Virtualization=Disabled mode. We had to disable the virtualization due to another issue we had in the last release.

**Comment by HEskandari** [comment]
<img width="401" alt="Screen Shot 2022-07-15 at 12 15 29 pm" src="https://user-images.githubusercontent.com/132117/179134427-fc824179-6de5-4732-a364-fcbd58a72003.png">

Reproduced and confirmed, the issue is with the TreeView behaving this way when disabling virtualization.

**Comment by mick-anderson24** [comment]
Any updates on the progress of getting this issue/bug resolved?

**Comment by soujay** [comment]
This bug has been addressed in the [PR](https://github.com/Particular/ServiceInsight/pull/1293). Closing this bug
