### ISSUE TITLE
Endpoint Explorer Scrolling doesn't work

### ISSUE THREAD

**Issue by mick-anderson24** [Particular/ServiceInsight#1254]
It doesn't appear that you can scroll through all the endpoints within the endpoint explorer if there are a ton of endpoints making it really hard to view messages from that queue.  There is no scrollbar and if you use the keyboard you can navigate down the list either

![image](https://user-images.githubusercontent.com/26772661/188963653-769bec98-750f-4ebe-afaa-1b1ff6218d33.png)

**Comment by timbussmann** [comment]
@mick-anderson24 have you been able to resolve the issue already or did you close the issue for another reason?

**Comment by mick-anderson24** [comment]
@timbussmann I noticed this issue was already raised by another person:  #1233

**Comment by timbussmann** [comment]
got it 👍

**Comment by HEskandari** [comment]
@mick-anderson24 We have fixed the issue in the [2.12.0 release](https://github.com/Particular/ServiceInsight/releases/tag/2.12.0).
