### ISSUE TITLE
Grouping Endpoints by Application in Endpoints List

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#150]
1. In SI, in the Endpoints list, the endpoints are displayed as-is, without any grouping.
* This may lead to a long list of endpoints, especially if the developer is developing / monitoring multiple applications (see below)
* We can group the endpoints by Application name (assuming the user follows the format of ```{AppName}.{EndpointName}```) 
   * we'll need to add "expand all" / "collapse all" buttons for ease of use.
* My guess is that **the value of this feature is**:
   * **Negligible** for single application developer, 
   * **Significant** for champs, consultants, partners, turn-key-solution developers, and of course - for us.

Thoughts ?

![image](https://f.cloud.github.com/assets/3889023/1731107/811b1f84-62fa-11e3-977a-dd71682a36ac.png)

//CC @udidahan, @andreasohlund, @HEskandari, @sergioc, @joaquinjares

**Comment by johnsimons** [comment]
@dannycohen is this one still something we want to do?
Has there been any requests for it ?

**Comment by dannycohen** [comment]
@johnsimons - There were complaints about large numbers of endpoints cluttering the endpoint list view (not recently, though). I'd say close it for now, and re-open if we receive more customer feedback for it.
