### ISSUE TITLE
Question: functionality of Property "Refresh"

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#179]
See image below:

![image](https://f.cloud.github.com/assets/3889023/1762221/97de81fc-66ec-11e3-9fd7-f36826a6dba2.png)

What does the "Refresh" option do ? what is its functionality ? 
(i.e. in what scenario does the property need to be refreshed ?)

**Comment by johnsimons** [comment]
This has been done, the only menu displayed is Copy
