### ISSUE TITLE
Design for Options Dialog

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#208]
See https://github.com/Particular/ServiceInsight/issues/207#issuecomment-31932816

Lets see if we can improve on this. 

// CC @HEskandari, @joaquinjares

**Comment by johnsimons** [comment]
The options window looks like this now:
![image](https://cloud.githubusercontent.com/assets/122651/7628317/341fbb46-fa65-11e4-8d1c-beb499d290ab.png)

IMO it looks fine, @dannycohen can we live with it ?

**Comment by dannycohen** [comment]
@sergioc - what do you think ?

**Comment by sergioc** [comment]
Could improve:

- AutoRefresh timer > indicate time units
- Recent SC entries > needs a better experience
- icons
- possibly layout

@dannycohen what else did you have in mind when you initially opened the issue, besides https://github.com/Particular/ServiceInsight/issues/207#issuecomment-31932816 ? 

Is that option really needed? Or could we simply remember the last state used in the flow diagram?

**Comment by johnsimons** [comment]
> Or could we simply remember the last state used in the flow diagram?

@sergioc that is how it works today

**Comment by sergioc** [comment]
@dannycohen is the current behavior acceptable for you?

**Comment by dannycohen** [comment]
@sergioc - 

>> is the current behavior acceptable for you?

If you are referring to "remember the last state used in the flow diagram" - then yes, definitely, IMO.

Otherwise I agree with your statement in https://github.com/Particular/ServiceInsight/issues/208#issuecomment-102029578 (aside from layout which is good enough IMO). 
Can you provide some design guidelines ?

**Comment by mauroservienti** [comment]
Reviewing this with @HEskandari we believe that this can be closed and if needed dedicated issues should be raised for each improvement we want to make.
