### ISSUE TITLE
Use SC connection status icons in Endpoint Explorer

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#213]
In order to determine if a given SC instance is connected, use status icons instead of always the same SC icon.

http://glui.me/?i=ax55h99ybzges26/2014-01-12_at_13.03.png/

**Comment by johnsimons** [comment]
@sergioc @dannycohen are you happy to close this one as it is not possible to do ?

**Comment by sergioc** [comment]
OK
