### ISSUE TITLE
Re-Design: Endpoint display in Message Flow

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#223]
##### Topic Definition
1. Current design of Endpoint in Message Flow does not represent the system behavior in a visually-correct manner 
   - (Note there are no bugs per-se, just place for improved visualization)
2. Failed Message Representation:
   1. There are three possible cases for message failing (by order of presumed most common to least common)
      1. Endpoint availability / stability issues 
      2. Endpoint badly configured
      3. Message badly formatted, fails deserialization
   2. Currently, when a message fails processing it is always marked as a "message failed", implicitly indicating that the message is badly formatted, while in many (most?) cases it may be an issue with the endpoints being unavailable / mis-configured.
3. Endpoint representation missing
   1. The current message flow, as its name indicates, is focused on representing the messages
   2. However, it will be beneficial to be able to represent the endpoints in a more significant way, both in order to provide the visualization for the "Failed Message" discussed above, and in order to allows us to display detailed endpoint data (which is extremely relevant to its sent / processed messages)
#### Question Definition

How an we provide a better design for endpoints in Message Flow ?

![image](https://f.cloud.github.com/assets/3889023/2004020/7d38fc7e-8690-11e3-8735-7b7a2aa4dc37.png)

// CC @udidahan , @HEskandari , @joaquinjares , @andreasohlund

**Comment by johnsimons** [comment]
@sergioc @dannycohen,
 
I may be wrong here but it seems this is complete, here is what the diagram looks like today:
![image](https://cloud.githubusercontent.com/assets/122651/7741937/8b47cc46-ffca-11e4-8edb-8ac62648fb9d.png)

Is there anything else or can we close this one ?

**Comment by sergioc** [comment]
@johnsimons going back to read the issue description, this is not complete.

- endpoints have even less prominence than original design (e.g. missing icons)

> However, it will be beneficial to be able to represent the endpoints in a more significant way, both in order to provide the visualization for the "Failed Message" discussed above, and in order to allows us to display detailed endpoint data (which is extremely relevant to its sent / processed messages)

- This needs discussion

- not marking endpoints as origin of error when applicable (only message itself is marked with red color)

@dannycohen want to open a new requirement for this?

**Comment by johnsimons** [comment]
Ok @sergioc, so what design should we be following including the design to display errors?

**Comment by sergioc** [comment]
@johnsimons this is my recommendation:

**With endpoint names visibility toggled ON:**

![screenshot 2014-02-13 20 19 47](https://f.cloud.github.com/assets/493451/2163786/f7b01ed6-94e3-11e3-9ab7-b2445861c4ae.png)


*********************


**With endpoint names visibility toggled OFF (only reveal problematic endpoint):**

![screenshot 2014-02-19 20 11 42](https://f.cloud.github.com/assets/493451/2210489/be13bb46-9999-11e3-9eba-069c714f2391.png)

**Comment by sergioc** [comment]
Recommendations already applied, closing.
