### ISSUE TITLE
Visualization of a message starting multiple Sagas in the Flow Diagram

### ISSUE THREAD

**Issue by joj** [Particular/ServiceInsight#230]
In the `Message Flow` diagram when the message starts more than one saga, the message node should correctly visualize all the Sagas. 

For example, the message starting two sagas should look like this:

![Screen Shot 2019-05-29 at 12 58 27 pm](https://user-images.githubusercontent.com/132117/58619542-70fb3880-8308-11e9-9b33-9b5ef00d0e0f.png)

**Comment by johnsimons** [comment]
@andreasohlund am I correct to say that for us to implement this in SI the core would have to change to collect the multiple sagaids and hence this is not supported ?

**Comment by andreasohlund** [comment]
Pretty sure we can handle this in the saga audit plugin?

That said we only support 1 instance per saga type so the screenshot in the description is not correct

**Comment by johnsimons** [comment]
@andreasohlund 

> Pretty sure we can handle this in the saga audit plugin?

Yes we could do that, but currently the message flow diagram has no dependency of the plugin, so that would be a change



> That said we only support 1 instance per saga type so the screenshot in the description is not correct

Yes agree, but still highlights the issue

**Comment by andreasohlund** [comment]
Now I get it, you're talking about the SagaId, SagaType headers.

Setup a call when you're back fro YOW so we can hash it out. Think we need
to introduce a new header to fix this
