### ISSUE TITLE
Update Retry / Options icons to new design 

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#241]
1. Related to #219 
2. The following icons require updating to the new design:
   - Options menu item under View menu.
   - Retry message on the context menu for the failed messages.

@sergioc - can you assist ? 
#### Existing Options

![image](https://f.cloud.github.com/assets/3889023/2204229/805238b2-9937-11e3-96c6-8c80858a8f63.png)
#### Existing Retry

![image](https://f.cloud.github.com/assets/3889023/2204224/689e8144-9937-11e3-8bc8-9e97cbf62099.png)

The retry icon used in SP is similar to Refresh in SI (just points the other way... which is good, IMO)

![image](https://f.cloud.github.com/assets/3889023/2204245/cdd01708-9937-11e3-9046-37663a721d23.png)

**Comment by johnsimons** [comment]
@sergioc do you think we should reuse the SP retry icon in SI ?

**Comment by sergioc** [comment]
@johnsimons I think not, not enough distinction between that and refresh icons in SI. Let's use:

https://www.dropbox.com/s/ag1d4hcwg0huwjf/retryMsg.svg?dl=0

**Comment by johnsimons** [comment]
@sergioc it looks like the background color is set to white, should it be transparent ?

**Comment by johnsimons** [comment]
@sergioc can you also send me an icon for the options ?

**Comment by distantcam** [comment]
Discussed with @HEskandari and we're gonna close this. It's so out of date the icons don't look like that anymore.
