### ISSUE TITLE
ServiceInsight should be single instance

### ISSUE THREAD

**Issue by joj** [Particular/ServiceInsight#250]
If the system is already open, it shouldn't open again.

//cc @udidahan

**Comment by johnsimons** [comment]
@dannycohen SP also supports opening SI see https://github.com/Particular/ServicePulse/issues/62

I think is pretty weird if we do not reuse the existing opened instance of SI if one exists.
What should we do here ?

I'm :+1: to single instance

@Particular/engineers what do you think ?

**Comment by DavidBoike** [comment]
Multiple windows is always awful unless you opt in. My preference would be single instance with tabbed interface. Would also enable a right-click option for messages "Explore in new tab" or "Explore in new window"

**Comment by seanfarmar** [comment]
Pushed a PR
