### ISSUE TITLE
in quiet mode installer still shows webpage and progress dialog

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#283]
so this 

    Particular.ServiceInsight-1.0.0-Beta6.10.exe  /quiet  /L*V "msiexe.log"

still flashes up a progress dialog and then opens http://particular.net/ServiceInsight-1

**Comment by johnsimons** [comment]
@SimonCropp @gbiellem is this still true ? I assume not because PI works ?

**Comment by gbiellem** [comment]
@johnsimons  yep it's definitely been fixed
