### ISSUE TITLE
Switch To Message View link from Saga View is not prominent and is easy to miss.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#285]
Currently the `Switch to Message View` is displayed inside the saga view diagram as a link.
Its easy to miss. As the heading of the Saga grabs attention, it's easy to miss the link.
Either way the link is not part of the saga diagram.

![image](https://f.cloud.github.com/assets/854553/2495794/134dc582-b305-11e3-909c-563d39807cf3.png)

I suggest moving it to next to the toolbar, where we have a button to show / hide the saga message data. 

cc/ @dannycohen @udidahan thoughts??

**Comment by johnsimons** [comment]
@dannycohen @indualagarsamy 

There is actually no "Message View" !

If you click on that link, you navigate to the "Flow Diagram", should we update the link text ?
