### ISSUE TITLE
automate the generation of screen shots

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#286]
So this page has several screens shots of ServiceInsight http://docs.particular.net/Serviceinsight/getting-started-overview
It is possible to take screenshots of WPF elements http://stackoverflow.com/questions/7754704/how-can-i-create-thumbnail-from-wpf-window-and-convert-it-into-bytes-so-i-can

So the proposal is to stub the data and automate the creation of screenshots. This could be run as part of a TC build and whenever the screens are update they can be easily copied to the docs site.

**Comment by johnsimons** [comment]
@SimonCropp does this still make sense ?

**Comment by SimonCropp** [comment]
OK closing this 

Not there are several SI screen shots in docs.

http://docs.particular.net/serviceinsight/getting-started-overview
http://docs.particular.net/serviceinsight/application-invocation

So moving forward these will need to be update manually as SI evolves ie contrive the given scenario in ServiceControl for each image every time
