### ISSUE TITLE
Negative values in calculated Critical time and Delivery time

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#302]
Based on imsage included in user feedback in https://github.com/Particular/ServiceInsight/issues/301

See:

![image](https://cloud.githubusercontent.com/assets/3889023/2682274/8cf5b1aa-c198-11e3-9b58-2595d013d80a.png)

// CC @andreasohlund , @HEskandari , @joaquinjares , @indualagarsamy

**Comment by cjoergensen** [comment]
We are seeing the similar behavior:

![image](https://cloud.githubusercontent.com/assets/8087733/7454683/48cdda9c-f276-11e4-866a-f26bb55f7221.png)

**Comment by andreasohlund** [comment]
Can you take a look at the pure headers on the message? (sent time and
processed time should be there)

Could the clocks be off between the servers?

**Comment by cjoergensen** [comment]
Here are the headers:

NServiceBus.ProcessingEnded: 2015-05-04 12:08:47:777249 Z
NServiceBus.ProcessingStarted: 2015-05-04 12:08:47:777249 Z
NServiceBus.TimeSent: 2015-05-04 12:08:48:166676 Z

It could be that the clocks on the servers are a bit off. Is there a smart way to verify that?

**Comment by andreasohlund** [comment]
Looks like it since timesent is after the processing ended.

Regarding checking the diff I only found this:

http://serverfault.com/questions/239848/time-difference-between-two-machine-clocks

@gbiellem any ideas?

**Comment by cjoergensen** [comment]
I will talk with my ops guys and see if we can get this verified.

**Comment by cjoergensen** [comment]
@andreasohlund @gbiellem I talk to the server guys,  and they said that the server clocks could easily come out of sync by some milliseconds. So that sounds like a reasonable explanation.

**Comment by johnsimons** [comment]
This is actually a bug in NServiceBus core, see https://github.com/Particular/NServiceBus/issues/2731
