### ISSUE TITLE
Saga View displays Events as Command

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#305]
### Repro
1. Created simple solution with SM
2. Saga publishes an event "OrderPlaced" (see code and SM Canvas below)
3. Saga View displays the message as a Command (see image below): the icon used should be the one for events and not the one for messages.

#### Order Placed Event

![image](https://cloud.githubusercontent.com/assets/3889023/2814675/d67fd66c-cead-11e3-89f0-64e2b6744c53.png)

![image](https://cloud.githubusercontent.com/assets/3889023/2814678/e4e976f4-cead-11e3-9fcd-5e674f38d632.png)
#### Displayed as Command in Saga View

![image](https://cloud.githubusercontent.com/assets/3889023/2814667/c5e24c0e-cead-11e3-9df8-d2aac0bf77a1.png)
### Versions used
- SM: 2.0.2
- SI: 

![image](https://cloud.githubusercontent.com/assets/3889023/2814686/fd033950-cead-11e3-87d0-9fb0ef2e9fc3.png)

**Comment by johnsimons** [comment]
@dannycohen in a saga that send and publishes multiple messages from a single saga handler, how do you see this working ?

Here is an example, in the message flow this saga looks like:
![image](https://cloud.githubusercontent.com/assets/122651/7789979/05f7a9f8-02b8-11e5-946f-f7800524ce01.png)

But then in the saga diagram it looks like:
![image](https://cloud.githubusercontent.com/assets/122651/7789984/293735b4-02b8-11e5-8a5b-4212127c2fa7.png)

so as u can see all messages going out are stacked up, this includes events (I have pointed them out in the diagram) and commands, so what should the arrow be ?

**Comment by johnsimons** [comment]
@sergioc thoughts ?

**Comment by johnsimons** [comment]
the only thing that comes to mind is for us to group the messages per type and display them grouped?

**Comment by johnsimons** [comment]
Because you can also have multiple timeouts, see:
![image](https://cloud.githubusercontent.com/assets/122651/7790003/207bb9a8-02b9-11e5-9d0b-72737bb2a363.png)

**Comment by mauroservienti** [comment]
If outgoing messages are events they are tracked with the correct icon. Not sure in which version this was fixed.

![image](https://user-images.githubusercontent.com/1325611/101046461-59e27a00-3581-11eb-9faa-d80eb5faf0fa.png)
