### ISSUE TITLE
Display of very long conversations in SI

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#335]
Moved from https://github.com/Particular/ServiceControl/issues/335

@JeffreyAllenMiller asked:

> We are using Schedule.Every to poll a sub system every 15 seconds. This process appears to be sending a deferred SchedulesTask message to RavenDB, This is creating thousands of records in ServiceControl and they all seem to be related by the correlationId. My concerns is that we might select on of these records in ServiceInsight with the Flow Diagram selected and it will cause ServiceInsight to crash trying to render all of them. Not to mention it is terribly inefficient. Should we be concerned about this? I think I understand why the correlationId is the same, I am guessing because it is the schedule task and it show related messages in that context. But the negative, could be the Flow Diagram or am I being paranoid.

**Comment by sergioc** [comment]
Scheduled msgs are off by default, closing.
