### ISSUE TITLE
When trying to filter by a search string, the list shows all messages instead of just the search results

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#361]
**Steps to repro**
1. Make sure that the root node is selected.
2. Enter the search string. For example: `SELENE@Application26@2014-07-16T06:28:13`
3. However the grid shows all messages, instead of just the results:
See:
![image](https://cloud.githubusercontent.com/assets/854553/3595638/50c6e53a-0cb8-11e4-9d4d-417528337a90.png)

**Comment by johnsimons** [comment]
It looks like this now works:
![image](https://cloud.githubusercontent.com/assets/122651/7644948/95c11f08-faf0-11e4-835f-7d679397523d.png)

Tested with SI v1.2.8 and SC v1.5.2
