### ISSUE TITLE
Expired licence old location trumps newer licence in current location

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#362]
The first licence that SI finds is the one that's verified even if it's expired and there's a newer licence installed by SI.

SI installs into HKCU, which is the last place searched for a licence.

Instead SI should check the licence and if it's invalid, continue searching the registry.

**Comment by indualagarsamy** [comment]
hey @distantcam - is this still an issue??hey @distantcam - is this still an issue??

**Comment by johnsimons** [comment]
This is probably fixed as part of https://github.com/Particular/ServiceInsight/commit/16dcead4c86b7adef3377ce159a10a73e17b0fd2

If not reopen it
