### ISSUE TITLE
Add colored background area behind hovered message

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#367]
In addition to current hover behavior, use a colored background area behind a hovered message, in addition to turning blue connectors and processing handlers. 

The background area also serves as a hotspot the user can click to select a message without having to open the message menu.

Regular message:
![screenshot 2014-08-11 21 44 41](https://cloud.githubusercontent.com/assets/122651/7877385/1be3b00e-061e-11e5-8ca1-922b4c3b8ad0.png)

Message in saga:
![screenshot 2014-08-11 21 43 29](https://cloud.githubusercontent.com/assets/122651/7877392/49b40de4-061e-11e5-814c-12c323fa4b7d.png)

**Comment by johnsimons** [comment]
@sergioc @dannycohen I assume we are not going ahead with this colour palette based on comments in https://github.com/Particular/ServiceInsight/issues/394#issuecomment-58965146, is that correct ?

**Comment by sergioc** [comment]
@johnsimons this issue doesn't relate to color specifically, but I'll close it anyway since this feature/enhancement can also be made part of the concern raised in https://github.com/Particular/ServiceInsight/issues/394
