### ISSUE TITLE
"Jump to page" in message browsing

### ISSUE THREAD

**Issue by synhershko** [Particular/ServiceInsight#372]
At the moment, ServiceInsight, allows you to page the messages in this fashion:
![image](https://cloud.githubusercontent.com/assets/854553/4156813/a84573e4-3477-11e4-8c9c-3ec362b87e3f.png)

Have an option that will allow the user to jump directly to a specified page as opposed to clicking on next button many times.

**Comment by danielHalan** [comment]
+1 for this until Advance Search is implemented, as paging thru 100's of pages is quite a pain.

**Comment by danielHalan** [comment]
Any progress on this?

**Comment by johnsimons** [comment]
@danielHalan not yet

**Comment by mauroservienti** [comment]
Closed in favor of https://github.com/Particular/ServiceInsight/issues/958
