### ISSUE TITLE
Feature Request - Retry Batch Mode & Short Cut Key

### ISSUE THREAD

**Issue by Romiko** [Particular/ServiceInsight#382]
I would like to select multiple messages and retry them. 

I would also like a feature where I can press a shortcut key e.g. F8, that would retry the message and move to the next failed message.

**Comment by johnsimons** [comment]
@dannycohen this one is an old one, are we going to do it or not ?

**Comment by HEskandari** [comment]
ServiceInsight is not really a dev-ops tool, so you shouldn't be doing bulk operations in SI. We have added this feature to ServicePulse which _is_ a DevOps tool. Please use that instead.
