### ISSUE TITLE
Very large stack trace screws with header view scrolling

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#391]
very minor but.... note that the scroll bar height is inconsistent as you scroll

![halfwayscroll](https://cloud.githubusercontent.com/assets/122666/4487414/d4a3fa9e-49fa-11e4-8237-409ea82b9f44.png)

![scollalittlefurther](https://cloud.githubusercontent.com/assets/122666/4487415/d856e278-49fa-11e4-95af-bee0d0406a20.png)

**Comment by johnsimons** [comment]
Found the issue in devexpress - https://www.devexpress.com/Support/Center/Question/Details/Q434570

**Comment by johnsimons** [comment]
So i think the solution is to remove the devexpress grid and use the one out of the box :smile:

**Comment by johnsimons** [comment]
Fixed in #461
