### ISSUE TITLE
Window does not follow highlighted message when message selection changes 

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#393]
### Repro
1. Select a message in message window
2. Note the SeqDiag indicates highlights the selected message
3. Select another message that is not displayed on the currently visible section of the SeqDiag window
4. Note the SeqDiag windows is not updates, i.e. it does not scroll to follow the currently selected highlighted message

**Comment by distantcam** [comment]
This needs to be checked if it's still a problem, given we rewrote the code for selecting messages.

If it still exists then it's scheduled for 1.6

**Comment by distantcam** [comment]
This has since been fixed.

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers do we know in which version this was fixed?
