### ISSUE TITLE
Unified visual language / palette for selected message in Sequence Diagram and Message Flow & Saga View

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#394]
Selected Message Flow message should be highlighted using a similar palette and visual language as the Sequence Diagram selected message ( @Sergioc and @DannyCohen will provide a design)

![image](https://cloud.githubusercontent.com/assets/3889023/4522196/70f32768-4d24-11e4-811c-0cde1a5eaa45.png)
### Saga View

Same applies to Saga View, which should also highlight the selected message:

![image](https://cloud.githubusercontent.com/assets/3889023/4524419/313f2fa2-4d44-11e4-8182-38d2a4aa88c2.png)

**Comment by johnsimons** [comment]
@dannycohen @sergioc I've read this issue description and there seems no conclusion to it.

So are we going forward with this or should we close it ?

Has there been any requests for this feature ?

**Comment by sergioc** [comment]
@johnsimons I'll get back to you soon on this.

**Comment by distantcam** [comment]
All the diagrams and looks have changed. This is no longer relevant. Closing.
