### ISSUE TITLE
Display connecting line on Timeout as thinner line 

### ISSUE THREAD

**Issue by dannycohen** [Particular/ServiceInsight#398]
Display connecting line on Timeout as same line as thinner line than other message types (command, event)

**Comment by johnsimons** [comment]
@dannycohen need your input regarding this issue, see https://github.com/Particular/ServiceInsight/pull/450#issuecomment-99643122

**Comment by dannycohen** [comment]
@johnsimons - As discussed:
We need to provide consistent visual language across all view (e.g. dotted line for Event, full line for Command, and (now) thin line for Timeout)

@sergioc - Can you chime in on design guidelines ?

**Comment by sergioc** [comment]
@dannycohen will discuss during sync with @johnsimons tomorrow
