### ISSUE TITLE
Ask user to opt in to sending silent error data

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#403]
There's a few places where SI fails silently (often around SC where SC does something unexpected) and there's no exception.

It would be useful if these were reported back to us. So, if we ask the user to report usage data back to us we can get this silent error data.

**Comment by johnsimons** [comment]
@distantcam isn't this one done ?

**Comment by johnsimons** [comment]
Done in https://github.com/Particular/ServiceInsight/commit/d4d67533b0e3b87feea4df9ca7ce8600d7e4fad1
