### ISSUE TITLE
When a saga message does not contain SagaHistory, Improve the status bar error message

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#413]
It is a valid scenario to have endpoints that contain saga information which does not load the SagaAudit plugin. When viewing these messages in ServiceInsight, the status bar reports an error.

--

![screen shot 2014-11-17 at 7 00 19 pm](https://cloud.githubusercontent.com/assets/854553/5081931/0b8e1d5e-6e8c-11e4-81da-6c9218a9c166.png)

**Comment by johnsimons** [comment]
We are now not showing that error in the status bar, instead we load the tab but just display:
![image](https://cloud.githubusercontent.com/assets/122651/7877358/97865bfe-061d-11e5-8788-3b8cd158eeba.png)
