### ISSUE TITLE
When message types are not present in the metadata from SC, then SI must display proper default values instead of blank

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#421]
For external integration scenarios when 3rd party systems are sending messages to NSB endpoints, they may not contain the `EnclosedMessageTypes` header.

When SC parses this information, the meta data for `MessageType` will be null. 
We need to set proper value such as `Not available - missing metadata EnclosedMessageTypes` or something of the sort.

Relates to https://github.com/Particular/ServiceControl/issues/429

**Comment by johnsimons** [comment]
Fixed in #484
