### ISSUE TITLE
Filter messages by severity

### ISSUE THREAD

**Issue by dnicholas2001** [Particular/ServiceInsight#425]
For example, when I click on an endpoint, I want to see only the errors.

**Comment by jdrat2000** [comment]
This came from a support case 8400

**Comment by dhreczany-gcmlp** [comment]
Any update? will it be implemented? Would you kindly please supply a link to support case 8400 for further notification purposes?

**Comment by johnsimons** [comment]
@sergioc thoughts about this request ?

So the idea is to have different view options

**Comment by sergioc** [comment]
This is already possible by sorting the message list by message status.
