### ISSUE TITLE
Message appears twice in message List and Flow diagram

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#427]
Hi 

We had some failed message, that went through after a retry, but now  they appear twice in the Message List and the Flow Diagram:

![image](https://cloud.githubusercontent.com/assets/8087733/5814326/89efcc08-a08a-11e4-809f-0d629259918f.png)

We are running ServiceInsight v. 1.2.4 and ServiceControl v. 1.4.3

Best regards
Christian

**Comment by distantcam** [comment]
That isn't exactly the same message, it's a new message with the same data, including the message id. That's why it's appearing twice.

**Comment by cjoergensen** [comment]
Hi @distantcam 

How can you tell that it is a different message?

Best regards
Christian

**Comment by distantcam** [comment]
Do you mean how do I know, or how is a user supposed to know it's a different message?

I know because there's been some bugs surrounding the idea of messages being unique, which is not true when you retry messages.

As for how best to show this difference to the user, that'll require more discussion. 

Thoughts? @sergioc @dannycohen

**Comment by dannycohen** [comment]
@cjoergensen - Would you say the image is a correct representation of what happened ? (i.e. the message was retried and processed twice by the same endpoint instance)

**Comment by cjoergensen** [comment]
@dannycohen Hmm... I am not really sure. There is only one message. That message failed and was retryed with succes. But in ServiceInsigt it looks like there is two different message (duplicates) where one has failed.

**Comment by dannycohen** [comment]
@cjoergensen - Can you check if the Message ID's are the same ?

**Comment by cjoergensen** [comment]
Hi @dannycohen, sorry for my late response.

In the Message list (see screenshot) they appear to have the same id. Unfortunately the messages are no longer available to me, because they have fallen to the 'ServiceControl/HoursToKeepMessagesBeforeExpiring' limit.

**Comment by cjoergensen** [comment]
@dannycohen

Hi again. The scenario just happend again. So I got fresh data now:

![image](https://cloud.githubusercontent.com/assets/8087733/6226585/f1570894-b696-11e4-94f6-68cdc0b65b05.png)

The message Id is the same. If I do a message search directly through the ServiceControl Rest ApI (api/messages/search/9380000b-de0c-4044-ae62-a442009abd6c/) i get two entries:

[{
	"id": "5c20bfb2-2b48-12ff-a727-d439a59bdcb3",
	"message_id": "9380000b-de0c-4044-ae62-a442009abd6c",
	"status": "failed",
	[Confidential Content]
	"message_intent": "publish",
	"body_url": "/messages/9380000b-de0c-4044-ae62-a442009abd6c/body",
	"body_size": 2024
},
{
	"id": "eae4a00f-4d86-426a-4225-974f73b947b4",
	"message_id": "9380000b-de0c-4044-ae62-a442009abd6c",
	[Confidential Content]
	"status": "resolvedSuccessfully",
	"message_intent": "publish",
	"body_url": "/messages/9380000b-de0c-4044-ae62-a442009abd6c/body",
	"body_size": 2024
}]

If you want the full content i can send this via e-mail.

Best regards,
Christian

**Comment by cjoergensen** [comment]
This looks very similiar to #419

**Comment by johnsimons** [comment]
@distantcam this should be fixed now ?
Except maybe the flow diagram still has a bug ?

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceInsight/commit/b60e9a205caec416c93fcb569219dd13b74b9092
