### ISSUE TITLE
Show inner exceptions in Exceptions view

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceInsight#430]
to discuss, @distantcam should I raise this as a requirement?
## 

related to: https://groups.google.com/forum/#!msg/particularsoftware/AA8nsiUREx4/z3Na-W0PriwJ

**Comment by distantcam** [comment]
@mauroservienti Yes please.

Although I suspect this is a ServiceControl issue and that ServiceInsight is just showing the data it's given. I'll look into it.

**Comment by mauroservienti** [comment]
done. Feel free to close this one

On Tue, Feb 17, 2015 at 3:08 AM, Cameron MacFarland <
notifications@github.com> wrote:

> @mauroservienti <https://github.com/mauroservienti> Yes please.
>
> Although I suspect this is a ServiceControl issue and that ServiceInsight
> is just showing the data it's given. I'll look into it.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceInsight/issues/430#issuecomment-74606702>
> .
>



-- 
Mauro Servienti | Solution Architect | Particular Software

**Comment by johnsimons** [comment]
@mauroservienti are you driving this one ? Can you provide a mockup of what u have in mind ?

**Comment by johnsimons** [comment]
This was done in v1.3.0, see https://github.com/Particular/ServiceInsight/releases/tag/1.3.0

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers I see no mention of this issue in the 1.3.0 release notes. Are we sure this was fixed in 1.3.0?

**Comment by adamralph** [comment]
Looking at the linked GG post, it seems like a better title for this feature would be something like "Show inner exceptions". Would the make sense? Is it indeed possible to see inner exceptions since 1.3.0?

/cc @mauroservienti @Particular/serviceinsight-maintainers

**Comment by adamralph** [comment]
Reopening, since we need to confirm whether this was indeed fixed in 1.3.0.

If not, we need to fix it. If it was, needs to be added to release notes for 1.3.0.

**Comment by HEskandari** [comment]
Checked this again. The exception and the inner exceptions information are all shown correctly in the stacktrace. We just need to include this in the release notes of 1.3.0.

**Comment by HEskandari** [comment]
Added the issue to the release notes.
