### ISSUE TITLE
Clear Audit Log

### ISSUE THREAD

**Issue by danielHalan** [Particular/ServiceInsight#431]
Possibility to Clear the Audit log.

**Comment by distantcam** [comment]
@danielHalan Can you be more specific? Do you want to clear the audit log entries from ServiceControl?

**Comment by HEskandari** [comment]
If by ''Audit" log you mean the log window in ServiceInsight, it can be cleared now. If you mean audit messages ingested in ServiceControl, there is a data retention policy that is exactly for that purpose.
