### ISSUE TITLE
Chocolatey package for 1.2.5 seems to be rejected

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#432]
Review Comments:

* Unfortunately this does not conform to our naming rules: https://github.com/chocolatey/choco/wiki/CreatePackages#naming-your-package. Remove “.install” from the package title.
* Add a more detailed package description.
* Keep in mind that *.install packages only make sense if there’s a portable version of the software too.
* Please don’t directly create/use a folder on the system root (c:\ChocolateyResourceCache).

Thanks

~ Tom

See : https://chocolatey.org/packages/ServiceInsight.install/1.2.5

**Comment by distantcam** [comment]
Fixed. Now to see if 1.2.6 passes review.
