### ISSUE TITLE
Retrying message retries it but still shows the message as failed

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceInsight#433]
Using SC 1.5.0 and Si 1.2.5

I'm preparing a talk with this sample here:

https://github.com/danielmarbach/nservicebus.introduction/tree/Reliability

When I change the `ComplainAboutProcessor` from 

````
 public class ComplainAboutProcessor : IHandleMessages<ComplainAbout>
    {
        public void Handle(ComplainAbout message)
        {
            Console.WriteLine("Received complain about {0} with reason {1}.", message.FacilityId, message.Reason);
        }
    }
````

to

````
 public class ComplainAboutProcessor : IHandleMessages<ComplainAbout>
    {
        public void Handle(ComplainAbout message)
        {
            throw new InvalidOperationException();
            Console.WriteLine("Received complain about {0} with reason {1}.", message.FacilityId, message.Reason);
        }
    }
````

The message is marked as failed ServiceInsight. When I fix the code and start the endpoint again and retry the message in SI the message is successfully processed by the endpoint as shown in the log:

> Press any key to shut down.
Received complain about dae3f902-a65c-4a9b-8060-62b9963db737 with reason d.

But the message remains failed on the UI even after several refresh attempts. See

![2015-02-26 09_40_16-serviceinsight for nservicebus](https://cloud.githubusercontent.com/assets/174258/6388558/7b50e122-bd9b-11e4-979d-5d0a1204bf49.png)

AuditConfig should point to the right audit queue. SC is running properly

**Comment by cjoergensen** [comment]
Could be related to #472 ?

**Comment by danielmarbach** [comment]
Here what SP shows

![2015-02-26 09_40_16-servicepulse for nservicebus](https://cloud.githubusercontent.com/assets/174258/6388670/cf7222c4-bd9c-11e4-9d0c-e4c3ada6b49a.png)

**Comment by danielmarbach** [comment]
@cjoergensen 472? Didn't find it

**Comment by cjoergensen** [comment]
@danielmarbach  oops #427

**Comment by danielmarbach** [comment]
and also #419

**Comment by cjoergensen** [comment]
Hi guys

Any updates on this issue?

**Comment by indualagarsamy** [comment]
@cjoergensen - we are currently investigating this issue. Stay tuned. We'll post updates as soon as we have them.

**Comment by johnsimons** [comment]
@distantcam this is now fixed right ?

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceInsight/commit/b60e9a205caec416c93fcb569219dd13b74b9092

**Comment by cjoergensen** [comment]
Issues seems to have reappeared in 1.2.10:

![image](https://cloud.githubusercontent.com/assets/8087733/8207279/9a952c3e-1500-11e5-90cd-35cd9806f8d2.png)

**Comment by johnsimons** [comment]
@cjoergensen yes it is a bug, unfortunately the bug is actually in ServiceControl, I'm chasing this one over there.

**Comment by cjoergensen** [comment]
@johnsimons what is the issue number in the ServiceControl project?

**Comment by johnsimons** [comment]
@cjoergensen it is related to https://github.com/Particular/ServiceControl/issues/472
