### ISSUE TITLE
Saga View Not Working

### ISSUE THREAD

**Issue by shawndewet** [Particular/ServiceInsight#434]
In my endpoint project I have referenced the ServiceControl SagaAudit plugin, such that when I deploy, the necessary dll is deployed as expected. You can see this in the left pane of the screenshot, which shows a view of the files in my deployed folder, from which the NServiceBus.host.exe is running processing messages successfully.

Yet the Saga view in ServiceInsight is complaining that I don't have the necessary ServiceControl plugin.

What am I missing?
![sagaview](https://cloud.githubusercontent.com/assets/1556343/6549321/d5f670f2-c619-11e4-981b-9321917308ee.png)

**Comment by distantcam** [comment]
There could be a number of issues here.

- Is ServiceControl running on the same machine as the endpoint?
- Is there anything in the logs?

cc @Particular/servicecontrol

**Comment by shawndewet** [comment]
Yup, ServiceControl is running on the same machine.  Which logs should I look at? ServiceControl's? ServiceInsight's?

**Comment by distantcam** [comment]
@shawndewet The endpoints log. :D

It should be in the directory, but I don't see it. Has logging been disabled for the endpoint?

http://docs.particular.net/nservicebus/logging-in-nservicebus

**Comment by shawndewet** [comment]
Oh yes, that is there...a separate \logs folder just off the top of the screen shot.  It is logging (with NLog) the activity of the endpoint as expected.  Both from NServiceBus and from my own code.  Should I be looking for something specific?

**Comment by distantcam** [comment]
Not that I know of. Magic words like "audit" or "error" I guess.

**Comment by shawndewet** [comment]
Nope, but a couple of messages of interest are ones that tell me that the SagaAudit part is being initialized.  Would it help if I attach a log file?  It's 52k with about 500 lines.

**Comment by distantcam** [comment]
Sure. Or you can send it to me at cameron.macfarland at particular.net

**Comment by distantcam** [comment]
@shawndewet Something else to try. When you select the message in ServiceInsight, go to the `Logs` tab at the bottom and you should see a url for the message. Go to that url in your browser and send me the results please.

**Comment by shawndewet** [comment]
Full response sent, but interestingly the log shows a NotFound error as well...see screen shot.
![si log url](https://cloud.githubusercontent.com/assets/1556343/6550190/a27c477c-c62a-11e4-9db3-c6f30bf43cfe.png)

**Comment by johnsimons** [comment]
Something looks off there, how come the id is a empty guid?

**Comment by shawndewet** [comment]
I did have a bug in my saga at one point that caused a message to go into an endless loop (After processing a message, my code sent a message of the SAME type, instead of the NEXT type in the business process).  That seems to be when these odd errors came into the log.  (Besides MSMS's purge, is there perhaps a way I can truncate all history in ServiceControl, get rid of all existing messages and start from scratch? (I'm still in staging and not yet in production)).  Perhaps the problem is just corrupt-data-related?

**Comment by distantcam** [comment]
The saga data id is null. Are you creating a unique saga id in your saga data?

http://docs.particular.net/nservicebus/sagas-in-nservicebus

Also, once you've fixed an error make sure to re-run the endpoint and generate new messages as the old messages won't be updated.

**Comment by shawndewet** [comment]
Sure, but is there a way to just trash all those old messages from the
database?

On Mon, Mar 9, 2015 at 7:41 AM, Cameron MacFarland <notifications@github.com
> wrote:

> The saga data id is null. Are you creating a unique saga id in your saga
> data?
>
> http://docs.particular.net/nservicebus/sagas-in-nservicebus
>
> Also, once you've fixed an error make sure to re-run the endpoint and
> generate new messages as the old messages won't be updated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceInsight/issues/434#issuecomment-77803066>
> .
>



-- 
Shawn de Wet
*Tel 083 378 4621*
[image: Inline image 1]
*Building software that makes your work easier!*
*www.codewell.co.za <http://www.codewell.co.za/>*

**Comment by johnsimons** [comment]
> Sure, but is there a way to just trash all those old messages from the database?

@shawndewet sorry for the delay, not easily, it is easier to drop the whole db, is this a development database ?

**Comment by shawndewet** [comment]
It is a development db.  I will drop and restart and see if that makes a difference.

**Comment by johnsimons** [comment]
Hi @shawndewet 

Is this still an issue with latest v1.2.9 ?

**Comment by johnsimons** [comment]
No response from user, so closing
