### ISSUE TITLE
Initiating a retry on the grid, retries the wrong message

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#437]
**Steps to reproduce:**
- Generate a few error messages so that there are at least a few error messages on SI
- Select the first message on the grid and initiate a retry
- Note that its retried the wrong message (see screenshot)
  While the first message was the one that was initiated with message id ending with: `c31ad5`, the one that SI indicates is being retried is one with message Id: `1001d`.
- Refresh on the top does nothing, does not refresh the grid.
- After clicking a different endpoint and back to the original endpoint, shows that it indeed retried the wrong message. 

![screen shot 2015-04-15 at 12 02 34 pm](https://cloud.githubusercontent.com/assets/854553/7167115/6592bfa8-e367-11e4-96ae-17b99de3f76c.png)

--

Related Desk Case: https://nservicebus.desk.com/agent/case/10257

**Comment by indualagarsamy** [comment]
@distantcam - can you please review the change? 

I think this is related to this commit -https://github.com/Particular/ServiceInsight/commit/30346a5600672b386ffa5a6cc3d67a5070a906a7

**Comment by indualagarsamy** [comment]
@distantcam @johnsimons - During the refresh operation, this returns false if essentially the message list hasn't changed. 
https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight.Desktop/MessageList/MessageListViewModel.cs#L251
So, the message icon will never be reset to either failed or repeated failed.

**Comment by indualagarsamy** [comment]
@johnsimons @distantcam - Any updates on this issue?

**Comment by indualagarsamy** [comment]
@distantcam - I believe we have a separate issue open for the retry issue. https://github.com/Particular/ServiceInsight/issues/433

**Comment by distantcam** [comment]
A deployment kerfuffle means this didn't make it to 1.2.6 and instead will be in 1.2.7
