### ISSUE TITLE
Endpoint explorer not in sync

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#440]
As you can see from the screenshot, the message endpoint is not in the explorer
![image](https://cloud.githubusercontent.com/assets/122651/7289226/51844e56-e9b0-11e4-90b4-74b595c0dced.png)

**Comment by distantcam** [comment]
Not sure about this one. I can't replicate it, and I suspect it might be a SC error anyway.

**Comment by johnsimons** [comment]
@distantcam ping me when u get online and I'll try to reproduce it for u

**Comment by johnsimons** [comment]
can't repro
