### ISSUE TITLE
Icon missing

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#441]
![image](https://cloud.githubusercontent.com/assets/122651/7289832/cbe3752a-e9b8-11e4-8884-ee9e3a9c900c.png)

**Comment by distantcam** [comment]
We currently don't have an icon for copy. cc @sergioc

**Comment by johnsimons** [comment]
@distantcam can't we re-using the exiting icon ?

**Comment by distantcam** [comment]
Yes, now that I know it's there.

**Comment by johnsimons** [comment]
@distantcam the current implementation is IMO a bit confusing, as u can see in the screen shot I have provided above, there is only a single row selected but when I click "Copy To Clipboard" all the headers are copied. I was expecting only the selected rows to be copied.

What do you think ?

**Comment by distantcam** [comment]
@johnsimons That's a different discussion that needs to involve more people. This issue is just about fixing the icon.
