### ISSUE TITLE
Copy to clipboard does not respect selection 

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#442]
![image](https://cloud.githubusercontent.com/assets/122651/7290619/8bf8eae6-e9c5-11e4-90bb-12788376ff14.png)

I was expecting to select whatever headers I'm interested in and then when I use the "Copy to clipboard", to only copy the highlighted headers

At the moment it copies all header regardless of the highlighted rows

**Comment by udidahan** [comment]
Should this have been cataloged as a bug? 

> Copy to clipboard does not respect selection

That text doesn't sound like an improvement to me.

**Comment by johnsimons** [comment]
Fixed @udidahan

**Comment by udidahan** [comment]
The reason I brought this up was in reading through the release notes, I didn't quite understand why it would be an improvement.
