### ISSUE TITLE
JSON Body view is slow and losses color formatting

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#446]
Hi

The JSON body is very slow when loading some messages (> 8 sec) and is unable to do color formatting on some attributes:

![image](https://cloud.githubusercontent.com/assets/8087733/7468000/58ffdd60-f303-11e4-8177-85475b36832c.png)

Could be related to #357 

I cannot post the full data of the message here, as it contains confidential data. But I can send it to you directly if needed.

Kind regards,
Christian

**Comment by johnsimons** [comment]
@cjoergensen 
Can you send it john.simons(at)particular.net

**Comment by cjoergensen** [comment]
@johnsimons it's should be in your inbox

**Comment by johnsimons** [comment]
Fixed as part of #449

**Comment by johnsimons** [comment]
@cjoergensen is this working now in v1.2.9 ?

**Comment by cjoergensen** [comment]
@johnsimons yes, it is much better.

**Comment by johnsimons** [comment]
nice to hear :smile:
