### ISSUE TITLE
Enabling large icons makes icons blurry

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#454]
![image](https://cloud.githubusercontent.com/assets/122651/7601656/d4f53c94-f95c-11e4-83fb-a2bbc02628f2.png)

**Comment by johnsimons** [comment]
@distantcam @dannycohen 

I think we should remove the "Customizations", this means the user would not be able to enable these settings, thoughts ?

**Comment by dannycohen** [comment]
@johnsimons - I see no significant value in the "large icons" feature. 
Its an accessibility feature that we do not (currently) support throughout our offerings, and can be provided by 3rd party software (like the accessibility tools provided by Windows, zoom-in/out in browsers etc.).

**Comment by distantcam** [comment]
This setting no longer exists, so closing this.
