### ISSUE TITLE
Smooth Scrolling in Saga View

### ISSUE THREAD

**Issue by fafachd** [Particular/ServiceInsight#464]
Smooth scrolling (rather than jumping to the next message) would make the saga view AWESOME.
 
Currently, scrolling feels very jumpy and it gets worse as the number of updated saga-data properties increases. When the number of updated saga-data properties gets sufficiently large, they start to drop out of view off the bottom of the screen and there is no way to see them, since scrolling with the slider jumps to the next message.

**Comment by johnsimons** [comment]
Hi @fafachd,

Yes this one is a very annoying bug, I have addresses this in #356 and will go out as part of v1.2.9

**Comment by johnsimons** [comment]
@fafachd is this now working ok for you ?
