### ISSUE TITLE
Unable to scroll horizontally in SequenceDiagram

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#470]
Unable to scroll horizontally in SequenceDiagram. Also, the sequence diagram view is initiated with a blank offset to the right, making it impossible to see the left-most endpoints:

![screenshot 2015-06-16 16 04 08](https://cloud.githubusercontent.com/assets/493451/8184934/8b3b195c-1441-11e5-9ab4-da4606a47714.png)

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceInsight/commit/474e0897a51473f8065756385db7b4d92f6f64da
