### ISSUE TITLE
Sequence Diagram mixed up

### ISSUE THREAD

**Issue by DocJames** [Particular/ServiceInsight#491]
Hi,

A message is delivered from 
Esb.Endpoints.AggregatedPowerReadingEventPublisher.1.0 -->
Esb.Publishers.AggregatedPowerReadingEventPublisher.1.0 -->
Esb.Subscribers.PandaCommunicator.Default.1.0

A lot of the Sequence Diagrams looks like this:

![croppercapture 23](https://cloud.githubusercontent.com/assets/8024718/9403173/ccf1bbea-47e4-11e5-9a0a-eb3625b4d0a7.png)

Somehow ServiceInsight is mixing the flow. 

The correct Sequence Diagram looks like this:

![croppercapture 24](https://cloud.githubusercontent.com/assets/8024718/9403221/561aaab2-47e5-11e5-9455-c04776ef4ba9.png)

Delivery time for the message is 0 ms. I think a fast delivery is causing the problem.

Thanks,
Jimmy

**Comment by johnsimons** [comment]
@DocJames what version of ServiceInsight are you on ?

**Comment by johnsimons** [comment]
@DocJames are those endpoints hosted in different servers ?

**Comment by DocJames** [comment]
@johnsimons I'm using ServiceInsight 1.3.1. The endpoints are on 3 different servers. There can be a slight time difference, which can cause the problem.

**Comment by weralabaj** [comment]
@DocJames Could you attach screen of FlowDiagram for this one? And list of messages for this conversation with TimeSent etc.?

**Comment by DocJames** [comment]
@weralabaj 

Here is the FlowDiagram:

![croppercapture 25](https://cloud.githubusercontent.com/assets/8024718/9463382/af8dc0a4-4b1c-11e5-83ef-1475459cebf8.png)

On publisher Esb.Endpoints.AggregatedPowerReadingEventPublisher.1.0

Headers:

NServiceBus.TimeSent: 2015-08-25 08:55:45:876694 Z
NServiceBus.OriginatingMachine: ESBENDPOINT-T1
NServiceBus.OriginatingEndpoint: Esb.Endpoints.AggregatedPowerReadingEventPublisher.1.0
NServiceBus.ReplyToAddress: Esb.Endpoints.AggregatedPowerReadingEventPublisher.1.0@ESBENDPOINT-T1
NServiceBus.ProcessingStarted: 2015-08-25 08:55:45:385266 Z
NServiceBus.ProcessingEnded: 2015-08-25 08:55:45:385266 Z
NServiceBus.ProcessingMachine: SERVICEBUS-T1
NServiceBus.ProcessingEndpoint: Esb.Publishers.AggregatedPowerReadingEventPublisher.1.0
NServiceBus.OriginatingAddress: Esb.Endpoints.AggregatedPowerReadingEventPublisher.1.0@ESBENDPOINT-T1

Performance:

TimeSent: 25-08-2015 10:55:45
ProcessingStarted: 25-08-2015 10:55:45
ProcessingEnded: 25-08-2015 10:55:45
ProcessingTime: 0 milliseconds


On subscriber Esb.Subscribers.PandaCommunicator.Default.1.0

Headers:

NServiceBus.TimeSent: 2015-08-25 08:55:45:385266 Z
NServiceBus.OriginatingMachine: SERVICEBUS-T1
NServiceBus.OriginatingEndpoint: Esb.Publishers.AggregatedPowerReadingEventPublisher.1.0
NServiceBus.ReplyToAddress: Esb.Publishers.AggregatedPowerReadingEventPublisher.1.0@SERVICEBUS-T1
NServiceBus.ProcessingStarted: 2015-08-25 08:55:45:258682 Z
NServiceBus.ProcessingEnded: 2015-08-25 08:55:45:305682 Z
NServiceBus.ProcessingMachine: MIRAM-D1
NServiceBus.ProcessingEndpoint: Esb.Subscribers.PandaCommunicator.Default.1.0
NServiceBus.OriginatingAddress: Esb.Publishers.AggregatedPowerReadingEventPublisher.1.0@SERVICEBUS-T1

Performance:

TimeSent: 25-08-2015 10:55:45
ProcessingStarted: 25-08-2015 10:55:45
ProcessingEnded: 25-08-2015 10:55:45
ProcessingTime: 47 millisekunder

**Comment by johnsimons** [comment]
@DocJames 
Looking at the `TimeSent`s for the 2 different messages it looks like `Esb.Publishers.AggregatedPowerReadingEventPublisher.1.0` is sent before `Esb.Endpoints.AggregatedPowerReadingEventPublisher.1.0`, this is probably happening because both `MIRAM-D1` and `SERVICEBUS-T1` server clocks are a bit out of sync.
To be honest it is pretty much impossible to have all server clocks in sync.

So it seems we may need to come up with another mechanism to figure out the order of messages and not rely on `TimeSent`.

**Comment by DocJames** [comment]
@johnsimons Yes, that is what I guessed was the problem. Can you use the message route to create the correct order? (the FlowDiagram is correct)

**Comment by johnsimons** [comment]
Sorry for the delay @DocJames.
Yes we are going to use the relatedTo header to correctly order endpoints.
We are currently working on a few improvements to this diagram and once
done we will release all these together.
On Wed, 26 Aug 2015 at 16:49 DocJames <notifications@github.com> wrote:

> @johnsimons <https://github.com/johnsimons> Yes, that is what I guessed
> was the problem. Can you use the message route to create the correct order?
> (the FlowDiagram is correct)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Particular/ServiceInsight/issues/491#issuecomment-134865320>
> .
>
-- 

*John Simons*
*Engineer, Particular Software*

Email*:*  john.simons@particular.net
Web:    www.particular.net

**Comment by HEskandari** [comment]
This is made obsolete by the rewrite of Sequence Diagram in #497 PR. We are using RelatedTo header to order endpoint and messages.
