### ISSUE TITLE
Wrong body is shown when having messages with same message ids

### ISSUE THREAD

**Issue by FabianTrottmann** [Particular/ServiceInsight#492]
When receiving several messages with the same message id, service insight displays the same body in all messages. No matter if messages are from the same type or not.
Although messages should have unique ids, displaying a completely wrong body corresponding to a message is confusing. The only way is to get the body directly from raven db.

**Comment by johnsimons** [comment]
Hi @FabianTrottmann 

How do I go about reproducing this issue, any help would be immensely appreciated ?

**Comment by FabianTrottmann** [comment]
Hi @johnsimons 
You can reproduce it by sending a message with a specific messageId and sending another message with the same messageId but with different payload. It doesn't matter if the messages are of the same or different types.
ServiceInsights displays the exactly same body on both messages (usually the body of the message which was sent first)

**Comment by andreasohlund** [comment]
@FabianTrottmann what's the use case for messages with the same ID? (we do handle messages with the same ID beeing processed by different endpoints)

The reason I ask is that if you are reusing message id things like Retries, Outbox etc will start missbehaving since they rely on unique message ids

**Comment by FabianTrottmann** [comment]
@andreasohlund different provider integrate with our endpoints and we are not in control whether the message Id is unique or not. We absolutely understand that message Ids should be unique, but in my opinion its still wrong to make users of ServiceInsight think that everything is fine and instead of showing an error just displaying the wrong body.

**Comment by johnsimons** [comment]
Hi @FabianTrottmann 
> different provider integrate with our endpoints and we are not in control whether the message Id is unique or not

I'm still unclear why the 3rd party integration needs the same message id for all messages ? As @andreasohlund points out, the `NServiceBus.MessageId` header is very critical for a successful execution of the NServiceBus core infrastructure, with that in mind, would it be possible for the 3rd party integration points to look at a different header that you would set and be in control of, instead of the  `NServiceBus.MessageId` header ?

> but in my opinion its still wrong to make users of ServiceInsight think that everything is fine and instead of showing an error just displaying the wrong body

You are right, unfortunately we have never consider this use case, hence the bug, I'll need to get back to you on how we going to address this issue.

**Comment by FabianTrottmann** [comment]
The 3rd parties don't use the same message id for all messages, but it recently happened in a case accidentally. We are aware that Message Ids are crucial and therefore we solve this problem organizationally to make sure, we do not get any duplicated ids anymore.
Thanks @andreasohlund @johnsimons for your help and quick feedback

**Comment by johnsimons** [comment]
> The 3rd parties don't use the same message id for all messages, but it recently happened in a case accidentally.

@FabianTrottmann so are you saying that this is an unusual scenario for you? I am asking because to be honest, we rely on distinct message ids heavily in ServiceInsight/ServiceControl and therefore I think is currently impossible to address this issue :disappointed:

**Comment by timbussmann** [comment]
@FabianTrottmann are the messages with the same id processed on the same endpoint?

**Comment by FabianTrottmann** [comment]
@johnsimons yes it is an unusual scenario and it really should not happen. @timbussmann In my case the messages are processed on the same endpoint. But I just tried to send messages with the same IDs processed on different endpoints and the same problem occurs.

When I query MessagesViewIndex on ravenDB with the messageId, I get multiple messages and the bodies displayed by ravenDB in the json docs are both correct. From where does ServiceInsight retrieve the message body?

**Comment by adamralph** [comment]
We are withdrawing this as unique message ID's are a fundamental assumption. @FabianTrottmann if you are still experiencing problems with this then please reach out to our [support channels](https://particular.net/support).
