### ISSUE TITLE
Messages list is not updated when choosing endpoint with 0 messages

### ISSUE THREAD

**Issue by DocJames** [Particular/ServiceInsight#498]
Hi,

If I look at an endpoint with messages, and choose an endpoint with 0 messages, the message list is not updated.

Looking at the top node:
![croppercapture 30](https://cloud.githubusercontent.com/assets/8024718/9733595/cb60b7b2-562c-11e5-94de-64ad5ea973da.png)

Looking at an endpoint with 0 messages:
![croppercapture 31](https://cloud.githubusercontent.com/assets/8024718/9733596/ce7e2790-562c-11e5-9ce4-9243daa5de88.png)

I'm using version 1.3.1 and ServiceControl version 1.6.1.

Thanks,
Jimmy

**Comment by johnsimons** [comment]
Thanks @DocJames, will look into it.

**Comment by johnsimons** [comment]
I can reproduce this, it seems that it gets out of sync randomly.
To reproduce we need to change endpoint quickly

**Comment by HEskandari** [comment]
@DocJames Apologies this has taken a while for us to get to. I have tested this and although I see a few issues with the way views are cleared (or not), the Messages List in particular is actually cleared as expected. 

Are you okay for me to reword the issue to reflect the state as of release 1.6.2?

**Comment by DocJames** [comment]
@HEskandari It's not a problem in release 1.6.2. Works fine now. Thanks.

**Comment by HEskandari** [comment]
@DocJames I'll close this issue then.

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers do we know in which version this was fixed (either deliberately or accidentally)?
