### ISSUE TITLE
ServiceInsight No License - Application Closes After Prompt

### ISSUE THREAD

**Issue by colin-higgins** [Particular/ServiceInsight#503]
A customer was using ServiceInsight and the trial period ended. He was unable to import a license through the UI. He was running the latest version (1.4).

 It seems as though the conditions were:
 - ServiceInsight was not picking up the license in HKLM
 - The customer deleted the trial license and trial date registry entries under HKCU
 - When starting ServiceInsight, an alert window popped up stating the license was not valid and there was no browse option to import a license and the application closed as soon as the alert window was dismissed, giving no opportunity to import a license

The work around was to manually add an entry "License" to HKCU with REG_SZ 

I think there are two problems here:
 - The edge case where no trial license or full license exists, the user has no ability to import
 - ServiceControl was not looking in HKLM for the full license.

Should we combine our license seeking logic into a single package shared between ServiceControl and NServiceBus? We could extend the NServiceBus license logic with visitor pattern (for the edge cases).

**Related Desk Cases**: 
- https://nservicebus.desk.com/agent/case/13838
- https://nservicebus.desk.com/agent/case/13733

**Related Issues**:
- Issue #502

**Comment by ramonsmits** [comment]
+1 I had another customer with the same issue. I just looked into the source code and SI only looks in HKCU.

Using default constructor: 

- https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/Framework/Licensing/AppLicenseManager.cs#L89

Using HKCU:

- https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/App_Packages/Particular.Licensing/RegistryLicenseStore.cs#L13

**Comment by ramonsmits** [comment]
Issue #502 is probably related as back then the customer tried multiple things and it eventually worked.

**Comment by colin-higgins** [comment]
@Particular/serviceinsight 
This has cropped up again. I had them manually override the trial entry in the registry but it comes back after restart.

**Comment by HEskandari** [comment]
Given ServiceInsight is a developer / debugging tools that run on the desktop, I think storing the license in HKCU does make sense. However, I think for reading the license, we should also check HKLM and copy the license to HKCU.

Thoughts?

**Comment by HEskandari** [comment]
@colin-higgins could you elaborate on when this happens? We store trial start date under HKCU\SOFTWARE\ParticularSoftware\ServiceInsight\TrialStart so removing that should reset the trial date. Could you point me to the desk issue, if there's any?

**Comment by johnsimons** [comment]
> I think for reading the license, we should also check HKLM and copy the license to HKCU.

@HEskandari pretty sure NServiceBus checks both, first CU and them LM

**Comment by HEskandari** [comment]
Verified. Licenses imported for NSB core gets stored in HKLM and we don't check that for SI purpose. I'll fix it so that SI checks both HKLM and HKCU when reading the license.

**Comment by mikeminutillo** [comment]
Another desk case https://nservicebus.desk.com/agent/case/15768
