### ISSUE TITLE
ServiceInsight looks blurry on higher DPI screens

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#504]
I just noticed this on my retina display. SI looks blurry compared to other elements on the screen.

https://msdn.microsoft.com/en-us/library/windows/desktop/ee308410(v=vs.85).aspx

SI should be updated to be per-monitor DPI aware. There might be other things impacted as we use bitmaps in places instead of scalable graphics.

**Comment by sergioc** [comment]
If you're able to list all currently used graphic resources, I can supply the corresponding SVG versions.

**Comment by sergioc** [comment]
@mikeminutillo can you reproduce this?

**Comment by mikeminutillo** [comment]
@sergioc yeah, some of the icons look blurry 
![image](https://user-images.githubusercontent.com/124014/91685493-139a0b00-eb8d-11ea-9a24-9891208c33a5.png)

So does the splash image

**Comment by mikeminutillo** [comment]
There's a collection of icons here https://github.com/Particular/ServiceInsight/tree/master/src/ServiceInsight/Images
Some of them may alreaady have been replaced. It's hard to tell

**Comment by mikeminutillo** [comment]
There's also this one https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/ServiceInsight-About.png

**Comment by sergioc** [comment]
This only affects icons. All icons will be converted to either a high-rez bitmap or vectors.

**Comment by sergioc** [comment]
All icons are available as SVGs here (and sub-folders): https://www.dropbox.com/sh/wv24lprn7vws4yr/AADME1J0nGlM43oGP0YmNLbCa?dl=0

Let me know if there's something missing.

**Comment by HEskandari** [comment]
Old vs New:

![image](https://user-images.githubusercontent.com/124014/91685493-139a0b00-eb8d-11ea-9a24-9891208c33a5.png)

![image](https://user-images.githubusercontent.com/132117/92198504-e8c6f400-eeb7-11ea-834d-d6f714d54fa8.png)

**Comment by sergioc** [comment]
From the screenshot, it seems the icons are still not updated for toolbars and (probably) everywhere outside the message list

**Comment by HEskandari** [comment]
@sergioc where should I get the icons for the rest of the application?

**Comment by sergioc** [comment]
>All icons are available as SVGs here (and sub-folders): https://www.dropbox.com/sh/wv24lprn7vws4yr/AADME1J0nGlM43oGP0YmNLbCa?dl=0
>
>Let me know if there's something missing.

**Comment by HEskandari** [comment]
Closed via #885.
