### ISSUE TITLE
Can't retry a failed message that was archived

### ISSUE THREAD

**Issue by Bishbulb** [Particular/ServiceInsight#506]
ServiceInsight version 1.4.0
ServiceControl version 1.7.1

Repro steps:
- Generate a failed message
- Open ServicePulse and archive the failed message
- Open ServiceInsight
- Find the archived message
- Right-click on the message and select "Retry Message"

Actual: The message is never retried (I verified this by enabling journaling on the MSMQ and never seeing any new messages get processed by the endpoint)
Expected: The message should have been retried.

The use-case here was that I accidentally archived a message that should have been retried, and I was trying to use ServiceInsight to correct the situation.

**Comment by johnsimons** [comment]
Actually the result is correct, once a message is archived it is not able to be retried.
And we do not have an un-archive at the moment.

It seems the problem is that SI is giving you the option to retry an archived message and that is a bug.

Now regarding your use case:
>  I accidentally archived a message that should have been retried

I need to discuss with others to see if we can support that scenario.
@mikeminutillo @petersgiles @gbiellem thoughts ?

**Comment by Bishbulb** [comment]
OK, thanks for the update regarding the expected behavior. I'm interested in knowing how I should be dealing with this type of issue in the future. I sometimes go to the error.log queue using Queue Explorer and drag-n-drop the archived message back into the source queue, but as you can imagine this solution is a bit dodgy for a production system.

**Comment by johnsimons** [comment]
@Bishbulb 

I was wondering, u said that "accidentally archived a message that should have been retried"
Is this because our archive and retry buttons are too close together ?
Or maybe because they do not have labels and easy to get them mixed up ?

**Comment by sergioc** [comment]
If the behavior is to be expected, we need to give a chance for the user to recover from an accidental error like this. Spacing the buttons apart might not be enough. The best is to delay the action by 3-5secs and show an undo link in the confirmation message. Once no longer possible to undo, hide the link.

**Comment by Bishbulb** [comment]
In my situation, we had a large number of messages hit the error queue due to an outage with one of our 3rd party integrations. For this particular 3rd party integration, we have built some UI into our application that shows the state (pending/success/failed) to the user, and we give the user a button to let them retry any transactions that may have failed. Our back-end processes are able to retry these failed transactions without caring that previous attempts may have resulted in messages hitting the NServiceBus error queue.

What happened here was that I archived all of the failed messages without realizing that a couple of them were **not** related to the 3rd party integration and thus should not have been archived. I then went into ServiceInsight, found the messages, and right-clicked to retry them. 

I recognize that this is a bit of an edge case, but I think it would be great to be able to recover from an accidental archive of a failed message, no matter what the reason. I kind of liked the idea of doing that from within ServiceInsight, as you have to be very explicit about which messages you are looking for & retrying.

**Comment by johnsimons** [comment]
@Bishbulb thanks for the extra details

**Comment by johnsimons** [comment]
@sergioc the "undo link in the confirmation message" is a good idea but it seems that would not work here because as @Bishbulb describes, all messages were archived in a single action and some of these should have not been.
Do the "undo link" would undo the archiving of all messages instead of speciifc ones.
I think the only was for us to support this scenario is to provide an unarchive option ?

**Comment by sergioc** [comment]
> but it seems that would not work here because as @Bishbulb describes, all messages were archived in a single action and some of these should have not been.

It would allow to recover from the mistake anyway, except archival of the other messages would also cancelled. That would already help, the only issue is that the user would have to find another way to only archive messages that were meant to be archived.

> What happened here was that I archived all of the failed messages without realizing that a couple of them were not related to the 3rd party integration and thus should not have been archived. 

@Bishbulb were the messages unrelated in the 3rd-party integration (i.e. those not meant to be archived) isolated in their own exception group?

**Comment by johnsimons** [comment]
@sergioc
I think the "Undo" toaster that gmail puts up when you send an email makes sense in their context however in this scenario we are not bound by a timeframe to cancel the action.
In essence we should be able to unarchive a message any time we want.

So yes we could have an "Undo" toaster like gmail does but that is just a temporal shortcut, we still need to provide the facility to unarchive a message at a later time.

Does this make sense ?

**Comment by sergioc** [comment]
OK

**Comment by HEskandari** [comment]
@sergioc What was the consensus here? Did we agree that it can be closed? Pinging @Particular/serviceinsight-maintainers

**Comment by sergioc** [comment]
Yep, this can be closed. ServicePulse now has the option to unarchive messages - more details: https://docs.particular.net/servicepulse/intro-archived-messages#unarchiving-failed-messages
