### ISSUE TITLE
Handler Label on the wrong side

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceInsight#512]
Is this a symptom of self-sends triggered by self-sends? In this case it was timeout triggered by timeout. 

<img width="337" alt="messagelabeloverhandlerlabel" src="https://cloud.githubusercontent.com/assets/124014/11329493/bb2ba6d6-91d7-11e5-80c1-a3c451f5b5f1.PNG">

**Comment by johnsimons** [comment]
I am actually wondering if we should top align the label.

![image](https://cloud.githubusercontent.com/assets/122651/11329652/bfeb15e0-91ea-11e5-90dc-c9c695a160d7.png)

@mikeminutillo @HEskandari @distantcam thougths ?

**Comment by HEskandari** [comment]
@johnsimons what is the problem of showing it on left/right (opposite the arrow) side?

**Comment by johnsimons** [comment]
> what is the problem of showing it on left/right (opposite the arrow) side?

Nothing wrong with that, was just trying to figure out if we could just have a set location, out of the way from everything else

**Comment by sergioc** [comment]
@johnsimons we should avoid covering lines and other visual objects with text, to keep the flows as uninterrupted as possible.
