### ISSUE TITLE
Message links don't open the correct sequence diagram

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceInsight#513]
Steps to reproduce:

1. Open ServiceInsight choose a Message that isn't in diagram of the first Endpoint
1. Copy the Message Url from the context menu in a sequence diagram e.g. si://localhost:33333/api?EndpointName=Store.Operations&Search=[Message Id Guid]
1. Close ServiceInsight
1. Paste the Url in a browser
1. Allows OS to open link in ServiceInsight

ServiceInsight opens on the Sequence Diagram but not on the diagram/conversation of the Message. Instead it displays the diagram of the first available Endpoint

**Comment by HEskandari** [comment]
@petersgiles could you elaborate on "message that isn't in diagram of the first Endpoint"? 

Is it a message that belongs to the second endpoint? or a message that's on the second page of data?

**Comment by petersgiles** [comment]
Any message that doesn't appear in the first diagram. The point is that the wrong diagram is being selected. The diagram that loads appears to be the first one in the list of endpoints. 

This is a tough one. I'm not sure there's any good way of deciding what diagram views to open and therefore whatever we do open is confusing. My initial reaction when opening in this way was, that wasn't the diagram I was looking at last time and what am I looking at now.

**Comment by johnsimons** [comment]
I have repro this but need some guidance

**Comment by petersgiles** [comment]
yes I'm not sure what the original experience was meant to be. Maybe @sergioc or @dannycohen can help.

**Comment by dannycohen** [comment]
@petersgiles - 

> what the original experience was meant to be

The original experience was meant to be thta you can open a Message URI and view the message and its context in SI. 

The primary usage for this was SP, but also many other tools.

This is a recurring feature in many tools, where you want to communicate a specific context that needs treatment. 

For example, a user scenario can be: "a DevOps person sees a problem in a message and wants the Dev to take a look at it".
* The DevOps can send the message Id (through copy Message Id to clipboard) 
* The DevOps can send a Message URI that will launch SI pre-filtered to show the specific message context. This option is a faster and more automate-able UX

Makes sense ?

**Comment by petersgiles** [comment]
@dannycohen ok, sounds legit.

So in our case where the devops sees a problem with a message, what screen should it open when the dev follows the link. ATM it looks like it will open the last view you had open.

**Comment by dannycohen** [comment]
@petersgiles -

> ATM it looks like it will open the last view you had open.

i.e. adhere to the viewing user's layout and preferences.

Makes sense to me. 

AFAIR - The option of specifying a specific view in the message URI was discussed but was never really a significant "sub-feature". Adding a "view" parameter to the mesages URI also makes for a more cumbersome URI (more options... more error prone etc. Lets keep it simple...)

**Comment by petersgiles** [comment]
closing - working as designed
