### ISSUE TITLE
Sequence Diagram - Leftmost labels get cut off

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceInsight#514]
When a label is added on the left hand side of the left most Endpoint, the text can disappear off the left hand side of the diagram. This can happen in two places when there is a long message type being sent back to the leftmost endpoint:

1. Where the incoming message is coming from another endpoint. The arrow will come in from the right hand side and the message type label will appear on the other side.
2. If the handler for that message is sending a message back out to the right then the label for the handler will also appear on the left hand side.

**Comment by distantcam** [comment]
I've fixed this for case 1.

For case 2 I don't know how to fix this. Any ideas @HEskandari @johnsimons ?

**Comment by HEskandari** [comment]
Do I read it wrong, or in both cases the arrow is coming Right to Left? if yes, what's the difference exactly? Since in RTL case handler label will appear on the Left hand side? @mikeminutillo @distantcam

**Comment by distantcam** [comment]
@HEskandari A loopback message on the first endpoint would be a left-to-right arrow.
