### ISSUE TITLE
Show empty state when no data is available for conversation

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceInsight#515]
When Service Control returns no data for a conversation, either because it's been deleted or because there is no Conversation ID (i.e. NSBv3), the new Sequence Diagram should show a "No Data" panel the same way that the other diagrams do. 

@sergioc will provide an image for this.

It may be helpful to include on this page some info about why there might not be any data (see the Body tab for an example). Alternatively we could link to a doco page about why there's no data.

**Comment by sergioc** [comment]
Mock-up:

![no conversation data](https://cloud.githubusercontent.com/assets/493451/11333302/064b1670-91cd-11e5-8df8-5f670fde94f1.png)

Icon: https://www.dropbox.com/s/yar31lrl21bdap8/no-conversation-data.svg?dl=0

**Comment by HEskandari** [comment]
This is ready, but I need the actual wording + link to the documentation page. It looks the documentation page is not created yet? @mikeminutillo

**Comment by mikeminutillo** [comment]
@HEskandari it's currently in a PR. I needed to update the image (and possibly the text) before we could release

**Comment by HEskandari** [comment]
Here's my screenshot...please advise on the wording. 
![image](https://cloud.githubusercontent.com/assets/132117/11417948/4ecfe2fa-946f-11e5-965c-a9c199643406.png)

**Comment by HEskandari** [comment]
oh, forgot...we need the image again as GeometryData format...could you provide that @sergioc ?

**Comment by sergioc** [comment]
Sure @HEskandari, but I think we'll need to discuss that first. I've sent you an invite.

**Comment by johnsimons** [comment]
This is done in https://github.com/Particular/ServiceInsight/commit/64007284fe9d53dcba9895d9660583fee590f408

**Comment by sergioc** [comment]
Minor adjustment in the text to shorten copy, better highlight call to action and make it easier to click.

Data could not be found. [Learn more about the possible reasons]().

**Comment by johnsimons** [comment]
Updated as part of https://github.com/Particular/ServiceInsight/commit/1d9ce938602739858e9da385832dc176c369641e
