### ISSUE TITLE
Messages overlaps on the flow diagram

### ISSUE THREAD

**Issue by andreasohlund** [Particular/ServiceInsight#516]
When multiple commands share the same conversation id.

![flow diagram bug](https://cloud.githubusercontent.com/assets/125028/11341770/3bc28f72-9204-11e5-97fb-3684aa45c765.PNG)

### Repro

Here's a video on how to repro - https://drive.google.com/a/nservicebus.com/file/d/0Bxjcg5ArjglPVjZFYWp3cklHSEU/view?usp=sharing

**Comment by HEskandari** [comment]
I could reproduce this when you switch back to the Message Flow tab, having a message/conversation selected other than the one previously displayed on Message Flow diagram. In this case the layout was not updated. The changes were made in commit 5de38b3e08a9e5ca7f111250dce4785e48771d85 to address this.

I could not reproduce this on the latest release on 1.5.6. Would you be able to have a look @andreasohlund or this is good enough to close it?

**Comment by andreasohlund** [comment]
Can't repro this any longer :+1:
