### ISSUE TITLE
Sequence diagram style and behavior adjustments

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#517]
After a review with @sergioc we came up with the following issues that needs to be fixed before the release:

- [x] Remove the message name underlining on mouse hover
- [x] Show the same tooltip from the handler when mouse hover the handler name
- [x] Making the spacing on the Left hand side label of the handler equal to the right hand side label
- [x] When a message is selected bring into view the message in the sequence diagram
- [x] Space between icon and message label as per design
- [x] Change the color for icon for the hover state of the message
- [x] Show context menu on right click, left aligned to the message
- [x] Use loopback icon for self-send messages
- [x] Change endpoint and the line color to #e6e6e6
- [x] Move the endpoint icon a couple of pixels to the left
- [x] Make sure the font size for the Endpoints at the top matches the message font size.

No going to do:
- [ ] Add max length to handler label and show ellipsis (...) in the middle, if possible: Added a white background to the label instead.

**Comment by johnsimons** [comment]
Regarding the " Add max length to handler label and show ellipsis (...) in the middle, if possible.", we have decided against ... as much as possible and in this scenario we don't need them.
All we need is to ensure the text is readable when overlaps a line, and that can be easily achieved by assigning a white background to the label.

**Comment by sergioc** [comment]
> we have decided against

@johnsimons I don't remember being part of the decision process... 

> All we need is to ensure the text is readable when overlaps a line, and that can be easily achieved by assigning a white background to the label.

... but let's see how that will look like.

**Comment by HEskandari** [comment]
@sergioc could you conver the loopback.svg to Geometry data? I can see that it has Polyline and Polygon inside, which makes it a bit different (and unusable in my case). e.g. this is for "Commands":
```
M 0,0 M 32,32 M 0,16 A 6,6 0 1 1 12,16 A 6,6 0 1 1 0,16   M 14,13 v6 h10 v2 L32,16 L24,11 v2 z
```

**Comment by johnsimons** [comment]
> I don't remember being part of the decision process

@sergioc yes that is right, the taskforce made that decision in the Aussie timezone.

**Comment by sergioc** [comment]
@HEskandari updated loopback* icons in same location, lemme know if you need further adjustments.

**Comment by sergioc** [comment]
@johnsimons can you add here a screenshot of a sequence diagram showing various handler labels overlapping endpoint spines to see the impact of the overlapping labels?

**Comment by johnsimons** [comment]
@sergioc here it is
![image](https://cloud.githubusercontent.com/assets/122651/11432813/2a47d554-9501-11e5-926b-fc7f95110510.png)

We need to add more padding but it should convey the message

**Comment by sergioc** [comment]
@johnsimons That does not give me an idea of what I asked for. I see only one handler in one tiny screenshot cropping. 

Can you please provide a screenshot showing a diagram with various handler labels overlapping endpoint spines to see the impact of the overlapping labels?

**Comment by johnsimons** [comment]
Sorry @sergioc not following, the screen shot shows an overlapping, wasn't that what you are after ?
Here is a zoomed view:
![image](https://cloud.githubusercontent.com/assets/122651/11488522/e07bc344-9812-11e5-9401-3e940a171c41.png)

**Comment by johnsimons** [comment]
All done
