### ISSUE TITLE
Blue arrow overlaps start box

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#518]
![image](https://cloud.githubusercontent.com/assets/122651/11357794/f7ef0060-92b6-11e5-998d-b0c7e8aabfe5.png)

**Comment by HEskandari** [comment]
Is this still an issue @johnsimons ? It looks like this so it is a bit more consistent with other handler 'boxes':

![image](https://cloud.githubusercontent.com/assets/132117/11460942/495d3fcc-974c-11e5-9cc6-cb5db004fdda.png)

**Comment by johnsimons** [comment]
I think we can live with it.
@petersgiles thoughts ?

**Comment by petersgiles** [comment]
I don't like it but if it is consistent across all arrows then I can live with it

**Comment by HEskandari** [comment]
the problem is that there's no elegant and easy way to make this an exception, consider other scenarios like this as well:

![image](https://cloud.githubusercontent.com/assets/132117/11461299/713c4710-9754-11e5-85af-07524260e4ef.png)

**Comment by petersgiles** [comment]
And this is why I wanted a handler-centric diagram. :(

The blue line only appears when you highlight a thing so its meaning isn't changed by this.

If you really want to highlight the start of the line put a small blue circle on the end of it...that's universally accepted as the start of something in UML

**Comment by johnsimons** [comment]
Not going to fix for now
