### ISSUE TITLE
Sequence Diagram - message context button pushed diagram a little left on hover

### ISSUE THREAD

**Issue by petersgiles** [Particular/ServiceInsight#519]
Hovering over the message box makes the context button appear and pushed the whole diagram a little to the left

![si_enfattening_a](https://cloud.githubusercontent.com/assets/1644481/11360044/46575e6e-92d5-11e5-8b5e-2ae93586c7b7.PNG)

In this picture notice that the timeline (spine) was originally under the '.' just after HashBus in the endpoint box. The picture showing the hover has the timeline a few pixels to the left under the 'us'. It makes the image jitter weirdly during the hover.

![si_enfattening_b](https://cloud.githubusercontent.com/assets/1644481/11360045/49071e4c-92d5-11e5-91b7-6b7e3d55b2a8.PNG)

We just need to provide a bit of extra room in the diagram for the rightmost message to expand into

**Comment by sergioc** [comment]
@petersgiles we're removing the context menu button and replacing it with a right-click context menu, so that will solve this for now. We'll bring the button back if there's proof this causes issues.

**Comment by HEskandari** [comment]
@petersgiles @sergioc The button is removed now as a part of fb06f94
