### ISSUE TITLE
Message Properties Dialog takes multiple clicks to update

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceInsight#520]
Symptoms

If you click a message on the Flow diagram, the Message Properties view clears but does not refill. If you click that same message on the Flow diagram, the Message Properties view fills in.

Here's why:
- User clicks the message on the Flow Diagram
- Flow diagram raises a SelectionMessageChanged event
- Message Properties dialog sees this and shows the message properties from the HeaderRaw property on the StoredMessage instance
- Sequence Diagram ALSO sees this and changes it's selected message
- This triggers the Sequence Diagram to raise it's own SelectionMessageChanged event
  - This event uses the StoredMessage that is stored against the Arrow on the Sequence Diagram.
  - That instance of StoredMessage does not have the HeaderRaw property filled in
  - The Message Properties Dialog sees this new StoredMessage and dutifully clears it's state. There is no new state to display

And then:
- User clicks the SAME message on the Flow Diagram
- Flow Diagram raises a SelectionMessageChanged event
- Message Properties dialog sees this and updates as per usual
- Sequence Diagram ALSO sees this
  - But the message is the already selected message so no SelectionMessageChanged event is raised

I don't know how to fix this. I can track back to why the Arrow StoredMessage doesn't have HeaderRaw and try to add it but that's only part of the problem. The Sequence Diagram shouldn't be re-raising an event as a part of responding to that event. Also, why does the StoredMessage get copied around. Ideally there would be one copy of the StoredMessage and some central repo / cache for things to go grab them from. That's a WAY bigger issue though :)

@HEskandari @distantcam @johnsimons thoughts?

**Comment by HEskandari** [comment]
+1 on not copying the StoredMessage. The event handling is more complicated than that. It boils down to the fact that same event is raised from different UI widgets, e.g. Messages grid raises a selection change event, as well as SD, and FD. Plus we need to keep the selection synchronized across the different views.

**Comment by johnsimons** [comment]
> It boils down to the fact that same event is raised from different UI widgets

@HEskandari that is exactly the problem, we need to only have a single owner per event, I will look at fixing this on Monday

**Comment by HEskandari** [comment]
@johnsimons did you work on this?

**Comment by HEskandari** [comment]
Fixed in 61e4d73.
