### ISSUE TITLE
Change program name from "ServiceInsight for NServiceBus" to "ServiceInsight"

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#521]
We don't refer to ServiceInsight as "ServiceInsight for NServiceBus" anywhere, so for the sake of consistency, need to rename the program name to "ServiceInsight".

**Comment by petersgiles** [comment]
@johnsimons & @sergioc are you playing tennis?

@sergioc I'm support the notion of a rename but, while consistency is a good thing, this needs to be done as part of a greater marketing strategy. 

There are several opinions within the company on naming things all with reasonable arguments behind them. @mauroservienti seems to be enthusiastic about this right now.

I think we should cool our heels on this one until we decide what we are doing with the platform unless we can find a greater imperative for doing it i.e. Marketing/Sales wants it now.

**Comment by mikeminutillo** [comment]
@pete I agree. This is a trivial change which will have a non-trivial amount of fallout. We should not try and complete it within the context of the Sequence Diagram.

**Comment by sergioc** [comment]
@pete @mikeminutillo fine, let's come back to this later.

**Comment by distantcam** [comment]
Doing this as part of a 1.6 release. The times we say "ServiceInsight for NServiceBus" are in the assembly info for the exe, and the 2 shortcuts the installer creates (one in start menu, one in desktop).
