### ISSUE TITLE
Message properties panel does not update if messages are selected via new sequence diagram

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#522]
Message properties panel does not update if messages are selected via new sequence diagram. If I select messages via the message list, then it properties panel updates according to selection.

![screencast](https://dl.dropboxusercontent.com/s/tl3pnf9v2cm4tfx/2015-11-26%20at%2018.14.gif)

**Comment by johnsimons** [comment]
Duplicate #520
