### ISSUE TITLE
Add legend to explain diagram elements

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#523]
Add tooltip to message arrow lines to allow user to understand what does the line type (solid or dashed) signifies.

Suggested text format: `MessageName command` and `MessageName event`

**Comment by johnsimons** [comment]
:-1: things like this are better comunicated via a symbols legend (we could expose a quick help popup), or just doco.
Something like when u press `?` in github.
![image](https://cloud.githubusercontent.com/assets/122651/11431797/1dbd25ac-94eb-11e5-9e62-fb8acfd32f9c.png)

So we can not just define lines but also, messages, handlers, handlers in error, start, ....

Maybe @petersgiles you would be able to help up here ?

**Comment by petersgiles** [comment]
@distantcam something like this would be good

![legend](https://cloud.githubusercontent.com/assets/1644481/11432968/b778de46-950b-11e5-8876-01c5b0de4bea.png)

**Comment by johnsimons** [comment]
That's exactly what I had in mind @petersgiles.
Ping me if u need help identifying all possible symbols

**Comment by petersgiles** [comment]
Yes we need a list and I think they should be in the legend at approximately half scale. 

Also simple one to two word names for each thing. We can do some fancy stuff by using tool tips or accordion s if we need a lot of text to describe what they are.

**Comment by johnsimons** [comment]
No worries @petersgiles, lets work on this on Monday

**Comment by HEskandari** [comment]
Even better, the help window in Slack looks almost the same, and hey, it is in WPF ;) Is this what we've settled on doing?

![image](https://cloud.githubusercontent.com/assets/132117/11460878/00063448-974a-11e5-96c8-6d3c91d8bcab.png)

**Comment by petersgiles** [comment]
@hadi yes I think this is the best way to go. It's good that you have a working example from an application we like using too. We might get into a little bit or argy-bargy over where it should pop up but you should go ahead and prototype it.

**Comment by HEskandari** [comment]
I've implemented this as much as we agreed and discussed with the TaskForce. This can be closed to my understanding.

![image](https://cloud.githubusercontent.com/assets/132117/11494115/63306458-9853-11e5-9a7c-796914b2d82a.png)

**Comment by johnsimons** [comment]
Awesome work @HEskandari

**Comment by petersgiles** [comment]
Things to review / do

- Title Bar "Diagram Legend" or just "Legend"
- Left justify Icons
- Wording (as per image above)
   - Start Conversation
   - Process Message
   - Process Message Failed
   - Publish Event
   - Send Message
   - Send Local Message
   - Request Timeout

**Comment by petersgiles** [comment]
Things to review / do

- Title Bar "Diagram Legend" or just "Legend"
- Left justify Icons
- Wording (as per image above)
   - Start Conversation
   - Process Message
   - Process Message Failed
   - Publish Event
   - Send Message
   - Send Local Message
   - Request Timeout

**Comment by petersgiles** [comment]
Your new legend

![legend](https://cloud.githubusercontent.com/assets/1644481/11518493/e762f8ca-98e5-11e5-8488-4cac746d9f01.png)

**Comment by johnsimons** [comment]
@distantcam can u look at this one too ?

**Comment by johnsimons** [comment]
There u go after a few adjustments
![image](https://cloud.githubusercontent.com/assets/122651/11523700/337fd690-9910-11e5-974a-59a8fcfb118e.png)

It was difficult to split the arrows from the symbols, so for now this is it.

**Comment by sergioc** [comment]
I think this should be removed from the sequence diagram or at least postponed to a future version. 

Here's why:

- first of all this is not the solution to the original issue, so I re-launched the original in a new issue (https://github.com/Particular/ServiceInsight/issues/528)
- There's no argumentation in https://github.com/Particular/ServiceInsight/issues/523#issuecomment-160006337, just @johnsimons opinion
- A clutter-free option, based on a long standing UI pattern (https://github.com/Particular/ServiceInsight/issues/528) has not been validated with user testing. E.g. the UI for a multi-line graph often gives tooltips to explain the line represents and it's natural to hover the lines if no legend is present. We also use tooltips elsewhere in this diagram to give more details about certain objects in the diagram.
- whatever UI we add to access this adds clutter, which we don't yet know whether it's necessary
- the implementation above is not optimal:
   - the panel disclosure UI cue is [barely noticeable and offers no clue about what it will do/show](https://dl.dropboxusercontent.com/s/nfewhlkn8to3bxb/2015-12-03%20at%2018.35.png)
   - the panel positioning is messy [showing as a sub-panel of a panel](https://dl.dropboxusercontent.com/s/4rykn4gsyixlpdq/2015-12-03%20at%2018.34.png)
   - A legend would be better placed in a Sequence Diagram doco, with additional details about the sequence diagram. 
   - If user testing indicates tooltips are not enough, the ideal design is a button in the tool bar with a help sign icon or that icon and a `Help` text label, which links to a proper Sequence Diagram doco in the browser.

Better not rush out this one.

**Comment by sergioc** [comment]
Another alternative to this legend is a modal view that shows when the user opens the Sequence Diagram tab for the first time.

The modal view could include:
- a short introduction text to the sequence diagram in SI and what is it supposed to show
- a link to a sequence diagram doco
- the legend
- an option to not show the modal again (though it can be re-accessed any time via the Help menu)

The advantages of this modal over the current implemetation are two:

1. the user can't miss it because it shows automatically
2. it won't take permanent room in the visible UI

Mock-up:

![screenshot 2015-12-04 16 30 49](https://cloud.githubusercontent.com/assets/493451/11593401/742c0c28-9aa4-11e5-8ad9-b30233bb2c83.png)

**Comment by petersgiles** [comment]
@sergioc this is very good and I think you've nailed the look and feel of what should be displayed to the user. I like the link to our documentation and the way that is done as part of the paragraph at the top. I still think the legend bits should print / export with the diagram when we provide those options. 

Also I still think it should be launched from a widget on the diagram. That way the noise is opt-in. Here's the Pete-flow (Pete is a subset of all developers and isn't necessarily indicative of the developer community as a whole).

I find 'tour of new features' popup dialogs annoying because I'm going to read the words 'getting started...' and then dismiss the dialog without reading the rest because it's not why I'm opening the tool this time. I'm going to do that for about 3 or 4 starts before I get agitated enough to give it my attention. I'm going tick that box and hope it works better than the Microsoft 'remember me' checkbox.

A small '?' widget in the top corner of the diagram to launch this would be within the context of the task I am trying to achieve and a natural way for me to adopt product knowledge at my own pace.

I think you are right about also navigating to this from the help menu but I'm not sure it will scale well if be have more than a dozen 'feature help boxes'. we may have to look at in app help search like OSX does when we hit a certain number of these,

**Comment by HEskandari** [comment]
@sergioc I see a few issues with this proposal...

- We don't have the infrastructure to show skinned dialogs, remember settings, etc.
- A modal dialog in this context wouldn't be possible. The "Tabs" are all activated when you open the shell so technically you don't know when "Sequence Diagram" tab is activated for the first time.
- How do they access the dialog when they have dismissed with "Don't show again"?
- As @petersgiles says, it wouldn't scale...what happens when we have four 'Getting started' dialogs?

**Comment by petersgiles** [comment]
@HEskandari but the content of the dialog is fine right? 

The problem is just the engineering around making a modal work in a predictable and useful way.

**Comment by HEskandari** [comment]
@petersgiles yes, no problem with the content. The issue was 'how' to show it and not 'what' :)

**Comment by distantcam** [comment]
![screenshot 2015-12-04 18 24 41](https://cloud.githubusercontent.com/assets/493451/11596262/52f23bd0-9ab4-11e5-90e9-647dfebfecdb.png)

For me, this is a failure. This says "We know this diagram is too complex for you to understand, so here's some help that you'll need to refer to more than once."

**Comment by mikeminutillo** [comment]
The use of the term "Command message" is potentially misleading. A message can be a Command, a Reply, or just a Message.

We're also missing a legend entry for the Endpoint.

**Comment by tmasternak** [comment]
Removing `Tag: Consider for Short Term Focus`. @HEskandari  Please add `Consider for Promotion` if it's still relevant.

**Comment by sergioc** [comment]
Agreed on including a link to [documentation](https://docs.particular.net/serviceinsight/sequence-diagram/) which already explain what lines and icons mean.

**Comment by HEskandari** [comment]
@sergioc can you create a mockup on 'how'? Where should the link go?

**Comment by sergioc** [comment]
It would be a button in a diagram toolbar:

<img width="769" alt="image" src="https://user-images.githubusercontent.com/493451/92098134-29037500-edd9-11ea-801f-b15baf5ef6e1.png">

Icon: https://www.dropbox.com/s/cuomm5yzdkhjmnh/help.svg?dl=0

**Comment by seanfarmar** [comment]
Pushed a PR
