### ISSUE TITLE
Context menu issues

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#524]
1. The message name shows up as part of the menu when clicking on an error message
![image](https://cloud.githubusercontent.com/assets/122651/11432679/2a7000b2-94ff-11e5-8b68-0f27e32b2858.png)

2. Retry button shows on non error messages

### Actions

- [x] Remove the context menu title
- [x] Remove / Hide retry message option when it's not an error message (or it is a failed message in a state where it would be inappropriate to Retry)

**Comment by petersgiles** [comment]
1. [ ] Change the context menu title to ????
2. [ ] Remove / Hide retry message option when it's not an error message (or it is a failed message in a state where it would be inappropriate to Retry)

We should split these into separate issues if we can only solve one of them

**Comment by mikeminutillo** [comment]
I'm not certain that having the message name in that context menu adds a lot of value. If you right-clicked on you were just reading it. If anything all it does is obscure the actual name behind it. Should we just remove it?

**Comment by petersgiles** [comment]
I agree

**Comment by sergioc** [comment]
Agreed.
