### ISSUE TITLE
Export to png icon

### ISSUE THREAD

**Issue by johnsimons** [Particular/ServiceInsight#526]
![image](https://cloud.githubusercontent.com/assets/122651/11550154/846920ae-99b8-11e5-90cd-8846424c2448.png)

@sergioc can you provide us an icon for the export button ?

**Comment by sergioc** [comment]
Sure - here you go: https://www.dropbox.com/s/25aok9m8i7q4gwx/export-to-image.svg?dl=0

BTW, the button label should read `Export to PNG` (PNG is an acronym, so it should be capitalized)

**Comment by johnsimons** [comment]
Fixed in https://github.com/Particular/ServiceInsight/commit/007a9b571418000aee9573582dac8903e980be31
