### ISSUE TITLE
Unable to clear message list search filtering after searching/filtering message by ID

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#529]
Unable to clear message list search filtering after searching/filtering message by ID. Even if I click the search input clear button and even after pressing enter on an activated search input that is empty, it still won't clear the filter.

The only way to clear the list filter is by restarting SI.

**Comment by HEskandari** [comment]
@sergioc  I just tried with the latest build, can not reproduce this. Could you try again? See if it is a specific scenario/message that has this problem?

**Comment by sergioc** [comment]
I can still reproduce the issue here. Steps to reproduce:

1. Open the sequence diagram
2. Right click on a message
3. Click "Search by Message ID"
4. Attempt to clear the search to see all messages from the conversation in the message list

**Comment by sergioc** [comment]
It seems like it only happens with the VideoStore

**Comment by sergioc** [comment]
@HEskandari that VideoStore data that triggered the issue is now gone here. It could be that the issue only manifests with relatively old data. I reloaded the VideoStore here and will check back in 2 days.

**Comment by HEskandari** [comment]
I did exactly as you described in the steps but couldn't repro. If that happens again, could you zip and also send me the SC database?

**Comment by sergioc** [comment]
OK, I'll keep you posted.

**Comment by HEskandari** [comment]
Did you test this again @sergioc ? Can we close it?

**Comment by HEskandari** [comment]
Closing this one. The actual problem is described in #539
