### ISSUE TITLE
Add a number to duplicated message types and their processing handler labels to help distinguish in exported diagram

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#530]
Add a number to duplicated message types' labels and their processing handler labels to help distinguish which handler belongs to which message in exported diagrams. See following example:

![sequencediagram](https://cloud.githubusercontent.com/assets/493451/11589196/d42b756e-9a86-11e5-8ce3-952e3229b818.png)

**Comment by HEskandari** [comment]
If we're talking about a large diagram that doesn't have the same message / handler type (hence Duplicate as you said), the type would make it distinguishable already, so I think we're talking about this particular type of scenario.

Let me ask this question...What benefit does adding a number have in the above diagram? Once you 'link' the message to the handler in the above scenario, what added insight does that give you, in an exported image.

I think we're now optimizing for the export, which is not part of the issue at hand to begin with. 

Thoughts? @johnsimons @sergioc

**Comment by distantcam** [comment]
> I think we're now optimizing for the export, which is not part of the issue at hand to begin with.

I completely agree with @HEskandari on this. Displaying on screen and exporting are 2 separate problems and we should treat them differently.

**Comment by mauroservienti** [comment]
One option here is to add the message ID in the tooltip displayed on hovering messages
