### ISSUE TITLE
Replace message processing handler message icon

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#532]
Replace message processing handler message icon to make it look like a spinner that may wrongly indicate it's still in progress.

**Comment by HEskandari** [comment]
@sergioc link to the icon?

**Comment by sergioc** [comment]
I still need to create the icon @HEskandari

**Comment by sergioc** [comment]
Update:

![screenshot 2015-12-08 08 54 17](https://cloud.githubusercontent.com/assets/493451/11650483/c798328c-9d89-11e5-9586-faac228e47f6.png)

Icons:
[Normal](https://www.dropbox.com/s/pe5l1jg8hefbl31/processing-handler.svg?dl=0)
[Hover/Selected](https://www.dropbox.com/s/b4l1vtyeeowwcaj/processing-handler-hover-select.svg?dl=0)
[Error](https://www.dropbox.com/s/e3zs3q295i1ww6a/processing-handler-error.svg?dl=0)

**Comment by HEskandari** [comment]
@sergioc we don't have any state for when the handler is in "Error" state. Currently when you mouse-over the handler label that's in error state, it changes to regular 'highlighted' blue.

Unless we change that, I think the "Error" icon above (in red) is inconsistent.

**Comment by sergioc** [comment]
We can discard the error icon, the rest looks great.
