### ISSUE TITLE
Hiding Export and Legend for the Sequence Diagram Release

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#533]
Since we'll need to polish these two functionalities a bit to make it ready for the release, the TF agreed to turn them off for now.

The improvements are discussed in #530 and #523.

**Comment by johnsimons** [comment]
I am confused how did the TF got to the conclusion that removing 2 useful and feature complete features is better then continuous improvement ?

**Comment by sergioc** [comment]
@johnsimons neither of those features are fully there yet for a first release and there's still discussion occurring around them. The TF agreed on ensuring that these should only go out without any known issues or doubts.

This will allow us to focus more on the core improvements to maximize our chances of doing a good release, as early as possible.

**Comment by sergioc** [comment]
@HEskandari are you sure you meant to mention https://github.com/Particular/ServiceInsight/issues/529 in this issue's description?

**Comment by HEskandari** [comment]
@sergioc Thanks, updated.
