### ISSUE TITLE
Keep showing sequence diagram associated with messages showing in list after searching by message ID

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#536]
If I search by message ID in the sequence diagram, the sequence diagram view will show the empty state:

![screenshot 2015-12-09 12 08 40](https://cloud.githubusercontent.com/assets/493451/11684942/8b9f2316-9e75-11e5-9f1e-404a197ce2fd.png)

This doesn't make sense if the messages showing in the filtered list have associated data to produce a seqeunce diagram. This will show if I select the message in that list:

![screenshot 2015-12-09 12 13 06](https://cloud.githubusercontent.com/assets/493451/11684946/919f83f0-9e75-11e5-8dc2-fc86da8db20f.png)

I suggest adding this one to the next release milestone.

**Comment by HEskandari** [comment]
It is a know issue. Me and @johnsimons have spend a bit of time trying to fix it, but it might be a bug with our grid control. Let's schedule this for after the SD release as it is just a bug in general and nothing to do with SD.

**Comment by HEskandari** [comment]
I think this is partially fixed. Now when you search by message Id, the Sequence Diagram does load up that conversation and you wouldn't get the 'Data not available' as before.

There is an issue still which is, the row in the Grid in "Messages" window doesn't get highlighted (although it is selected). There is a known issue when selecting the first row of the grid (e.g. through search by Id) that I have raised and will track separately. 

Can you check if this works now @sergioc?

**Comment by sergioc** [comment]
@HEskandari :+1:
