### ISSUE TITLE
If you left-click or right-click the handler from a message which is not visible on screen, it’ll jump to the message unexpectedly.

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#537]
If you left-click or right-click the handler from a message which is not visible on screen, it’ll jump to the message unexpectedly.

**Comment by johnsimons** [comment]
We currently scroll the enquing side into view, when a message is selected.
I guess we need to ditinguish if the message selection is auto or user initiated

**Comment by HEskandari** [comment]
I think this is working fine as per #517 item "When a message is selected bring into view the message in the sequence diagram". I think it makes sense to do it on the left click only though, which I'll fix.

@johnsimons I'm not sure I follow what you mean auto vs user initiated selection?

**Comment by sergioc** [comment]
Disable the "When a message is selected bring into view the message in the sequence diagram" behavior when the user clicks the handler?

**Comment by HEskandari** [comment]
@sergioc @johnsimons so no scrolling into the view at all?

**Comment by sergioc** [comment]
We keep the scrolling, but only if the message was selected outside the diagram, i.e. via the message list.

**Comment by johnsimons** [comment]
@HEskandari the proposal is to not scroll into view when a user clicks on the grey boxes, but otherwise the scroll into view should work

**Comment by HEskandari** [comment]
@sergioc @johnsimons I've had a look into this today, it is not possible to determine the source of the action, so we can't distinguish between a message selection from the Grid or from the Sequence Diagram, or other sources.

Even if we have one source of truth (one 'thing' publishing the selection changed events as opposed to various UI widgets) we still wouldn't be able to tell who performed that action. 

So the solution is:

 - Keep it as is, scroll the message into the view, regardless of who performed an action and where.
 - Don't perform scrolling into the view at all.

Thoughts?

**Comment by sergioc** [comment]
I think both solutions are far from ideal. @distantcam any thoughts on this?

**Comment by petersgiles** [comment]
I agree with @sergioc, this isn't ideal.

I think it's fine to move to the message selected in the list above the diagram. Reasoning, you are not disrupting the user's current focus - the message list.

Selecting and scrolling to the message when i'm clicking on a handler is bad. You are disrupting my focus, I want to find out about the handler when I click on it, i don't want to scroll somewhere else.

How to fix? Place a ghosted message icon on the edge of the screen (in the direction of the invisible message) clicking the ghost message will bring the message into view

**Comment by HEskandari** [comment]
@sergioc have a play with the latest version, I seem to have miraculously fixed it (thanks to @johnsimons 's idea)
