### ISSUE TITLE
User feedback widget/mechanism

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#538]
Add some sort of mechanism for users to provide feedback in-app. Possibly automatically convert feedback into GH issues automatically.

**Comment by petersgiles** [comment]
A lot of users use this application behind firewalls and are block from connecting to the web. The UI would have to be aware of this.

How would this feature differ from email or using our support or github mechanisms directly? Do you imagine some kind of voting widget that people can vote up or down various features with?

**Comment by sergioc** [comment]
@petersgiles either a simple message input, or something similar to what Microsoft does, which includes an emotions survey, message input and ability to upload a screenshot: 

![send-a-smile-in-office-2013-allows-sending-screenshots-to-microsoft_thumb](https://cloud.githubusercontent.com/assets/493451/11774556/a03085c6-a236-11e5-8930-d408cc15a49d.png)

The important is for us to make users aware that they can send feedback when they use SI, to help generate more feedback.

**Comment by tmasternak** [comment]
Removing `Tag: Consider for Short Term Focus`. @distantcam  Please add `Consider for Promotion` if it's still relevant.

**Comment by sergioc** [comment]
It could also be just a `Feedback` button for opening a new issue in this repo. Similar to the feedback button in ServicePulse or in docs.particular.net

**Comment by HEskandari** [comment]
If a link in the menu is acceptable (e.g. Help -> Feedback...) I'm happy to include this in the next release milestone. What say you @sergioc?

**Comment by sergioc** [comment]
I was thinking of something a bit more visible like a toolbar button. Not as easy to make as the menu item, but more inviting to use.

**Comment by HEskandari** [comment]
I'd say toolbar and menu item are comparable effort-wise. We can even have both, but for toolbar we're going to need an Icon. That plus discussing where it goes on the UI might be the only difference on the effort.

**Comment by sergioc** [comment]
Then I'd definitely go for both.

**Comment by HEskandari** [comment]
@sergioc did you have a specific icon in mind? For the toolbar you'll probably need one (which can be reused for the menu as well). Also where do you want to place it on the toolbar? Should it stick to the right hand side (not sure if possible but checking)

**Comment by HEskandari** [comment]
![image](https://user-images.githubusercontent.com/132117/40952393-74b902be-68be-11e8-87dc-79358b1f1578.png)
![image](https://user-images.githubusercontent.com/132117/40952406-82a96526-68be-11e8-9c60-c09affc1d66c.png)
@sergioc  here's roughly what I have so far.

**Comment by sergioc** [comment]
> did you have a specific icon in mind?

I was thinking of a more prominent button with an icon to increase visibility:

<img width="1171" alt="image" src="https://user-images.githubusercontent.com/493451/40965055-06e3b9b6-68ad-11e8-9a60-bb16239784d3.png">

**Comment by sergioc** [comment]
Agreed on adding a button that links to the opening of a new issue in GH, similar to the feedback button in SP.

**Comment by HEskandari** [comment]
@sergioc you mean this design? Is that how it should look like?
https://github.com/Particular/ServiceInsight/issues/538#issuecomment-394629976

**Comment by sergioc** [comment]
Yep

**Comment by sergioc** [comment]
Icon: https://www.dropbox.com/s/zsew8m8y0o8rano/feedback.svg?dl=0

**Comment by HEskandari** [comment]
@sergioc There was an icon already there for this, so I haven't changed that. Let me know if I should.

**Comment by sergioc** [comment]
@HEskandari which icon was there?
