### ISSUE TITLE
"Only one arrow is allowed to come in" Exception

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServiceInsight#545]
While running pub/sub example on NSB v6 I tend to get below exception quite often. The sample code can be found in here:
https://github.com/WojcikMike/PubSubSample

While trying to open audited message (mostly while clicking EventMessage) this is the exception that I get.

System.Exception: Only one arrow is allowed to come in
   at ServiceInsight.SequenceDiagram.Diagram.Handler.set_In(Arrow value) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\Diagram\Handler.cs:line 40
   at ServiceInsight.SequenceDiagram.ModelCreator.Initialize() in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\ModelCreator.cs:line 106
   at ServiceInsight.SequenceDiagram.SequenceDiagramViewModel.CreateElements(List`1 messages) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\SequenceDiagramViewModel.cs:line 227
   at ServiceInsight.SequenceDiagram.SequenceDiagramViewModel.Handle(SelectedMessageChanged message) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\SequenceDiagram\SequenceDiagramViewModel.cs:line 201

**Comment by HEskandari** [comment]
I ran the sample, this looks to be a bug in ServiceControl.

When I load the conversation, I get two messages, that are pretty much identical, except for the `time_sent` and `delivery_time` (even `id` and `message_id` are the same)

![image](https://cloud.githubusercontent.com/assets/132117/11945386/8307533a-a8a3-11e5-9a22-b180a5d00145.png)

Now as per code, you are publishing an event of type `MySuperPowerAreEnabled` in your publisher, then handling it in the Subscriber2 and publish another instance of the same event type, plus a command of type `LocalCommand`.

The conversation I get from ServiceControl doesn't resemble that (missing local sent `LocalCommand`) and what it does give me (two almost identical messages) feels like a bug.

I have attached the JSON payload I get for that conversation, could a ServiceControl expert have a look? @mikeminutillo 

[Conversation.txt](https://github.com/Particular/ServiceInsight/files/69179/Conversation.txt)

Having said all that, @johnsimons reported so wierd looking diagrams when he was testing v6 stuff. It *could* be that this is a related [issue][1].

[1]: https://github.com/Particular/ServiceInsight/issues/511

**Comment by WojcikMike** [comment]
@HEskandari It is connected to exactly the issue that you refered to. I was investigating that to see if v6 is not doing something wierd. And I came to above issue. 

Regardign my code sample, there is an error there MySuperPowerAreEnabled should simply implements IEvent in which case there would be no hops between publisher and subscriber. However as this shows the issue I will not change anything in the code sample.

**Comment by WojcikMike** [comment]
When I checked sample itself. I noticed that every handler have the message delivered 2 times (observed by @HEskandari). The reason for that is the configuraiton in Publisher (app.config file in MyPublisher - basically it should be gone). After removing app.config and removing subscription in code for MyPublisher. Then every handler is called once. And Insight don't throw exception however displays a bit off sequence diagram:
![image](https://cloud.githubusercontent.com/assets/604826/11979368/11ace650-a993-11e5-95fd-b736e7b4a989.png)

For this moment I left the sample app as an example of very badly written application using nservicebus. I am not sure at this moment how to Insight should behave in such situation.

**Comment by andreasohlund** [comment]
Seems to hit users as well https://app.raygun.io/crashreporting/7gulz9/errors/999916385/

**Comment by WojcikMike** [comment]
To elaborate a bit more, I suspect that there is a discrepancy in how NSB v5 and v6 works. In above examples for v6 I had AutoSubscribe turned on as well as I manually subscribed to the event. This caused that my Event MySuperPowerAreEnabled was delivered 2 times to my handler. 

The same scenario in version 5 does not deliver message 2 times. I will try to confirm this and find where the fault is. And probably raise an issue to discuss this behavior mismatch.

**Comment by johnsimons** [comment]
@WojcikMike as you correctly identified this seem to be a bug in the v6 core, is it ok with you if I close this one ?

**Comment by WojcikMike** [comment]
@johnsimons Yes I agree, it is not a problem of Insight nor ServiceControl. However I wonder if the error of a bad message should cause ServiceInsight to close. But this is loosely connected to this issue.

**Comment by HEskandari** [comment]
@johnsimons is there any better way of doing it, other than throwing an exception? Knowing that exceptions will bubble up and display as unhandled exception dialog.

**Comment by johnsimons** [comment]
@WojcikMike I agree, ServiceInsight should be more resilient to these issues.
@HEskandari how about the same way we display a "no data" splash, we could display a "could not parse data" splash ?

**Comment by HEskandari** [comment]
To me "could not parse data" is vague. "Why couldn't you??". Do we also need to point them to a documentation page explaining how to resolve it, or how to investigate?

**Comment by johnsimons** [comment]
@HEskandari hard to say, we may be able to provide a better message, but not sure if we can tell them how to resolve it.
But @HEskandari what do u think about the idea of handling this case this way and not crash ?

**Comment by WojcikMike** [comment]
For me it seems that above situation is caused by a bug in NSB core, which means that we should be informed by the bug ideally ASAP. So maybe the message should be:
"There was an error processing the message, please contact particular help desk to help to resolve it".

However assuming that this error don't occur for every message we should allow to browse through other messages.
@HEskandari @johnsimons what do you think?

**Comment by johnsimons** [comment]
@WojcikMike I think this would work, I wonder if we should include the option for the user to include the payload so we can better identify the issue, so in essence SI would email a report to support with an attachment

**Comment by HEskandari** [comment]
But they can always report the "bug" to us, why do we have to automate it? Specially since we know it is a data issue so we can't really do anything with the reported data?

@johnsimons I can see two ways of handling this case:

- Not rendering the diagram at all, preferably with a message in Statusbar or canvas (albeit a generic message).
- Displaying as much of the diagram as we can. The diagram, however, might look *weird*.

**Comment by HEskandari** [comment]
We've already tackled this by displaying an error message like this: 
![image](https://cloud.githubusercontent.com/assets/132117/16324872/b72cff40-39fb-11e6-8806-b4b282267164.png)

Is this enough? Anything else that needs to done here? @WojcikMike @johnsimons

**Comment by johnsimons** [comment]
@HEskandari this was a long time ago, I am sorry I cannot recall

**Comment by WojcikMike** [comment]
@HEskandari that is perfection itself, let me close this issue
