### ISSUE TITLE
ServiceInsight crashes when saving options on German Windows 10

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceInsight#547]
I was testing a release of ServiceControl on a German Windows 10 and found this issue in ServiceInsight 1.5.1
If I go to View->Options  and then change anything and press "Save"  ServiceInsight crashes completely. 
The exception is not caught by the "oops" screen. 
Tried the pre-release of 1.5.2 and same issue occurred

**Comment by distantcam** [comment]
Confirmed, this is a Costura bug.

I'm thinking we don't need Costura, since SI has an installer, so I'll just remove it.

**Comment by johnsimons** [comment]
I put a PR for this one

**Comment by johnsimons** [comment]
This is actually a pre-step for the auto-update

**Comment by gbiellem** [comment]
@johnsimons Is the auto-update still on the cards? I thought you had shelved it.

**Comment by distantcam** [comment]
Fixed by #549
