### ISSUE TITLE
Sequence diagrams render elements in weird order

### ISSUE THREAD

**Issue by WojcikMike** [Particular/ServiceInsight#552]
While running my pub/sub sample:
https://github.com/WojcikMike/PubSubSample
That uses latest version of NSB v6 prerelease. The sequence diagrams that are rendered in ServiceInsight are a bit off:
![image](https://cloud.githubusercontent.com/assets/604826/12195784/1b7b2f02-b5fa-11e5-88e1-a49f28245411.png)

I wanted to learn if this is a bug in SI or are there still issues in NSB core.

**Comment by johnsimons** [comment]
@WojcikMike I guess that is easy to find out, all we need to do is run the same sample against v4 and v5 and compare the results, do u think that will work ?

**Comment by WojcikMike** [comment]
Make sense, ported solution for v5 results in following diagram:
![image](https://cloud.githubusercontent.com/assets/604826/12198512/fdb68036-b610-11e5-8083-bcb176bc0f72.png)

I don't have the sample for v4 but can do it if needed.

**Comment by WojcikMike** [comment]
After analyzing the json files for v5 and v6 it seems that MessageIntent is set up incorrectly for v6. 
[v5 results.txt](https://github.com/Particular/ServiceInsight/files/96888/v5.results.txt)
[v6 results.txt](https://github.com/Particular/ServiceInsight/files/96889/v6.results.txt)

I will create a bug in NSB to fix it and then I will run the above samples again to see if the diagrams look better or not. So at the moment this issue is blocked until we fix: https://github.com/Particular/NServiceBus/issues/3344

**Comment by WojcikMike** [comment]
After fixing above bug I run the tests and still the diagram is sometimes off. The results file 
[v6 results.txt](https://github.com/Particular/ServiceInsight/files/126508/v6.results.txt)

shows that processed_at header is not set to right value but holds "0001-01-01T00:00:00Z". Separate issue will be created in NSB.

**Comment by WojcikMike** [comment]
As the above bug was fixed, I rerun my sample and the outcome looks good:
For v6 happy path is in good order and everything looks as it is expected:

![image](https://cloud.githubusercontent.com/assets/604826/13282978/dd435a18-daeb-11e5-8d1c-e88390e87cf3.png)

No when I thrown exception the diagram don't look so good as message handler for Subscriber 1 is above the arrow:
![image](https://cloud.githubusercontent.com/assets/604826/13283063/43335b98-daec-11e5-8588-1642122712c4.png)

**Comment by WojcikMike** [comment]
Ok after fixing the above bug with time_sent my scenarios looks good:

1. Happy path scenario, everything is in order without errors or misaligned arrows:
![image](https://cloud.githubusercontent.com/assets/604826/13428555/7fecc244-dfbb-11e5-8b18-e21fa1ea3af4.png)

2. Example with exception being thrown in one of the handlers
Subscriber 1 throws:
![image](https://cloud.githubusercontent.com/assets/604826/13428626/fb510724-dfbb-11e5-9afb-1cfd14edc6e6.png)

Subscriber 2 throws:
![image](https://cloud.githubusercontent.com/assets/604826/13428633/03683220-dfbc-11e5-8d3f-11b024458599.png)

Both subscribers throws exception:
![image](https://cloud.githubusercontent.com/assets/604826/13428661/2ad8f57e-dfbc-11e5-856f-200a38c94eda.png)

All of the diagrams are in right order so the diagrams of v6 looks good in Service Insight. I will close this issue. @andreasohlund as he might be interested
