### ISSUE TITLE
ServiceInsight Licensing Enhancements

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#569]
ServiceInsight needs to show license information is a more user-friendly fashion and highlight the important information that the user needs to know about. 

- Show Expiration Date / Upgrade Protection Date in the license dialog.
- Show a warning message when the expiration date or upgrade protection date is getting closer so that the user is informed and can renew their license on time.
- Displaying license type (Perpetual/Enterprise/Trial) in the license dialog.

**Comment by YifatS** [comment]
@HEskandari - I'm not familiar with the behaviour of the platform and the different solutions, but shouldn't we look to have the same text and the same behaviour in all?

**Comment by HEskandari** [comment]
Resolved by #812
