### ISSUE TITLE
Connecting to more than one ServiceControl instance

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#575]
The endpoint explorer should behave more like SSMS in that it shows all the Service Control instances it's connected to with the ability to drill down into specific ones to view the queues.

This was proposed as a part of #574

**Comment by HEskandari** [comment]
This seem to have been already implemented. Do we need to coordinate a release @distantcam? Related to #574.

**Comment by distantcam** [comment]
@HEskandari It has? I hadn't fully done it yet. RxServiceControl has the capability, but isn't used everywhere.

**Comment by HEskandari** [comment]
@distantcam definitely there's some sort of support. Thought it might have crept in with the Rx changes. Here's how it looks. 

![image](https://cloud.githubusercontent.com/assets/132117/19507746/ae4be6ee-9620-11e6-8736-4eb128cd0ef6.png)

**Comment by distantcam** [comment]
Huh! Ok that's definitely a side effect of the rx changes I've been making. I wouldn't close this yet, there's still some features to work out (removing endpoints comes to mind).

For now we should probably turn off this feature in master and then work on it in a branch.

**Comment by MpDzik** [comment]
+1

**Comment by HEskandari** [comment]
Resolved by #978
