### ISSUE TITLE
Missing message ID, and other data unavailable

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#576]
From http://stackoverflow.com/questions/36621031/nservicebus-serviceinsight-empty-flow-diagram-and-sequence-diagram (also in desk case)

- I started ServiceControl (Set audit forwarding on)
- I Started ServiceInsight (with default api url, which is ok)
- I Downloaded StepByStep sample from nservicebus site, and added audit forwarding config class

```csharp
class ConfigAuditQueue : IProvideConfiguration<AuditConfig>
{
    public AuditConfig GetConfiguration()
    {
        return new AuditConfig
        {
            QueueName = "audit"
        };
    }
}
```

As you can see in the screenshot, it is connected to msmq api and can fetch the messages. However Flow Diagram and Sequence Diagrams are empty.

Why is that, any ideas?
Is it related to the Unknown Message ID ? (Although it is known in Header)

![screenshot of SI](http://i.stack.imgur.com/J9val.jpg)

Here is also MSMQ installed features screenshot and versions for helping error recreation.

ServiceControl v1.12.0
ServiceInsight v1.5.6

![screenshot of MSMQ install options](http://i.stack.imgur.com/mShNO.png)

**Comment by HEskandari** [comment]
Think this can be closed now. The bug is logged and can be tracked under ServiceControl repository [here](/Particular/ServiceControl/issues/717).
