### ISSUE TITLE
When an endpoint has large amount of messages, performance is slow

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#577]
When SI is working with a large amount of messages, there are following problems:
- Startup time (too slow to load)
- Also when an endpoint has 1000s of messages, it takes a while for the view to load up the messages.

Reported by Customer.

**Comment by kevin-whalley-gc** [comment]
For example a queue with 76560 takes 3 seconds to load the first page, but the UI further locks up until the 'tab' (Flow Diagram, Body etc) loads as well

Since we don't know with certainty how many messages might be in a queue switching between them can be tedious

Also, when connecting to a given environment, regardless of the # of queues it seems to take some time which I believe might be related to # of messages

**Comment by HEskandari** [comment]
I'm testing this with the latest released version. On app launch, I'm connected automatically to an SC endpoint that has 1,482,318 messages. I don't notice that much of a delay and the start up time is comparable with another endpoint that has only a few hundred messages.

I'm thinking this might be unrelated to the number of messages in the endpoint/queue as we only load one page upfront (e.g. hundred items). It might be more issue of Sequence Diagram (or the view that is on focus when application is loaded) loading its data.

@kevin-whalley-gc Could you please re-test with the latest release? Also note which view is displayed after launch and what is the nature of the conversation that is being loaded. In Sequence Diagram / Flow Diagram terms, how many messages are in that particular conversation that is loaded? 

Do you have this issue if, say, Body tab is selected on launch? To test it, select the body tab, exist the app and relaunch so it is pre-select on subsequence app runs.

**Comment by HEskandari** [comment]
@indualagarsamy Did you ever test this with a customer database? This is a few months old now, but do you have any more details?

**Comment by kevin-whalley-gc** [comment]
Hi @HEskandari,

I retested with 1.5.9

- App startup is observed to take ~30 seconds
- Switching between an endpoint of 434 messages to an endpoint of `2579893messages takes in excess of 15 seconds. (the cursor transitions to a waiting state and the entire application goes blank in some scenarios)

The view for both of these scenarios was body

**Comment by HEskandari** [comment]
@kevin-whalley-gc I'm still trying to narrow this down. Would be great if you could clarify whether you're connected to a local ServiceControl or if that is on the network?

**Comment by kevin-whalley-gc** [comment]
Hi @HEskandari,

Our ServiceControl instance is on a separate host from ServiceInsight

**Comment by HEskandari** [comment]
@kevin-whalley-gc thanks for confirming it. The scenario I've been testing was both SI and SC were running on the same machine so the operation was not network bound. I'll move my SC to a remote machine and see if I get the same behavior.

**Comment by indualagarsamy** [comment]
@HEskandari - feel free to reopen the issue if the problem still persists. Closing.
