### ISSUE TITLE
Add 'ProcessingStarted' Column to Message List

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#578]
Add 'ProcessingStarted' Column to Message List or have a 'column chooser' feature.

**Comment by HEskandari** [comment]
Does this requires persistence of column states between app restarts? 

Think this issue along with other [View:MessageList](https://github.com/Particular/ServiceInsight/labels/View%3A%20Message%20List) labels will be superseded by the Particular/PlatformDevelopment#270.

**Comment by adamralph** [comment]
Withdrawn in favour of #708

**Comment by adamralph** [comment]
BTW - thanks @cjoergensen for raising this. We will consider this column, as well as others, in #708.
