### ISSUE TITLE
High DPI experience

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#582]
## Installer

![image](https://cloud.githubusercontent.com/assets/152998/15356044/9b34ebd0-1cf6-11e6-9da5-6cab5750e26c.png)

Logo isn't crisp on high DPI displays.

## Splash screen

The graphics on the splash screen are not crisp on high DPI displays.

![image](https://cloud.githubusercontent.com/assets/152998/15356097/e9a97826-1cf6-11e6-801d-dcb42bf361c9.png)

## License dialog

![image](https://cloud.githubusercontent.com/assets/152998/15356250/f13a5c4e-1cf7-11e6-8cbe-16bbcc43db69.png)

## Icons

![image](https://cloud.githubusercontent.com/assets/152998/15356193/9d6d7fec-1cf7-11e6-8edf-c66782d79c56.png)

![image](https://cloud.githubusercontent.com/assets/152998/15356198/a8137758-1cf7-11e6-9bce-3e23a6306e83.png)

![image](https://cloud.githubusercontent.com/assets/152998/15356215/bde72b38-1cf7-11e6-8209-411504cd8976.png)

![image](https://cloud.githubusercontent.com/assets/152998/15356223/c7db53b2-1cf7-11e6-946c-766707bc707c.png)

**Comment by HEskandari** [comment]
@ramonsmits what's the DPI exactly?

Think this belongs to /Particular/platformInstaller as it is an installer issue and applies to all the other products installed through the PI as well.

**Comment by distantcam** [comment]
Yeah same problem as #504. I'll close this one as a duplicate.
