### ISSUE TITLE
Splash screen high DPI and duration.

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#583]
It also is pretty annoying that the splash screen is displayed for quite some time. Its 8-10 seconds and then the applications pops up.

**Comment by distantcam** [comment]
The duration is based on the startup of the app, which from a cold boot can take some time. In any case that's outside our control.

The DPI is a bug.

**Comment by distantcam** [comment]
I'm going to close this as a duplicate of #504.
