### ISSUE TITLE
Messages transformed by message mutators can not be displayed properly

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#587]
There are some cases where the message is 'transformed' via a mutator and the copy of the message that is sent to the audit queue is not comprehensible. 

Provide a mechanism for the user/developer to provide their mutator logic in order to transform the messages back for the viewing purpose.

This could be done by:
- Supporting existing message mutator api from the core to do the transformation
- Providing a more generic addon approach where the user can plug-in their own logic.

Other cases where this is useful might be where message encryption is used or where there are attachments (via DataBus)

**Comment by RossJayJones** [comment]
+1

**Comment by ramonsmits** [comment]
Seems https://github.com/Particular/ServiceInsight/issues/467#issuecomment-136332914 had a customer request to have the ability to decrypt messages.

**Comment by ramonsmits** [comment]
Just had a request if SI supports incoming pipeline to extend with custom behavior just as any other nservicebus endpoint to be able to decrypt their full message body encryption.

**Comment by mauroservienti** [comment]
Merged into https://github.com/Particular/ServiceInsight/issues/467
