### ISSUE TITLE
ServiceInsight keeps saying trial has ended even though a license key is installed correctly

### ISSUE THREAD

**Issue by mauroservienti** [Particular/ServiceInsight#590]
A customer riased an issue in a [support case](https://nservicebus.desk.com/agent/case/18537) related to a licensing misbehavior.

They installed the licenses in the registry as per our documentation:

![image](https://cloud.githubusercontent.com/assets/1325611/16590153/a55a2020-42d6-11e6-8b5f-a7c926f94006.png)

![image](https://cloud.githubusercontent.com/assets/1325611/16590174/bdbaf2ac-42d6-11e6-9404-d5b9473701de.png)

however SI kept saying that the license was expired:

![image](https://cloud.githubusercontent.com/assets/1325611/16589991/f58e5a1c-42d5-11e6-9916-67aa99fa0f57.png)

The workaround that fixed the customer issue was to create a License registry key, with a propre license, even under `HKEY_CURRENT_USER\SOFTWARE\ParticularSoftware`

--

Don't know if this is already included in https://github.com/Particular/ServiceInsight/issues/569

**Comment by HEskandari** [comment]
This issue is resolved in #580. We're now looking for a valid, unexpired license under both HKLM and HKCU. The release will be out soon.
