### ISSUE TITLE
Backslashes not shown in message body

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#594]
Backslashes in the body are not shown. Expected either one slash or an escaped (double slash)

```
{
  "OrderId": "123\ABC"
}
```

![image](https://cloud.githubusercontent.com/assets/152998/17108070/432d3ff6-5292-11e6-880f-389004b6861f.png)
## References:
- https://nservicebus.desk.com/agent/case/18649

**Comment by HEskandari** [comment]
@ramonsmits this has been addressed as a part of #596. Here's how it looks now. Is it acceptable? Should we close the issue?

![image](https://cloud.githubusercontent.com/assets/132117/20159679/70e5f872-a736-11e6-977e-d1e3921da261.png)

**Comment by adamralph** [comment]
Does that mean we fixed both this bug and #596 in https://github.com/Particular/ServiceInsight/pull/620 ?

**Comment by HEskandari** [comment]
That is my understanding @adamralph

**Comment by adamralph** [comment]
OK. In that case, shall we close it, add it to the 1.5.8 milestone and update the release notes?

**Comment by HEskandari** [comment]
@adamralph I'm 👍 on that.

**Comment by adamralph** [comment]
Closed in #620.

**Comment by adamralph** [comment]
Done. I also:
- added a fix link from #620 to here
- altered the title of #620
- posted a reply to the ggroups announcement adding this bug fix

**Comment by HEskandari** [comment]
Excellent @adamralph!

**Comment by ramonsmits** [comment]
@HEskandari That isn't just acceptable... that is great ;-)
