### ISSUE TITLE
JSON Message Body is not displayed correctly, if the message contains HTML

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#596]
The JSON formatting gets messed up, when the message contains HTML tags:

![untitled](https://cloud.githubusercontent.com/assets/8087733/17292271/3556163a-57e9-11e6-8450-cc97336ceb17.png)

**Comment by HEskandari** [comment]
It looks like the escaped double quotes are breaking the rendering. I'm investigating a bit more to see what are the exact cases.

**Comment by adamralph** [comment]
Added to 1.5.8 milestone.

**Comment by adamralph** [comment]
We are reverting master to 1.5.7 in #617 so this bug will have to be fixed again.
