### ISSUE TITLE
Saga View shows updates in incorrect order

### ISSUE THREAD

**Issue by mikeminutillo** [Particular/ServiceInsight#598]
![image](https://cloud.githubusercontent.com/assets/124014/17723716/e2884fb2-646e-11e6-94e5-1554e06698bf.png)

I'm pretty sure that this is related to [change in ServiceControl that happened in April](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControl/SagaAudit/SagaDetailsIndex.cs#L52).

ServiceInsight is displaying changes in the order that SC serves them up. Is this a UI concern? Should we change it in SC or should SI always define a sort order?

**Comment by HEskandari** [comment]
I'd say it is a UI concern, much like #570 although in a different view.
