### ISSUE TITLE
Fix thread synchronization issues in master

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#607]
There's a few threading issues with the latest build off the master:
- When running on a customer database I end up in an infinite loop on startup. The code for refreshing the UI keeps running.
- The WorkStarted/Finished events are received out of order so the main shell thinks there's a work in progress while there isn't. When this happens, it would not be possible to connect to another instance of ServiceControl as the menu grays out.

The issue is due to how events are marshalled between threads (background and main).

**Comment by distantcam** [comment]
Fixed in the pirac merge.

**Comment by adamralph** [comment]
Was this a problem in 1.5.7 or only in master? If the latter, we should remove the 1.5.8 milestone since the fix is irrelevant wrt to production versions.

**Comment by HEskandari** [comment]
@adamralph this happened after releasing the 1.5.7. 👍 on removing the milestone.

**Comment by adamralph** [comment]
We are reverting master to 1.5.7 in https://github.com/Particular/ServiceInsight/pull/617 so this bug effectively never existed.
