### ISSUE TITLE
Handler orders are non-deterministic

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#609]
As per to screenshots below, the handler box for "BillingProductUpdatedNotification" under endpoint "Esb.Subscribers.MsCrm.Default.v1.1" appears out of order and should be placed under the connecting-line with the arrow:

![image](https://cloud.githubusercontent.com/assets/132117/19756240/e6fdb58e-9c66-11e6-930d-d1919798de18.png)

The very similar message next to it renders the same conversation correctly:

![image](https://cloud.githubusercontent.com/assets/132117/19756261/05cc4912-9c67-11e6-8222-e5d2273748c8.png)

**Comment by kbaley** [comment]
We have triaged this issue and will be considering it for inclusion in one of the upcoming maintenance releases for this package.

**Comment by ramonsmits** [comment]
Cannot be reproduces, likely fixed in https://github.com/Particular/ServiceInsight/releases/tag/1.6.3 via https://github.com/Particular/ServiceInsight/pull/640
