### ISSUE TITLE
NRE when auto-connecting to a ServiceControl instance that is no longer available

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#613]
Steps to reproduce:

1. Start SI and connect to an instance of SC
2. Exit SI
3. Stop or remove that instance 
4. Start SI

Upon startup SI tries to connect to the previously connected instance, but it throws an exception. The application crashes on Splash screen.

**Comment by adamralph** [comment]
We are reverting master to 1.5.7 in #617 so this bug will have to be fixed again.

**Comment by distantcam** [comment]
@HEskandari I can't reproduce this bug now, it may have been caused by my rewrite of the endpoint explorer.

**Comment by HEskandari** [comment]
@distantcam Just tested the issue and couldn't repro. Closing now.
