### ISSUE TITLE
SagaView cuts off property values if longer than certain length

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#624]
This is very common issue when it comes down to dates but is not limited to any specific type. Here's an example where there's no way finding out what the value actually changed to:

![image](https://cloud.githubusercontent.com/assets/132117/20160619/73b4189e-a73c-11e6-849d-3db149a2865f.png)

Note that is not related to users' screen resolution as the Saga update panel has a fixed width.

**Comment by sergioc** [comment]
Seems to depend on length of property name. This could be addressed by:

1) Auto-expand width to fit longest line
2) Optimize that equal character by replacing with colon and remove redundant non breaking spaces: `PropertyName =    Time stamp` > `PropertyName: Time stamp`

**Comment by adamralph** [comment]
Regardless of the problem itself, I think we should make the contraction that @sergioc suggested in order to mitigate the problem, so in this case it would be

> LastWorkRequestedAt: 9/11/2016 11:57:41 PM→9/11/2016 11:58:33 PM

This of course will not fix the problem generally since the text could still be too long for some properties. 

Another solution that springs to mind is a tool-tip which contains the full text, but that has the disadvantage of not showing for all properties when a screen shot is taken. It would also probably need to be suppressed for the cases where the text *does* fit into the view, but I'm not sure how easy that is to determine. On balance, a tool-tip probably isn't a very good solution.

Auto-expanding is probably the best solution. Is it easy enough to do, and would the layout accommodate it?

**Comment by HEskandari** [comment]
An alternative is to use tooltips. This is used somewhere else in SagaView as well. 

![image](https://cloud.githubusercontent.com/assets/132117/20170716/77390be2-a781-11e6-9ad8-eceb0f19faf7.png)

**Comment by sergioc** [comment]
@adamralph there should be non-breaking spaces around that arrow.

@HEskandari is there a lack of screen real estate to justify adding tooltips? Perhaps width should be responsive so that it would only truncate if the display size is small, in which case you show tooltips?

How important is it to have the info fully visible at a glance? If very important, then you should avoid tooltips unless it's impractical to use more display real estate for the saga.

**Comment by adamralph** [comment]
> @adamralph there should be non-breaking spaces around that arrow.

@sergioc 👍 

I also agree that we should investigate expanding the view, falling back to tooltips only at the limit of expansion.

**Comment by HEskandari** [comment]
I agree on the down sides of the tooltip. Let me run a different sample (larger text, different types etc.)  and see how current behavior is and what is the potential solution look like.

**Comment by HEskandari** [comment]
Two things discovered when doing further testing:

1. Currently the diagram / panels readjust based on size. When you make the "Messages Properties" smaller (or hide the dockable window) there's more room and the diagram re-adjusts. To me took some time to figure it out, so I'd say it is not intuitive enough.

2. The texts larger than certain size are displayed in a popup. Same popup is used to display binary data since they are larger to fit the width by nature.

I'm concluding that it is just date/time type values being a little cut off so by extending the minimum width on the main panel so that date/times are not cut off, we should be good. Doing that will make the vertical scroll bars appear, which may be undesirable from design standpoint. 

Same view when "Message Properties" window is made smaller:

![image](https://cloud.githubusercontent.com/assets/132117/20199572/818bbce2-a7ff-11e6-8ce1-280e47820a01.png)

The alternative is just to leave it as is and close the isse, since the view *is* reacting to size changes.

Thoughts on this?

**Comment by adamralph** [comment]
Given that you can bring the rest of the date in to view by adjusting your layout, I vote for withdrawing this. It feels like the ROI doesn't justify spending more time on it.

**Comment by sergioc** [comment]
I think we should have a quick call to demo the problem before we take further conclusions. Doesn't make sense to discuss behavior in text. Call scheduled.

**Comment by HEskandari** [comment]
While testing the Saga View a bit more, I can see there are all sorts of usability issues with it. See the screenshot:

![image](https://cloud.githubusercontent.com/assets/132117/20250265/d46020c6-aa60-11e6-88b8-2b35fe49801f.png)

The problems I can see from this customer database is:

1. Probably the biggest concern is that there's absolutely no good way to access the entire saga data:
 - You see it only on screen when it is small (for whatever benefit that gives you)
 - As soon as it gets slightly larger, there's no way to see the data. (resizing doesn't help, tooltip only shows partial)
 - You'll have to scroll quite a bit to get to the bottom of the long object graph. That's only for one message. If Saga has a few message, it will get *very* long and all you see is partial garble

2. There's no way to copy out saga data for each message (to email / send to someone or compare each message's data).

3. The middle panel (property diff view) has issues on its own
 - Some properties have no right hand side value (after '='). It is confusing.
 - The 'link' to open the detail view is not intuitive. Mouse cursor doesn't change on hover, it is not highlighted enough and is static.
 - Some property names are trimmed ("...") even there is space available. No tooltip is shown either.

While this may not be entirely related to this specific issue, thought to raise awareness before our meeting and see if I should create separate issues for each or one bucket issue for all.

**Comment by sergioc** [comment]
It already sounds like it needs multiple issues.

**Comment by adamralph** [comment]
I believe we should separate as much as possible into issues which can be fixed and released independently of each other.

**Comment by HEskandari** [comment]
Happy to split into multiple issues once we discuss and agree.

**Comment by HEskandari** [comment]
Here's the summary of our meeting at 15/11/2016:

We decided to split the issue into the following:

- Showing the 'Detail view' for the all objects (in the middle panel and right / left hand panels) as a generic way to display saga data. We'll remove the threshold and use ellipsis when the content gets long. User will be able to see all the trimmed property names and values in the detail view.

- Displaying the null values properly somehow, instead of showing nothing on the right hand side of the "=" sign.

- Replacing the detail view popup with a standard resizable window that behaves and looks the same as other dialogs (e.g. connection dialog). The window should *not* remain on the top when switching to other Windows applications.

- Fix the scrollbars within the 'Detail View' to work consistently. Unnecessary scrollbars should be hidden. When scrolling scrollbar sizes should remain the same regardless of the content that is within the view.

- Add individual scrollbars in the message content panels, as per #452, so that you don't have to scroll the whole view.

Did I miss anything? @adamralph @sergioc

**Comment by HEskandari** [comment]
I'd also suggest getting rid of the tooltip, since with the new detailed view which shows the whole data, it'd be useless (not that it served a real purpose before).

**Comment by sergioc** [comment]
@HEskandari LGTM

**Comment by HEskandari** [comment]
This is split into five issues. I believe this can be closed now as we track each issue individually.

**Comment by adamralph** [comment]
Thanks @HEskandari
