### ISSUE TITLE
Replace paging in message view

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceInsight#628]
Extracted from a suggestion by @johnsimons:

> No paging buttons (UIs have evolved), we just display a "load more";

---

After discussion with @Particular/serviceinsight-maintainers we believe there may be several ways to do this, e.g. "Load more" could be implemented either explicitly with a button saying "Load more" or implicitly by simply scrolling to the bottom of the view (with an appropriate visual indicator that more items exist).

**Comment by HEskandari** [comment]
Doesn't add much benefit and loses the ability to skip to a specific page.
