### ISSUE TITLE
Update License agreement in the installer.

### ISSUE THREAD

**Issue by indualagarsamy** [Particular/ServiceInsight#635]
Related to https://github.com/Particular/NServiceBus/pull/4280, we are working to change the license agreement and privacy policy to be compliant. 

Once we have the right text, SI Installer will need to reflect that.

cc / @kbaley

**Comment by sergioc** [comment]
But will SI also phone home?

**Comment by adamralph** [comment]
As a member of @Particular/serviceinsight-maintainers, I'm not aware of any plan to do so.

**Comment by kbaley** [comment]
I think it's more a matter of ensuring all products use the same language.

**Comment by indualagarsamy** [comment]
@adamralph @sergioc - When we install these products, the license agreement that we display is the same. Therefore the text needs to be updated. We will document the reasons in the NServiceBus PR and link that to all these license agreement issues as well. That should add the visibility you seek.

**Comment by adamralph** [comment]
👍 I agree that all products should use the same EULA.

**Comment by indualagarsamy** [comment]
The correct link to the evaluation license agreement is here:
https://docs.google.com/document/d/1ulv4Q0jIe8CZZt3p97Y_jLFEFWigL5dtWd3fLCXRqAw/edit#

**Comment by gbiellem** [comment]
> But will SI also phone home?

Auto-Update is a form of phoning home and that has been proposed by @distantcam

**Comment by adamralph** [comment]
In that respect, it's good that we're making this update, since we can then add the auto-updating later without having to change the EULA.
