### ISSUE TITLE
MessageFlow diagram does not display saga icons

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#636]
This seem to be a regression. See the picture below:

![image](https://cloud.githubusercontent.com/assets/132117/20414162/305e2068-ad85-11e6-8b77-319e87505c67.png)

@sergioc do you recall us displaying icons here? was it based on sage state (initiated/update, etc.)?

**Comment by distantcam** [comment]
The problem is in XamlIcons.xaml some of the icons were changed from Rectangle/Path to Path/Rectangle so the rectangle is displayed over the icon.

This changed in 3bee738f00b48a27e67bcc71c470b3dfe1ba99f7
