### ISSUE TITLE
Null values are not represented in SagaView

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#642]
In the SagaView panels the null values are left empty on right hand side of the equal signs ("="). The lack of value should be clearly communicated. 

Options are using `<Null>`, `<Nil>` or `N/A`.

This is a split of #624.

Depends on Particular/ServiceControl#889

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers I changed the title to be worded more as a bug.

**Comment by HEskandari** [comment]
So the culprit is JsonPropertiesHelper where we do the actual conversion.

**Comment by adamralph** [comment]
@HEskandari do you mean this? https://github.com/Particular/ServiceInsight/blob/7df7a52f1d4026f4dcd3ad91e65138a7687d81e6/src/ServiceInsight/Saga/JsonPropertiesHelper.cs#L13

I guess the simple fix there is to change that line to:

```C#
.Select(f => new KeyValuePair<string, string>(f.Key, f.Value?.ToString()))
```

If we do that, presumably we will still have to do some work in the UI components to display something when the `Value` is `null`? (I think we agreed on _null_ in grey italics?)

Also, will the rest of the code continue to function correctly when `null` values start appearing in that list?

**Comment by HEskandari** [comment]
@adamralph that seem to be the culprit. Testing should be relatively straight-fowrad but I haven't managed yet. Planning to give it a try this week and send a PR unless someone else beats me to it.

**Comment by adamralph** [comment]
Updated the description to convey the choice of solution.

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers I've just realised that we are not colouring the null values grey. They italic, but not grey:

![image](https://cloud.githubusercontent.com/assets/677704/23629099/e311a7b2-02b6-11e7-90cb-4d2c5ce876a6.png)

Should we change them to grey? Or leave as-is?
