### ISSUE TITLE
'Detail view' popup is not behaving as an standard window or popup.

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#643]
- Replacing the detail view popup with a standard resizable window that behaves and looks the same as other dialogs (e.g. connection dialog). 
- The window should not remain as the top window when switching to other Windows applications.
- The window should be non-modal (but still sit above the main app window).

This is a split of #624.

**Comment by adamralph** [comment]
Re-opening. @sergioc [said](https://github.com/Particular/ServiceInsight/pull/692#issuecomment-288004602):

> ![image](https://cloud.githubusercontent.com/assets/677704/24116386/e92f63aa-0da6-11e7-9702-ec7c513ae907.png)
> 
> I think this view could use a bit of padding around the window borders - otherwise the content looks too tight crowded.
> 
> As for text wrapping, code editors don't wrap text AFAIK. Won't the wrapping give the illusion there's multiple lines of text when that is not true? How about making wrapping an option instead?

**Comment by adamralph** [comment]
@HEskandari would it be an option to remove the wrapping for now, so that we can close this and release 1.7.0 with just the window mechanism changed? If so, we can revisit the wrapping (and an option for it) in a later release.

**Comment by HEskandari** [comment]
@sergioc RE the wrapping, code editor do have an option to enable wrapping, but here it is not just cosmetic. That's the only way to address #644. Also it just wraps the lines _visually_ but it doesn't mean it adds non-existing lines, e.g. if copied out the content would still be as many lines as it originally was.

**Comment by HEskandari** [comment]
@adamralph There's also the padding that needs to be added. Should we take these two issues entirely off that milestone? Or alternatively, we could just add the padding and release. I think it is best to keep the wrapping an not make it an option as the scroll bars would act weirdly when content is not wrapped.

**Comment by adamralph** [comment]
@HEskandari we can't take the two issues off the milestone since #692 is merged. We need to do any remaining work before releasing 1.7.0.

I tried it with wrapping disabled and everything seems fine:

![image](https://cloud.githubusercontent.com/assets/677704/24139162/5784ffee-0e1b-11e7-8fff-3265114fc033.png)

It seems #644 is still fixed, with wrapping disabled.

**Comment by HEskandari** [comment]
@adamralph you don't observe the problem because all the lines in the view have the same length. If you have more than one page of data with different length you should be able to repro the issue.

**Comment by adamralph** [comment]
@HEskandari but in that case, I'm not sure there is a problem. I wouldn't expect the horizontal scroll bar to keep adjusting as I scroll vertically. Can you point to an example of such a UI?

**Comment by adamralph** [comment]
So it turns out that the UI that I was not expecting is actually the behaviour, when wrapping is disabled.

![scroll](https://cloud.githubusercontent.com/assets/677704/24141776/cb5cd992-0e24-11e7-9de0-c1a8b7732aec.gif)

I kind of like this.

**Comment by adamralph** [comment]
It turns out we should have discussed this on #644. Re-closing this issue and re-opening #644 instead.
