### ISSUE TITLE
Scrollbars are behaving inconsistently in 'Detail view'

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#644]
- Unnecessary scrollbars should be hidden. 

This is a split of #624.

**Comment by HEskandari** [comment]
@Particular/serviceinsight-maintainers This is already done as a part of #692 where I opted using content wrapping instead. That means the content will get wrapped if larger than available width and no horizontal scrolling will ever appear. 

This is the only reliable and low effort way I could fix this with. I'm happy to send a separate PR for that, but it is basically setting one property.

**Comment by distantcam** [comment]
If we're going to turn off wrapping then the dialog should be resizable.

Come to think of it, the dialog should be resizable anyway.

**Comment by adamralph** [comment]
Can we deal with that in another issue? This issue improves the window, even if it doesn't contain all possible improvements. IMHO, we can switch wrapping back on and release this.
