### ISSUE TITLE
Showing message data issues multiple requests to ServiceControl

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#647]
The "Show Data" feature in SagaView essentially issues a LoadBody request to ServiceControl. The current approach issues multiple request. Should we extend ServiceControl to allow loading message bodies of multiple messages?

**Comment by HEskandari** [comment]
After reviewing SI again, I'm more convinced that we should move that "Show message data" button into each message and show the message payload individually. The benefits are:

- We could reuse the 'Detail view' rather than expanding the node in the diagram which makes the overall design more consistent.
- No need to issue N number of requests to ServiceControl which doesn't scale well.
- Would align better to the use-case being 'inspection of anomalies' rather than just give me everything mind-set.

Thoughts? /cc @Particular/serviceinsight-maintainers -maintainers & @sergioc

**Comment by adamralph** [comment]
@HEskandari I still have to test the UX here a little more myself, but on the face of it, this sounds good.

**Comment by HEskandari** [comment]
@adamralph let me know once you've had a chance to review the UX here. I can then close this discussion issue and open improvement focused issues.

**Comment by adamralph** [comment]
@HEskandari perhaps it's best if we jump on zoom when you're next on line and you talk me through it?

**Comment by adamralph** [comment]
@HEskandari and @adamralph discussed and decided that we should replace the showing of data for all messages with one message at a time. Raised #679.
