### ISSUE TITLE
Saga view shows timeout hyperlink when message has not been processed

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#651]
A user in a google issue asked about the display of timeouts in a saga view. Specifically when a timeout does not occur there is still a hyperlink that leads nowhere, which was confusing the user.

We should probably change the hyperlink to standard text if the timeout did not fire, and optionally also add a tooltip saying that.

cc @sergioc

**Comment by sergioc** [comment]
1. I think the link alone is not clear enough in any case, so it would be good to have the tooltip indicating what's the link for at all times. Even after clicking it may not be entirely obvious.
2. regarding timeouts that didn't yet fire, I'm unsure about using standard text. Because it's not a link it's unlikely the user will hover it and see the tooltip. Another option is to keep the link and trigger a message indicating the timeout didn't fire yet. Thoughts?

**Comment by adamralph** [comment]
> 1. I think the link alone is not clear enough in any case, so it would be good to have the tooltip indicating what's the link for at all times. Even after clicking it may not be entirely obvious.

Agreed. Specially when the message handling is already scrolled into view. E.g. in the following example, clicking the link has no visible effect:

![image](https://cloud.githubusercontent.com/assets/677704/20702354/c057eb8c-b617-11e6-825e-e6c58bb477ea.png)

I'm wondering if, after clicking, the incoming message should be highlighted somehow. It could even be a background highlight which fades out, [similar to when clicking a StackOverflow question](http://stackoverflow.com/questions/37487862/use-a-variable-in-an-attribute-constructor/37500415#37500415).

---

> 2. regarding timeouts that didn't yet fire, I'm unsure about using standard text. Because it's not a link it's unlikely the user will hover it and see the tooltip. Another option is to keep the link and trigger a message indicating the timeout didn't fire yet. Thoughts?

Just to throw a crazy idea out there, how about if we move the link to the requested message and make the meaning explicit? E.g.

![image](https://cloud.githubusercontent.com/assets/677704/20702569/a5a2ac04-b618-11e6-978a-bf203e28a702.png)

When the message is not processed, the text can be "(Not processed)" and not linked.

**Comment by adamralph** [comment]
As a bonus, we could even highlight both the requested timeout and the handled timeout boxes when the user hovers over either, to give a visual connection between the two.

**Comment by adamralph** [comment]
I've raised a WIP PR which does the simples thing possible, i.e. no link, just text, when the message hasn't been processed: #653

**Comment by adamralph** [comment]
The scope of this issue has been reduced to fixing only the fact that the timeout hyperlink is shown when the message has not been processed.

Other proposals here will be moved to separate issues.
