### ISSUE TITLE
View retries for a given message

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceInsight#655]
*From https://groups.google.com/forum/#!topic/particularsoftware/UTnz_o6ApMY*

> Is it possible to get an overview of the retry attempts and details of failed messages or messages currently in 'retry mode'?
> 
> I am imaging a view that looks something like this:
> 
> [Message Id]    [Message Type]  [Time Sent] [Status]
{3F2504E0-4F89-41D3-9A0C-0305E82C3301}  CreateCustomerRequest   18-12-2014 11:18:00.0899    Retrying
> 
> When expanding the message, the details of the individual attempts becomes visible:
> 
> [Attempt #] [Type]  [Time Sent] [Exception]
> 1   FirstLevel  18-12-2014 11:18:01.0899    Unable to connect to foo
> 2   FirstLevel  18-12-2014 11:18:00.0899    Unable to connect to foo
> 3   FirstLevel  18-12-2014 11:18:02.0899    Unable to connect to foo
> 4   FirstLevel  18-12-2014 11:18:03.0899    Unable to connect to foo
> 5   FirstLevel  18-12-2014 11:18:05.0899    Unable to connect to foo
> 6   SecondLevel 18-12-2014 11:28:05.0899    Login failed for user 'myuser'
> 7   SecondLevel 18-12-2014 11:38:05.0899    Login failed for user 'myuser'
> 8   SecondLevel 18-12-2014 11:48:05.0899    Login failed for user 'myuser'

**Comment by adamralph** [comment]
Currently we cannot do this, since the required information is not exposed by ServiceControl. It will need a change in ServiceControl to expose this information, and possibly a change in NServiceBus. We're considering this from a platform wide POV and will provide updates when we have them.

**Comment by mauroservienti** [comment]
We (DevExp) ad a look at this issue:

- All the information are available in the endpoint logs
- It's very hard to ship those information to ServiceControl as:
   - there is no easy way to keep track at the endpoint level of what is going on across multiple retries
   - we cannot really ship logs to ServiceControl at each retry attempt as we have no easy way to clean them up if a subsequent attempt succeed

Probably the best way to address such a requirement is to create a [custom recoverability policy](https://docs.particular.net/nservicebus/recoverability/custom-recoverability-policy) and do whaever is needed there.

For the above reasons I'll close this issue as `withdrawn`. Feel free to reopen if needed.
