### ISSUE TITLE
Can we upgrade to .NET Framework 4.6?

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#656]
Other than just using the latest framework there is another reason for the upgrade.

There are some bindings that only blow up on .NET Framework 4.5.2+. The cases are where we are doing two-way binding on a property with just getter. 

What's the implication on this upgrade? Should the .NET Framework version be aligned with prerequisite of ServiceControl / ServicePulse?

**Comment by adamralph** [comment]
> What's the implication on this upgrade?

.NET Framework 4.5.2 is still supported by MS, and some enterprises may still be stuck on it.

> Should the .NET Framework version be aligned with prerequisite of ServiceControl / ServicePulse?

I don't see any reason to. 4.6 installs over the top of 4.5.x so those running it will already be running all the apps under 4.6. I believe each product can choose to move it's compilation to run against 4.6 independently to take advantage of the new features and/or bug fixes.

**Comment by HEskandari** [comment]
@adamralph Forgot to clarify. ATM we're on .NET 4.5 and not 4.5.2.

**Comment by adamralph** [comment]
@HEskandari thanks.

If we want to upgrade from .NET 4.5 to .NET 4.5.2 to use new features and/or avoid bugs, I think we should just go ahead and do it. .NET 4.5 and .NET 4.5.1 are no longer supported by MS so there's little justification in holding back to support customers who are still using them.

The fact that we're currently on 4.5 doesn't change anything WRT upgrading to 4.6. The above concerns/observations still apply.

**Comment by HEskandari** [comment]
We believe some organisations may still be reluctant to upgrade to 4.6 so we have upgrade to 4.5.2 as it is still supported.
