### ISSUE TITLE
InvalidOperationException Sequence contains no matching element in 1.5.10

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#664]
This was reported via Raygun

ServiceInsight 1.5.10
ServiceControl 1.11.0

    System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate):77
     ServiceInsight.ServiceControl.DefaultServiceControl+<>c__31`1.<GetPagedResult>b__31_0(IRestResponse`1 response) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:245
     ServiceInsight.ServiceControl.DefaultServiceControl.ProcessResponse[T,T2](Func`2 selector, IRestResponse`1 response) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:459
     ServiceInsight.ServiceControl.DefaultServiceControl.Execute[T,T2](RestRequestWithCache request, Func`2 selector) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:398
     ServiceInsight.ServiceControl.DefaultServiceControl.Search(String searchQuery, Int32 pageIndex, String orderBy, Boolean ascending) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\ServiceControl\DefaultServiceControl.cs:99
     ServiceInsight.MessageList.MessageListViewModel.RefreshMessages(Endpoint endpoint, Int32 pageIndex, String searchQuery, String orderBy, Boolean ascending) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\MessageList\MessageListViewModel.cs:148
     ServiceInsight.MessageList.MessageListViewModel.RefreshMessages(String orderBy, Boolean ascending) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\MessageList\MessageListViewModel.cs:109
     ServiceInsight.MessageList.MessageListViewModel.OnSelectedExplorerItemChanged() in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\MessageList\MessageListViewModel.cs:235
     ServiceInsight.MessageList.MessageListViewModel.set_SelectedExplorerItem(ExplorerItem value) in C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\MessageList\MessageListViewModel.cs:79

**Comment by HEskandari** [comment]
@distantcam Would you be able to add a bit of description to the issue? Other than the stacktrace it is not clear in which scenario this would happen.

**Comment by distantcam** [comment]
@HEskandari Not really. I don't know what's causing this, and I cannot reproduce it.

**Comment by HEskandari** [comment]
This does not seem to have happened anymore. The only way this was reproduced was when the .exe.config file containing binding redirects were missing, which should not have happened in the first place. Closing.
