### ISSUE TITLE
Improvements to property display styles in Saga View

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#666]
There are a few issues with the way property key / values are displayed in SagaView so the following improvements should be made:

![image](https://cloud.githubusercontent.com/assets/132117/20917622/a5011046-bbe6-11e6-90b1-5bef0e685afd.png)

![image](https://cloud.githubusercontent.com/assets/132117/20924232/9610f196-bc04-11e6-9bdb-2c128f5b00ed.png)

- Contrast for property names and values is to be increased while keeping special characters de-emphasized. 
- Show the active tab in underlined black text to indicate it's active and can't be clicked again.
- Mouse cursor should change to Hand when hovering over the links.
- In order to not have View properties: displaying as if it was another property and better align the display of custom tabs with SP, change tabs labels, reduce font size by 2pt and make it all caps.

**Comment by HEskandari** [comment]
This was done as a part of #648 but we're moving the relevant parts here and only keep the bug / issue in 648.

**Comment by HEskandari** [comment]
@sergioc The screenshot above only shows black color for the selected underlined text. What color should be the 'underline' part when you hover over the *not-selected* text? In other words, should it behave link other links e.g. link to (xxx bytes)?

**Comment by adamralph** [comment]
@HEskandari I guess the hover style for a link should continue to be a blue underline. A black underline would look very strange.

**Comment by sergioc** [comment]
What color should be the 'underline' part when you hover over the not-selected text?

Same blue as the link.
