### ISSUE TITLE
Improve saga properties display of tabs

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#669]
In order to not have `View properties:` displaying as if it was another property and better align the display of custom tabs with SP, change tabs labels, reduce font size by 2pt and make it all caps:

![screenshot 2016-12-06 12 09 52](https://cloud.githubusercontent.com/assets/493451/20923479/e9cdc5f0-bbac-11e6-9ede-619e58fad418.png)

**Comment by adamralph** [comment]
@sergioc it seems like this should be part of #666, since that issue also changes these labels.

**Comment by adamralph** [comment]
btw 👍 to this change!

**Comment by HEskandari** [comment]
I'll close this and merge with #666.
