### ISSUE TITLE
Show tooltips for truncated property names in saga view

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#677]
Currently it's not possible to read the full text from properties with truncated names in the saga view:

![2016-12-12 at 09 16](https://cloud.githubusercontent.com/assets/493451/21092337/14d0f53a-c04c-11e6-8950-e5967c927400.png)

Adding tooltips to reveal the full name is a quick solution to have until we make a larger revision to property diff display.

**Comment by HEskandari** [comment]
@Particular/serviceinsight-maintainers I have submitted a PR for this, although this might be a Feature and not a bug. Please review and update.
