### ISSUE TITLE
Add feature to see multiple endpoints to choose from in the Endpoint Explorer

### ISSUE THREAD

**Issue by manuelsalvatori** [Particular/ServiceInsight#688]
I really would like to be able to control from a centralised ServiceInsight multiple endpoints being also able to switch between the easily and to label them with some alias instead of urls.

**Current behaviour**
Open ServiceInsight and add a new endpoint clicking on Tools>Connect To ServiceControl.
Type the URL of the endpoint and confirm.
The UI shows on the left the URL just selected and expanding it all the endpoints that are sending/receiving from the configured queues, it removes any other service previously added.

**Desired behaviour**
Open ServiceInsight and add a new endpoint clicking on Tools>Connect To ServiceControl.
Type the URL of the endpoint and an Alias to identify the service and confirm.
The UI shows on the left the existing services, below those the Alias just provided and expanding it all the endpoints that are sending/receiving from the configured queues.
Clicking on one service name on the left (Endpoint Explorer), on the right the data is updated accordingly.

I really would like to have this.
The reason for that is currently I'm observing many services for all our environments from one machine.

**Comment by HEskandari** [comment]
Thanks for opening the issue. We do have an issue open for this and I believe this is a duplicate. Please see #574.

As for what you are doing, isn't monitoring of endpoints on various environments what you should be doing using ServicePulse?

**Comment by manuelsalvatori** [comment]
@HEskandari thanks for the reply, I think my issue is related but not the same, and it's likely I misunderstood the way I should use the tools.

What I would like to do, is to be able to monitor every queue I use whit the minimum amount of services installed and maintained (ServiceControl, Pulse and Insight).

So far I understood that I need at least a service control service running for each machine where we have queues I want to monitor.

So, for now, I have 3 machines with three service control running, and each ServiceControl watches 2 sets of queues (audit / error) exposing apis on server:33331/api/ and serverx:33332/api/.

On top of that in each machine there is a ServicePulse serving the page for monitoring, this is also another limit I'm trying to solve, because the configuration for what i see and what I read in https://docs.particular.net/servicepulse/host-config, doesn't support multiple servicecontrol urls:
`        .constant('scConfig', {
            service_control_url: 'http://devgsaprow01I.dev.group.zone:33332/api/'
        });`

Regarding this very issue, I use from my machine ServiceInsight to connect to those multiple ServiceControl, but, each time I have to manually connect to the endpoint I want to view, it doesn't remain in the "Endpoint Explorer" panel, in which I always and only see one endpoint.

I hope I clearly described how I use the tools, hopefully I'm doing something wrong that I can change.

Thanks

**Comment by HEskandari** [comment]
@manuelsalvatori I don't think you should be setting this up they way you have (unless there's environment separation concerns that you haven't mentioned).

The way this is usually configured is that for all your endpoint across your system in an environment (e.g. x number of endpoints in Production or Staging) you need just one instance of ServiceControl. The trick is, all your endpoints should have a common error and audit queue where SC feeds off of. 

With this, you can manage all your endpoints with one instance of SC per environment. Now for monitoring of endpoints, you can use ServicePulse but to see message data and visualize your distributed system, ServiceInsight would be a better pick.

If this is confusing or you're still not sure how to do this, I recommend you open a support ticket with us and one of our engineers will help you through it.

**Comment by manuelsalvatori** [comment]
@HEskandari I understand your recommendation very well, and I think I'm going to plan the change.
This means I will end up having one servicecontrol / servicepuls for each environment.
It would still be useful from my side to be able to keep all the endpoint connected using ServiceInsighet so that I will be able to monitor all the development environments (in my case 3).
I will close this issue, is not so important was just a recommendation that would have helped me to manage all endpoints together.

Thanks for the information provided.

**Comment by HEskandari** [comment]
@manuelsalvatori The issue #574 was the ability to connect to multiple SC instances (e.g. one from Production and one from Staging) which I initially thought is what you want. 

You will still be able to see and monitor all the endpoints in your system using ServiceInsight. Both SI and SP can use the single source (SC) as their data and will provide a seamless experience.
