### ISSUE TITLE
Recording more info from the SC logs in a crash report.

### ISSUE THREAD

**Issue by distantcam** [Particular/ServiceInsight#695]
We currently record the SC version in our crash reports, which is very useful. But sometimes that isn't enough. The SC logs would be useful in that case.

**Comment by HEskandari** [comment]
I'm all for including extra information in (supposedly?) Raygun reports, but I see the following questions:

- How do we know how much of the SC log is enough/relevant to include?
- How do we access SC logs to begin with?

**Comment by HEskandari** [comment]
@Particular/serviceinsight-maintainers I don't think given the current state of SC/SI this is possible to do. 

Should we still discuss this in our next sync?

**Comment by adamralph** [comment]
Outcome of the discussion is that we will not be implementing this.
