### ISSUE TITLE
Installation may not complete due to Advanced Installer self extractor not exiting

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceInsight#699]
A bug in the version of Advanced Installer used to package ServiceControl, ServiceInsight and ServicePulse can leave the self extractor running after the MSI installation is complete.

This only happens if a log file is specified on the command line, which is always the case when the installation is run through the Platform Installer. See Particular/PlatformInstaller#202

To rectify this we need to do a release packaged with a later Advanced Installer version

**Comment by gbiellem** [comment]
Advanced Installer 13.5 has been installed on the build agents. 
@Particular/serviceinsight-maintainers  can you do release to address this

**Comment by distantcam** [comment]
@gbiellem Do we need to update our setup file?

**Comment by gbiellem** [comment]
@distantcam AFAIK it shouldn't require any changes in the setup. I've tested and about to release ServiceControl using the new version of Adv Installer and it worked without a change

**Comment by distantcam** [comment]
@gbiellem Awesome.

**Comment by gbiellem** [comment]
@Particular/serviceinsight-maintainers   This is not fixed.

The master branch wasn't rebuilt after this issue was raised so what was deployed for 1.6.3 was built using the old Advanced Installer as you can see from the build logs  [here]( https://builds.particular.net/viewLog.html?tab=buildLog&buildTypeId=ServiceInsight_Build&buildId=210155#_state=643,649,650,651,653,657,658,2150,2168,2169,2165,2236,2252&focus=2253)
