### ISSUE TITLE
Message window selection gets out of sync with the saga view diagram

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#701]
There could be different scenarios where Messages window contains no data, or different selected row but Saga View still shows a diagram or shows a different message's diagram.

- Perform a search in Messages window that yield no result, e.g. search by a non-existing keyword. The Messages window shows no messages as expected, but the Saga view shows the first (hidden) message's saga diagram.

- Select a message in Messages window and notice the Saga view opens the correct diagram. Perform a search in Messages window that yields no result. Change the Order of the Message view, e.g. sort by MessageType column. Clear the search so the view refreshes with data but observe the wrong diagram being displayed in the Saga view.

It looks like in certain scenarios `Current Selection` does not flow through Saga view.

**Comment by sergioc** [comment]
Closed in favor of #364
