### ISSUE TITLE
Consistent horizontal scrollbar in content viewer dialog

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#712]
When scrolling, scrollbar sizes should remain the same regardless of the content that is within the view.

This is a split of #644

**Comment by HEskandari** [comment]
@adamralph do you remember this one? Do you think we need to address it, or keep it as is?

**Comment by sergioc** [comment]
I remember a discussion about having a scroll bar handle that would auto resize depending on the horizontal length of the content visible at the moment. I’m quite sure it was concluded that would violate ui conventions and we decided to abandon the idea.

**Comment by adamralph** [comment]
What is the current behaviour? Reading back through #644 it sounds like we currently wrap the content, and therefore no horizontal scroll bar is ever shown. Is that correct?

**Comment by HEskandari** [comment]
Currently, depends on the content in the viewport. Once you scroll the content that exceeds the available width, the horizontal scrollbar does appear. The size of the scrollbar changes (also disappears) as you scroll content with different width.

The point of the issue was to make it more consistent with other text editors (e.g. notepad) but if we're happy with the behavior we can close.

**Comment by adamralph** [comment]
So at the moment, we don't wrap the content at all?

**Comment by adamralph** [comment]
OK, I can see that we don't: https://github.com/Particular/ServiceInsight/commit/1277d34dbb787042140244d306e221787afda88a#diff-356c2387ad5e72d28fd00e6566cf60db

**Comment by adamralph** [comment]
> Currently, depends on the content in the viewport. Once you scroll the content that exceeds the available width, the horizontal scrollbar does appear. The size of the scrollbar changes (also disappears) as you scroll content with different width.

In that case, the current behaviour is exactly what @sergioc is describing here:

> I remember a discussion about having a scroll bar handle that would auto resize depending on the horizontal length of the content visible at the moment. I’m quite sure it was concluded that would violate ui conventions and we decided to abandon the idea.

I.e. according to this comment, we are currently violating UI conventions. As I understand it, this issue is to fix that violation, and use a fixed size horizontal scrollbar instead.

**Comment by HEskandari** [comment]
Yes, @adamralph is right. The current behavior is somewhat different to conventional editors. This issue was to address it but upon demoing it, we said it is better to keep it as is. 

Here's the current behavior: 
![scrollbar](https://user-images.githubusercontent.com/132117/31321980-f9e6da0c-acd9-11e7-8156-251cb6a9c975.gif)

**Comment by HEskandari** [comment]
@Particular/serviceinsight-maintainers Are you happy with the implementation above? ☝️ If yes, this can be closed.

**Comment by sergioc** [comment]
I don't agree with closing this issue. The current behavior violates a UI convention.

**Comment by sergioc** [comment]
BTW, another option is to enable line-wrapping, but if we do that it would be good to also display line numbers in order to make it clear where is line wrapping occurring.

**Comment by adamralph** [comment]
I agree that this issue has not yet been solved.

**Comment by sergioc** [comment]
Groomed as part of enhancement release issue triage. It's not really a big problem and there's other apps doing this.
