### ISSUE TITLE
Saga payload view should be resizable

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#714]
Saga Payload view and Exception view should be resizable so that the user can resize them to fit their screen size and content.

**Comment by HEskandari** [comment]
@sergioc I had a look at this. I don't think we need to make 'all' child windows resizable. Technically speaking, About dialog, Splash screen (startup), Options dialog and Licensing dialog is also considered a child window, do we need them all to be resizable or should we pick and choose (in this case limit it to the Detail View).

**Comment by sergioc** [comment]
@HEskandari agreed. Can you list all child windows we have to see exactly what should be resizable?

**Comment by sergioc** [comment]
Chatted with @HEskandari and agreed we should only make "Detail View" and "Exception view" windows resizable since those are the only that are prone to content overflow.

**Comment by HEskandari** [comment]
Exception view is already resizable. The payload view isn't, so let's keep it open.

**Comment by seanfarmar** [comment]
I'll take this

**Comment by seanfarmar** [comment]
PR https://github.com/Particular/ServiceInsight/pull/876

**Comment by seanfarmar** [comment]
https://caliburnmicro.com/announcements/

Looks like the lib we are using is going off maintenance

**Comment by udidahan** [comment]
Has an issue been raised for the Caliburn Micro thing?

**Comment by HEskandari** [comment]
@udidahan we'll be creating an issue for dependency updates (which will include Caliburn Micro) before wrapping up.
