### ISSUE TITLE
Configuration option to skip certificate validation for connection to ServiceControl

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#717]
This is a spin-off of the discussion in https://github.com/Particular/ServiceInsight/issues/604.

This allows, for example, connections to ServiceControl running with a self-signed certificate.

We will allow this via an app config setting, which address the problem whether ServiceInsight is launched by the user directly, or via ServicePulse.

## Plan of attack

- [ ] Make changes - #756
- [ ] Update docs - https://github.com/Particular/docs.particular.net/pull/3273

**Comment by HEskandari** [comment]
@Particular/servicecontrol-maintainers Had a spike on this, there is a problem with the proposed way of doing it.

The way the by-pass works is that once you set it, it will be there for the session and there's no way to roll it back. Also, the workaround is controlled via a static variable (`ServicePointManager.ServerCertificateValidationCallback` property) which means it is not per SC instance. 

How do you propose we introduce the UI bit for it so that:

- It clearly communicates that it is for all SC connection, not tied to a particular instance
- It is per session at least (once the flag is set, you'll need to restart the app to set it back to default behavior)

I propose doing that via an option in the Settings screen.

- It is a global flag, so not per SC instance.
- All settings changes require restarts.
- We'll need to persist this flag anyhow, so not an extra effort.
- It works fine with issue #718 as well.

**Comment by mikeminutillo** [comment]
How common is this? Would it be problematic to simply make it an app.config setting with no UI?

**Comment by gbiellem** [comment]
@mikeminutello i raised the original issue (#604), IMHO its very uncommon, i was not sure if it was worth supporting

**Comment by HEskandari** [comment]
@mikeminutillo App.config _could_ be an option, but we're not storing anything else in there (with the exception of binding redirects).

**Comment by adamralph** [comment]
@Particular/serviceinsight-maintainers discussed this today and we decided to add it as an app config setting (description updated). This is a low cost, low impact way for us to support this use case.

**Comment by adamralph** [comment]
FYI I changed the title and description, and unchecked "Make changes" from the POA, since that's only done when #756 is merged.
