### ISSUE TITLE
Allowing SI activation to connect to ServiceControl running with a self-signed certificate

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#718]
This is a spin-off of the discussion in #604.

To address SI application invocation via links generated in ServicePulse, we agreed to do the following:

- Change the command line parsing of the query string passed during application invocation to specify the protocol (HTTPS/HTTP) and a flag to skip the certificate check. 

- This would be done in a backwards-compatible way, and ServicePulse would have to be changed subsequently to pass the new query string params.

**Comment by adamralph** [comment]
#717 now covers this use case.
