### ISSUE TITLE
When SC isn't running it takes a long time to switch between items in the list and not get any error information

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#720]
# Problem
When SC isn't running it takes a long time to switch between items in the list and not get any error information.

![2017-04-06_14-27-58](https://cloud.githubusercontent.com/assets/152998/24754905/8b2c9446-1ad8-11e7-8610-782ec57d0535.gif)

# Expected

If SI cannot communicate with SC I would expect to see an error.

**Comment by HEskandari** [comment]
I think should be labeled as a Bug. This happens when SC is down but the requests for those Message Ids are already cached so that's where it is loaded from, but in the case of SC being down, should we load the data from a cache at all? How can we ensure if it is not stale if SC can not be reached?

**Comment by HEskandari** [comment]
The "Messages" window now shows a "Loading..." indicator when data is being loaded. If ServiceControl is down, the connectivity issues are highlighted on the status bar.

![Screen Shot 2020-08-31 at 11 25 56 am](https://user-images.githubusercontent.com/132117/91674656-ed6c6f00-eb7c-11ea-96a7-846ae00ab14d.png)
