### ISSUE TITLE
Add processing time, critical time, and delivery time columns

### ISSUE THREAD

**Issue by swettstein** [Particular/ServiceInsight#723]
I would like the ability to select columns based on the standard NSB headers and to sort by those columns. For example, I would like to sort by ProcessingEnded so I can see retried messages as they are processed and not by when they were originally sent.

**Comment by HEskandari** [comment]
@swettstein Thanks for opening the issue. Because of things like data paging the sorting on client-side is not possible so with the current architecture the sorting is done by the ServiceControl.

Are there specific headers you want to sort by (other than ProcessingEnded you mentioned?).

**Comment by swettstein** [comment]
@HEskandari Are you saying that this would require an update to ServiceControl to return sorted paged data? I guess that makes sense. I would like to see all standard NSB headers as options to view and sort in the Message List View. Custom headers would be amazing too but that's probably much more difficult; let's start with NSB headers and work from there.

**Comment by swettstein** [comment]
looks like this is related to #708

**Comment by HEskandari** [comment]
@swettstein It is in fact connected to that issue. 

You understood correctly, this would require an update to ServiceControl, so at least it requires a coordinated effort to release. I'm checking with our ServiceControl maintainer group to see if adding another sorting option has performance implications.

**Comment by sergioc** [comment]
There's 2 ideas for highlighting clock drifts:

## Option 1

Highlight cells with negative values and show tooltip to explain highlight. 

![pasted image at 2017_06_15 11_26 pm](https://user-images.githubusercontent.com/493451/27582112-1bedd584-5b30-11e7-9007-d6bcb59e1ffd.png)

Problem: hard to see in low contrast displays, hardly any semantic value, not noticeable if cells are not visible

## Option 2

A combination of option 1 and new message status indicators:

<img width="1349" alt="screenshot 2017-06-23 09 27 32" src="https://user-images.githubusercontent.com/493451/27582180-52f789b2-5b30-11e7-8e57-18a895e11e38.png">

The warning status indicator would also show inside any cells displaying negative values.

**Comment by adamralph** [comment]
Thanks for the designs @sergioc. We discussed this in today's sync and we like option 2.

We are proposing to go with a slight variant though: we will continue to use the current status icons (the left three), and we will take the new warning icon and overlay it ourselves on any of the three status icons (reducing the size of the status icon as shown in the fourth image), since there could be messages in any of the three states which show symptoms of clock drift (or anything else we may choose to warn about in the future). That will save having to redraw all three icons with an warning variant, and will hold for any future status icons which are added.

Does that sound OK?

**Comment by sergioc** [comment]
> we will take the new warning icon and overlay it ourselves on any of the three status icons

That's fine, but I think it's more work for you to create that icon layout with overlay than for me to create new icons.

**Comment by adamralph** [comment]
@sergioc I don't mind either way.

@Particular/serviceinsight-maintainers I think some additional status icons were mentioned in today's sync, or is it indeed only the three shown above (success, failed, failed-repeatedly)?

**Comment by sergioc** [comment]
Updated message status icons:

![screenshot 2017-06-27 15 23 12](https://user-images.githubusercontent.com/493451/27589711-a67e6ec2-5b4c-11e7-95a5-352aa70535d4.png)

All icons SVGs can be found in https://www.dropbox.com/sh/cxbnpq3j7maqkfk/AADU2oxGS68YOakefAkJW-iea?dl=0

**Comment by adamralph** [comment]
Thanks @sergioc. Are we missing `failed-warning`?

**Comment by sergioc** [comment]
We were, thanks. I've added it to the same Dropbox folder.

**Comment by adamralph** [comment]
👍 thanks @sergioc 

@HEskandari it looks like you're good to go with the new icons.

**Comment by adamralph** [comment]
FYI I updated the POA to remove the tasks that are now part of #735.
