### ISSUE TITLE
NRE in EndpointExplorerViewModel.Handle

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceInsight#725]
From Raygun:

- **Version:** 1.7.0+14.Branch.master.Sha.3a8b8bdb65a6220e409691c88f82603bb9289351
- **Class name:** System.NullReferenceException
- **Message:** Object reference not set to an instance of an object.
- **Stacktrace:**
> ServiceInsight.Explorer.EndpointExplorer.EndpointExplorerViewModel.Handle(RequestSelectingEndpoint message) in
> C:\BuildAgent\work\7540559e45164f93\src\ServiceInsight\Explorer\EndpointExplorer\EndpointExplorerViewModel.cs:201

**Comment by SimonCropp** [comment]
i imagine this should be a single. https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/Explorer/EndpointExplorer/EndpointExplorerViewModel.cs#L47

since it is assumed to not be null

**Comment by HEskandari** [comment]
It could be `SingleOrDefault` as it stands today (you initially might be disconnected). However the stack trace doesn't tell me how we got there. 

A quick 'fix' would be:

`if (ServiceControlRoot?.EndpointExists(message.Endpoint) == true)` in [here](https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/Explorer/EndpointExplorer/EndpointExplorerViewModel.cs#L207).
