### ISSUE TITLE
Spike black box tests

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#726]
Related to issue https://github.com/Particular/PlatformDevelopment/issues/925. This is a spin-off of a comment [here](https://github.com/Particular/PlatformDevelopment/issues/925#issuecomment-266701112). 

Since ServiceInsight has very limited ~unit~ test coverage. The Maintainer Group feel that in cases of major changes/feature they need to have better coverage to ensure nothing is broken. This issue is to run a spike on that.

**Comment by HEskandari** [comment]
Just as a comment that we do have two approaches, already in the code base:

- Our approach to testing the UI in isolation in the [Approval Tests](https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight.Tests/XamlIconsTests.cs). This solves the challenge of creating a self-relying UserControl and showing it for test purposes. The downside is that this is monitor/resolution/OS dependant and the tests might pass in one environment and not the other.

- My earlier attempt on BBD style testing by running the whole and UI automation. This approach also has its own quirks. These tests were removed from the repo as of commit 4c2634f since they were not running on TeamCity.

**Comment by sergioc** [comment]
Discussed during enhancement release triage, closing for as we don't see this being needed any time soon.
