### ISSUE TITLE
Message Properties not showing timestamps in 24 hour format

### ISSUE THREAD

**Issue by cremor** [Particular/ServiceInsight#731]
I'm running ServiceInsight on a machine that is configured to use the "German (Austria)" region (de-at). So my date format should be "dd.mm.yyyy" and my time format should be "hh:mm:ss" in 24 hour format.

It seems like ServiceInsight respects those settings most of the time, but there is one exception: The timestamps in the message properties, e.g. the Performance.TimeSent property, are shown in 12 hour format, but without an AM or PM indication.

Example:
Shown value: 20.06.2017 07:37:54.5457
Expected value: 20.06.2017 **19**:37:54.5457

**Comment by HEskandari** [comment]
Thank you for reporting it. I will look into it and get back to you.

**Comment by HEskandari** [comment]
@cremor Just tried to reproduce this using the latest release (which went out yesterday). I have switched to German / Austria region and it seems the date _and_ time values are being displayed as expected. Here's the screenshot:

![image](https://user-images.githubusercontent.com/132117/29599085-c25f65d8-8810-11e7-8572-b0f1ad9cd01d.png)

Could you please verify if this still happens on the latest [release of 1.7.2](https://github.com/Particular/ServiceInsight/releases/tag/1.7.2)?

**Comment by cremor** [comment]
I was using 1.7.1 originally. I've now also tried 1.7.2 and can still reproduce the error.

The screenshot you posted shows the main message table. The bug doesn't happen there. As I've written in my initial post, only the message properties pane is affected.

This are screens from the same message:
![grafik](https://user-images.githubusercontent.com/116314/29659612-26853c0a-88bf-11e7-9b7b-e811f467b698.png)
![grafik](https://user-images.githubusercontent.com/116314/29659660-4259a0e2-88bf-11e7-974c-6c6cdbc8ff02.png)

**Comment by HEskandari** [comment]
@cremor ah got it, thanks for posting the screenshot.

**Comment by HEskandari** [comment]
@cremor I have verified the issue. Here's how it looks with the fix.

![image](https://user-images.githubusercontent.com/132117/29754778-a4949146-8bcf-11e7-866e-4b9b2f58db02.png)

**Comment by adamralph** [comment]
@cremor thanks again for raising this. We'll release this fix shortly, as part of version 1.8.0.
