### ISSUE TITLE
Runtime error: Can't find property 'DxFts_10'

### ISSUE THREAD

**Issue by adamralph** [Particular/ServiceInsight#733]
_From https://app.raygun.com/crashreporting/7gulz9/errors/1952419689/_

- **Version:** 1.7.0+14.Branch.master.Sha.3a8b8bdb65a6220e409691c88f82603bb9289351
- **Class name:** DevExpress.Data.Filtering.Exceptions.InvalidPropertyPathException
- **Message:** Can't find property 'DxFts_10'

<details>
<summary>Stacktrace</summary>
> DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Visit(OperandProperty theOperand):86
> DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Validate(IList operands):28
> DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Visit(FunctionOperator theOperator):12
> DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Validate(IList operands):28
> DevExpress.Data.Filtering.Helpers.EvaluatorCriteriaValidator.Visit(GroupOperator theOperator):12
> DevExpress.Data.Filtering.Helpers.ExpressionEvaluator..ctor(PropertyDescriptorCollection properties, CriteriaOperator criteria, Boolean caseSensitive, Boolean doCreateEvauluatorCore):33
> DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.get_ExpressionEvaluator():23
> DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.IsVisible(RowHandle handle):0
> DevExpress.Xpf.PropertyGrid.Internal.DataViewBase+<GetFilteredChildrenInternal>d__1d.MoveNext():99
> System.Linq.Enumerable.Any[TSource](IEnumerable`1 source):21
> DevExpress.Xpf.PropertyGrid.Internal.DataViewBase.CanExpand(RowHandle handle):53
> DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.PrepareRowDataForHandleOverride(RowDataBase data, RowHandle handle, RowDataProperties properties):78
> DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.InitializeViewItemsSource(PropertyGridView view):34
> DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.DoActionAndSaveFocus(Action action):123
> DevExpress.Xpf.PropertyGrid.Internal.RowDataGenerator.Invalidate(String fieldName):121
> DevExpress.Xpf.PropertyGrid.PropertyGridView.<Invalidate>b__7b(FieldNameAction theAction):89
> DevExpress.Xpf.PropertyGrid.Internal.AggregateAction.DevExpress.Xpf.Editors.IAction.Execute():20
> DevExpress.Xpf.Editors.ImmediateActionsManager.<ExecuteActions>b__0():30
> DevExpress.Xpf.Core.Locker.DoLockedAction(Action action):7
> DevExpress.Xpf.Editors.ImmediateActionsManager.ExecuteActions():50
> System.Windows.ContextLayoutManager.fireLayoutUpdateEvent():88
> System.Windows.ContextLayoutManager.UpdateLayout():836
> System.Windows.ContextLayoutManager.UpdateLayoutCallback(Object arg):16
> System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks():69
> System.Windows.Media.MediaContext.RenderMessageHandlerCore(Object resizedCompositionTarget):98
> System.Windows.Media.MediaContext.AnimatedRenderMessageHandler(Object resizedCompositionTarget):53
> System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs):119
> System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler):2
</details>

**Comment by WilliamBZA** [comment]
The stacktrace doesn't give any indication of where our code is triggering this. Perhaps we can reach out to DevExpress to see if they know about this or can give us hints on where to look?

Another option is to update to the latest verstion of DevExpress and hope? Tricky because we don't have a reproducible set of steps to verify.

Alternatively, if we are unable to reproduce we should probably withdraw as such.

**Comment by WilliamBZA** [comment]
Best I can find on this is that it's related to crossplat somehow, but that seems strange to me as the OS was a windows OS (server 2012).

Looks like we'll have to reach out to devexpress here.

**Comment by HEskandari** [comment]
@WilliamBZA Any updates on that? Did they provide any update/guidance on the error and how it is fixed?

**Comment by WilliamBZA** [comment]
Waiting for a response from them.

**Comment by WilliamBZA** [comment]
Confirmed that the proposed solution appears to resolve the issue. PR submitting

**Comment by adamralph** [comment]
Fixed in 1.7.2, released today: https://twitter.com/ParticularNews/status/899943683973361664
