### ISSUE TITLE
Connecting to ServiceControl does not trigger a refresh of the message list when the endpoint explorer does not have focus

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceInsight#736]
<details>
<summary>Original description</summary>
If I don't select anything in the `Endpoint Explorer` changing the sort order and/or column does not trigger query to SC to fetch the data. The sorting is done on the local data set. Only when I first click something in the `Endpoint Explorer` the sorting starts to work properly.

I suspect this is because of this code https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/MessageList/MessageListViewModel.cs#L102
</details>

**Comment by HEskandari** [comment]
How can you not select anything in the endpoint explorer? You have to have a selection and if it is either the root node, which means all the endpoints or a specific one.

Could you please elaborate how you ended up with no selection on Endpoint Explorer?

**Comment by SzymonPobiega** [comment]
@HEskandari When you start SI and don't even expand the Endpoint Explorer. The current code is based on the event that is triggered when you click something in EE.

**Comment by HEskandari** [comment]
@SzymonPobiega Just tried this but still can't repro:

- Launch SI, it connects automatically to previous SC instance and loads the data.
- Not selecting anything from Endpoint Explorer (and it looks as if there's no node selected)
- Click on one of the column headers, e.g. Message Type and it issues a request to SC and sorts the data.

Now could it be that the request is cached locally and doesn't actually hit SC? You should still see the log entries on Logs window.

**Comment by SzymonPobiega** [comment]
@HEskandari I verified it and indeed it does work when you can connect to SC. But when you can't (e.g. temporarily disabled `EndpointExplorerViewModel::SelectDefaultEndpoint` does not publish the event and then the selected endpoint is null and refresh queries are not sent to SC.

**Comment by SzymonPobiega** [comment]
@HEskandari @adamralph here's the link to the repro recording: https://drive.google.com/open?id=0B_QSSoVzhDxPbzU2b2JITGM5bHM

**Comment by HEskandari** [comment]
@SzymonPobiega Interesting. I see two issues:

- Messages not loading when you connect to SI
- Sorting issue you mentioned.

Both might be caused by the same thing. It looks like when you actually connect, the Endpoint Explorer doesn't have a selection as everything is tied to what is selected in the endpoint explorer.

**Comment by adamralph** [comment]
@SzymonPobiega @HEskandari I've updated the title based on today's discussion. Does it look OK? If not, feel free to edit.
