### ISSUE TITLE
Better icon for successful retries

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#739]
_Related to https://github.com/Particular/ServiceInsight/issues/735_

The current warning icon is limited and it can not signal issues like clock drifts. An update set of icon is required as we need to show warnings when a message has been successfully processed (e.g. for when there is clock drift issues), failed or archived.

**Comment by HEskandari** [comment]
@sergioc This issue came out of the maintainer's sync today. Do you have the capacity to do the mockups as per the PoA above?

**Comment by sergioc** [comment]
@HEskandari sure.

**Comment by adamralph** [comment]
If we were to go for a _new_ icon, could this work?

![image](https://user-images.githubusercontent.com/677704/28305334-2d26e55c-6b93-11e7-84a4-259137207c40.png)

Although I guess we'd perhaps want something much closer to the "success" icon, since success is the primary information it needs to convey. The fact that it was retried is secondary information.

**Comment by sergioc** [comment]
That might work, but I don't think it's appropriate.

> something much closer to the "success" icon, since success is the primary information it needs to convey.

That's exactly what I told @HEskandari in a chat, in addition to keeping things consistent.

**Comment by sergioc** [comment]
Is it important to know the number of retry attempts before it was successful, or it's enough to just somehow distinguish this from a regular success state?

**Comment by adamralph** [comment]
@sergioc I think it's enough to just distinguish from the regular success state.

The idea of a numeric overlay popped into our heads when we were discussing it, but I'm not sure it's the best idea for the icon. It might make it a bit busy and not be readable enough. Also, theoretically, someone could configure their endpoints to have a very high number of retries.

We can display the number of retries elsewhere. I'm not sure if we're doing that already or not, but that would be handled in a separate issue.

**Comment by adamralph** [comment]
Updated the issue description.

**Comment by sergioc** [comment]
Here's an option next to all other icons:

<img width="985" alt="2017-08-18 at 14 39" src="https://user-images.githubusercontent.com/493451/29459264-28f60a5a-8423-11e7-8f85-6f8ef4b083d4.png">

**Comment by adamralph** [comment]
I like it! Is the darker shade of green intentional?

**Comment by sergioc** [comment]
It is. A mix of retry requested and normal success. To give a bit of extra distinction compared to the success icon.

**Comment by sergioc** [comment]
All icons in PNG: https://www.dropbox.com/sh/toznos51e9jj52b/AADfWGjLzIbVJEy6QfWoI7NCa?dl=0

**Comment by adamralph** [comment]
Thanks @sergioc.

@HEskandari I think we should try out these icons on a sample data set in SI which has a good mix of rows with success and success with retry to see how it looks.

**Comment by sergioc** [comment]
Good enough to give the idea?

![2017-08-18 at 15 48](https://user-images.githubusercontent.com/493451/29461674-c9afc14e-842c-11e7-9b91-918fafc35556.png)

**Comment by adamralph** [comment]
Thanks @sergioc.

I'm not entirely sure about the darker shade of green. The fact that a message was retried is a relatively minor detail, so I think I'd prefer to see a uniform "wall of green" for all messages. Otherwise, when I eyeball the entire list, my eye is drawn to those off-colour messages unecessarily.

Another minor point: the curved arrow and the checkmark are very close together. Your screenshot above is rather low res, it looks like it has been shrunk from a much larger size, but the two shapes tend to merge together a bit into something that looks like a single shape. Perhaps they need a little more spacing? Could you provide a full-fidelity screenshot?

**Comment by sergioc** [comment]
> my eye is drawn to those off-colour messages unecessarily.

Why is that unnecessary? I assume a user would want to use this as an opportunity to easily confirm that messages retried successfully. A wall of the same green would make it more difficult to distinguish the icons:

<img width="1244" alt="2017-08-21 at 18 10" src="https://user-images.githubusercontent.com/493451/29528409-3ad0b218-869c-11e7-96a3-ee39e58bd7d5.png">


> the curved arrow and the checkmark are very close together.

This screenshot was taken on a low DPI screen and it could be that my screenshot tool messed up the output. The screenshot above should be give a more accurate idea of output on a low DPI screen.

> Could you provide a full-fidelity screenshot?

Can you provide a similar screenshot from SI in HiDPI for me to use?

**Comment by adamralph** [comment]
@sergioc sure, I've been meaning to provide screenshots of my own, but I'm having trouble with SC at the moment. Will provide something ASAP.

BTW - I discussed this with @HEskandari today and we came up with some more ideas. Will provide more detail ASAP.

Regarding the distinction between success and success with retry, we are both of the opinion that the distinction, as far as the end user is concerned, is subtle, and is usually not important. However, we are also going to reach out to some users to get some opinion on this, and may even RFC this change.

**Comment by sergioc** [comment]
> we are also going to reach out to some users to get some opinion on this

👍 how are you going to reach out to those users?

**Comment by adamralph** [comment]
Both @HEskandari are currently in contact with some users of SI.

**Comment by HEskandari** [comment]
Had a sync with Sergio on the icons again, I think with the issue #655 the need for retried/successful message goes away completely as we will have a separate column for the number of retries. 

Issue #655 will also simplify the current icons since we no longer need to display repeated-fails icons.

**Comment by adamralph** [comment]
At the moment it is not clear how #655 will remove the need for some of the icons.

**Comment by sergioc** [comment]
An extra column indicating the number of retries needed to process a message. That combined with a status icon should indicate if a message processed successfully or not and how many retry attempts were made up to the current processing status.

**Comment by HEskandari** [comment]
655 is about showing number of retires of each message. The simple implementation (for which we already have the data) can be in the form of a new column. The more advanced version (which would require the history of retires in SC) can be represented in a child / detail grid. We can split 655 to go with the simpler version as a low hanging fruit.

**Comment by adamralph** [comment]
I suggest we create a new issue which describes the alternate solution to this one precisely, including the removal of some of the current icons, etc.

**Comment by HEskandari** [comment]
@adamralph @sergioc Created #796.

**Comment by sergioc** [comment]
I've changed the retry requested and retry successful icons like this:

<img width="388" alt="image" src="https://user-images.githubusercontent.com/493451/91980504-a8d10700-ed27-11ea-8d39-2484e22254e9.png">

Reason is that the retry successful icon as a whole is already tiny and with 2 icons crammed into it, it's not really that legible.

All icon SVGs are here: https://www.dropbox.com/sh/cxbnpq3j7maqkfk/AADU2oxGS68YOakefAkJW-iea?dl=0

**Comment by HEskandari** [comment]
@sergioc All the "warning" icons are part of this [other issue](#735). We'll use them when working on that issue.
