### ISSUE TITLE
Make msg selection highlight color neutral

### ISSUE THREAD

**Issue by sergioc** [Particular/ServiceInsight#743]
While working on https://github.com/Particular/ServiceInsight/issues/739, it occurred to me that the current message selection highlight color isn't particularly appealing nor contrasts well with some icons.

## Proposal 1

- use a neutral color like grey to better contrast with icon colors
- increase contrast...
  - ... with other rows by using a dark color
  - ... with text inside selected row, by making it white

## Proposal 2

- use a neutral color like grey to better contrast with icon colors
- change selection highlight from light blue to light grey

Proposal 1 will likely give better results, but will require changes to "archive" and "retry requested"

**Comment by adamralph** [comment]
@sergioc could you provide some mock ups?

**Comment by sergioc** [comment]
I could, but it would be faster to visualize this directly in XAML.

**Comment by adamralph** [comment]
Discussed this with @HEskandari - he will provide screenshots.

**Comment by HEskandari** [comment]
@sergioc Do you have specific colors in mind?

**Comment by sergioc** [comment]
We can start from #222222 for dark grey (will require text to be white) and #bbbbbb for light grey and tweak from there.

**Comment by HEskandari** [comment]
Here's how it looks with the proposed colors.

![si-01](https://user-images.githubusercontent.com/132117/29755156-d8719f20-8bd6-11e7-91f9-ec6aa0e6a4ef.png)

![si-02](https://user-images.githubusercontent.com/132117/29755162-f0a1fd9c-8bd6-11e7-8528-3d088345c588.png)

I think the change in the focused row should also be reflected in the "Properties" window and the "Explorer" since they have similar semantics (selecting a row) and mechanics (using Grid control under the hood).

**Comment by adamralph** [comment]
@HEskandari are these two alternatives? Or are these two possible states?

**Comment by HEskandari** [comment]
These are the two colors you suggested @sergioc. There's not much of a possible state, as there's always one row selected/focused (unless there's no data).

**Comment by adamralph** [comment]
OK, so these are two alternatives. I find the black a little too jarring. My vote goes with the grey, similar to Excel:

![image](https://user-images.githubusercontent.com/677704/29814620-480d24da-8cae-11e7-8fdb-9be42a4b33e0.png)

**Comment by adamralph** [comment]
The reason I asked about state, is that some apps have a different style depending on whether the window (or pane) containing the list is active or not, e.g.

### Active

![image](https://user-images.githubusercontent.com/677704/29815032-92db97f2-8caf-11e7-8b79-9c58f8951ba6.png)

## Inactive

![image](https://user-images.githubusercontent.com/677704/29815041-981a4236-8caf-11e7-9780-531a9490aef3.png)

But I guess we don't have this state varation?

**Comment by HEskandari** [comment]
@adamralph we could have that option, if we choose to, but since the Messages list _always_ has something selected, I think it makes sense to not have active/inactive distinction.

**Comment by adamralph** [comment]
@HEskandari that two states indicate whether the messages list has focus or not. In both states, there is a message selected.

**Comment by sergioc** [comment]
> are these two alternatives? Or are these two possible states?

Alternatives

> I find the black a little too jarring. My vote goes with the grey.

I think the grey doesn't completely solve the issue of contrast. Black would work better contrasting with most colors and is easy to see. How would both look in a screenshot showing the whole application? Would black still be jarring? Would you notice that jarriness during normal usage where your task will never be to analyse the color of the highlight?

> The reason I asked about state, is that some apps have a different style depending on whether the window (or pane) containing the list is active or not, e.g.

That actually gives an idea of not putting the highlight background behind the icon. Then we can use whatever color, including a blue used in the different diagrams. Would that be possible?

**Comment by adamralph** [comment]
> I think the grey doesn't completely solve the issue of contrast. Black would work better contrasting with most colors and is easy to see. How would both look in a screenshot showing the whole application? Would black still be jarring? Would you notice that jarriness during normal usage where your task will never be to analyse the color of the highlight?

@sergioc without analysing it too deeply, I simplify prefer the look of the grey highlight to the black one. It's striking enough to immediately convey that it's the active row, without looking odd, which I think a black highlight does. Is there an example of another UI which uses a black background to indicate the active row in a list?

> That actually gives an idea of not putting the highlight background behind the icon. Then we can use whatever color, including a blue used in the different diagrams. Would that be possible?

I'm not sure, but given that the icon is in it's own cell in the row, I think that could look a little weird.

**Comment by sergioc** [comment]
> Is there an example of another UI which uses a black background to indicate the active row in a list?

Not from the top of my mind.

**Comment by HEskandari** [comment]
The black one looks like designing SI for people with vision impairment. Why does it have to be that contrasty?

To me, the gray looks better, is contrasty enough to convey the meaning and matches the rest of the theme.

**Comment by sergioc** [comment]
Black is more noticeable, has no issue contrasting with other colors and there's no confusion with out of focus panes or windows. Can you produce a screenshot of the entire app with the different highlight colors?

**Comment by HEskandari** [comment]
Here are the full app screenshots.

Dark gray selected row (#222222):
![image](https://user-images.githubusercontent.com/132117/36405945-92e2bf10-1647-11e8-8840-f1a23df251a8.png)

Light gray selected row (#bbbbbb):
![image](https://user-images.githubusercontent.com/132117/36406038-2548b80a-1648-11e8-8190-bdc1f8cf2414.png)


@sergioc let me know if you want to jump on a call and tweak the colors.

**Comment by WilliamBZA** [comment]
My vote goes for the light gray

**Comment by sergioc** [comment]
I still vouch for the dark grey for the reasons presented in my last comment.

But I think the best option is the previously mentioned option to use blue (aligned with the selection highlight color used in the diagrams), but not highlight anything in the first column to prevent clashing with icons:

<img width="1258" alt="image" src="https://user-images.githubusercontent.com/493451/36415329-c9d9ad48-1625-11e8-93c5-2136923218a9.png">

**Comment by HEskandari** [comment]
@sergioc Not highlighting the first column, even _if_ possible has a higher effort (since the grid only has the concept of a selected row out of the box).
