### ISSUE TITLE
License checking does not validate on license import

### ISSUE THREAD

**Issue by gbiellem** [Particular/ServiceInsight#776]
Our Particular license is an Advanced License so it does not include ServiceInsight.  

This is pretty clear in the license xml
```
Edition="Advanced" Applications="NServiceBus;ServiceControl;ServicePulse;"
```

But when I load ServiceInsight v1.9.1  and add this license I get no feedback that it is not applicable for this product and the product displays the license in the footer as though I am licensed.  After the app is restarted ServiceInsight reverts to "Trial License Expired". 

One of the devs here assumed this was just a glitch and has been reapplying the license every day and did not realize he was running unlicensed.

https://github.com/Particular/ServiceInsight/issues/722 may be related to this

**Comment by adamralph** [comment]
👍 thanks for raising this @gbiellem.

@Particular/serviceinsight-maintainers this sounds like a good candidate for a quick fix.

**Comment by HEskandari** [comment]
@adamralph might be an issue with the Particular.Licensing package. I can investigate.

**Comment by gbiellem** [comment]
Hi @adamralph  and @HEskandari

Pretty sure SI is just missing a call to the ValidForApplication [here](https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/Shell/LicenseRegistrationViewModel.cs#L96) 
If you take a look at the SC codebase it has an simliar method [here](https://github.com/Particular/ServiceControl/blob/master/src/ServiceControlInstaller.Engine/LicenseMgmt/LicenseManager.cs#L36) which does do the check

**Comment by HEskandari** [comment]
The problem is that ValidForApplication method checks not only for the passed application name, but also "NServiceBus". So if you're licensed for NServiceBus only, it is considered valid for ServiceInsight as well. Hence, my original thought that it requires an update to the licensing package.

**Comment by gbiellem** [comment]
@HEskandari   I think you've misread the code or your not understanding how that is supposed to work.
You are supposed to just provide just the name of the current application to that method.

**Comment by HEskandari** [comment]
@gbiellem ah I got it, yes it'd work fine, thanks.

**Comment by HEskandari** [comment]
This is now release on 1.10.2.
