### ISSUE TITLE
Escape closes the entire app instead of just dialogs

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#784]
in windows escape should only close a dialog

**Comment by HEskandari** [comment]
Verified. Happens due to https://github.com/Particular/ServiceInsight/commit/cfc48c803e02f43d7c90c704968e595d6900fd1d

Auto-close should happen only for dialogs.

**Comment by adamralph** [comment]
Thanks for raising @SimonCropp. We'll fix this in 1.10.0 which will be released shortly.

**Comment by SimonCropp** [comment]
thanks
