### ISSUE TITLE
Endpoint Explorer using invalid url when retrieving endpoints (SI 1.10.0)

### ISSUE THREAD

**Issue by cjoergensen** [Particular/ServiceInsight#787]
In version 1.10.0 the Endpoint Explorer is not populated with data.

The logs shows that an invalid url is used when retrieving the data from SC:

![billede](https://user-images.githubusercontent.com/8087733/36528651-202f9112-17b6-11e8-8797-0084f51ddcaf.png)

**Comment by adamralph** [comment]
@cjoergensen thanks for reporting this. We're looking into it and will post an update ASAP. For now I suggest you revert to [1.9.1](https://github.com/Particular/ServiceInsight/releases/tag/1.9.1).

**Comment by adamralph** [comment]
@cjoergensen can you please tell me which version of ServiceControl you are using?

**Comment by cjoergensen** [comment]
@adamralph we are using 1.45.0

**Comment by danielmarbach** [comment]
@cjoergensen do you have a proxy or load balancer in place?

I added locally a host entry like

```
127.0.0.1              mycustomdomain.com
```

did bind SC to

```
<configuration>
    <appSettings>
        <add key="ServiceControl/Port" value="33333" />
        <add key="ServiceControl/HostName" value="mycustomdomain.com" />
```

and connected SI to 

```
http://mycustomdomain.com:33333/api
```

![image](https://user-images.githubusercontent.com/174258/36532020-ef1f600c-17bf-11e8-9569-023091f39fc5.png)

Seems to work fine. Do you have any more details to allow us to repro it?

**Comment by cjoergensen** [comment]
@danielmarbach oh yes, we are hosting ServicePulse through IIS and using the reverse proxy IIS feature (https://docs.particular.net/servicepulse/install-servicepulse-in-iis). 

The IIS Site is configured to use TLS/SSL using a self signed certificate.

**Comment by cjoergensen** [comment]
@danielmarbach do note that it is only the "/api/endpoints" request that looks funky, the following requests looks fine.

**Comment by danielmarbach** [comment]
@cjoergensen yeah we changed that API for a future version of SC to be able to gracefully switch to a new API that we will provide. I guess [this line is the offender](https://github.com/Particular/ServiceInsight/blob/master/src/ServiceInsight/ServiceControl/DefaultServiceControl.cs#L148) and we have to fix this asap.

**Comment by adamralph** [comment]
@cjoergensen we've patched this, but before we release, would you mind trying this build of ServiceInsight to see if it fixes the problem for you? If all is good, this is the exact binary we will be releasing.

[ServiceInsight-1.10.1.exe.zip](https://github.com/Particular/ServiceInsight/files/1747782/ServiceInsight-1.10.1.exe.zip)

**Comment by adamralph** [comment]
@cjoergensen FYI I found a problem in the build attached to my previous comment. I'll attach another build ASAP.

**Comment by adamralph** [comment]
@cjoergensen please try this build:

[ServiceInsight-1.10.1.exe.zip](https://github.com/Particular/ServiceInsight/files/1748129/ServiceInsight-1.10.1.exe.zip)

**Comment by cjoergensen** [comment]
@adamralph it looks good:
![billede](https://user-images.githubusercontent.com/8087733/36543231-7467a06c-17e3-11e8-93f8-635a77efbfe3.png)

:-)

**Comment by adamralph** [comment]
Great! Thanks for testing. We'll officially release 1.10.1 later today.

**Comment by adamralph** [comment]
1.10.1 is released. Thanks again @cjoergensen! https://twitter.com/adamralph/status/966745512828424192
