### ISSUE TITLE
Continually showing "connected to SC" is redundant and distracting

### ISSUE THREAD

**Issue by SimonCropp** [Particular/ServiceInsight#791]
every time i navigate to SP or refresh the page i get the following

![image](https://user-images.githubusercontent.com/122666/38284532-1ce1ac98-37ff-11e8-939b-ea8e3d87d870.png)

SP version v1.12.0

**Comment by HEskandari** [comment]
@SimonCropp wront repo? I think this belongs to [Particular/ServicePulse](https://github.com/Particular/ServicePulse)

**Comment by SimonCropp** [comment]
@HEskandari thanks. moved
