### ISSUE TITLE
Error notification for certificate validation failure

### ISSUE THREAD

**Issue by markgould** [Particular/ServiceInsight#793]
I just upgraded a machine from ServiceInsight 1.8.0 to 1.10.2 and suddenly I couldn't connect to an endpoint anymore. I was getting an error saying unable to connect to ServiceControl. 

I dug through the code and narrowed it down to the certificate validation flag added in the app.config. When I changed SkipCertificateValidation to true, it started working, but it wasn't obvious what the problem was. It would have been nice if ServiceInsight told me there was a certificate issue.

**Comment by WilliamBZA** [comment]
Hi @markgould, this was added in 1.9.0 as a result of [this](https://github.com/Particular/ServiceInsight/issues/717) issue.

Can you remember what the exact error message was? Was it `There was an error connecting to ServiceControl. Either the address is not valid or the service is down`?

**Comment by markgould** [comment]
Hi @WilliamBZA yes, that was the error. It would be nice if it gave a certificate error or some sort of warning with how to fix it.

**Comment by WilliamBZA** [comment]
Thanks @markgould. I'm not sure when we'll get to it, but we've got eyes on this now.
