### ISSUE TITLE
ServiceInsight ignores datasets larger than 200 items

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#795]
The issue boils down to this line of code:

https://github.com/Particular/ServiceInsight/blob/1cc9820086de31ec752e7d7d3b5d03dca60f9ec2/src/ServiceInsight/Framework/MessageDecoders/JsonMessageDeserializer.cs#L140

This deserializer is used across the board and is not just Saga Data that uses it (which I think was the assumption). What happens is that if Endpoint List (or any other ServiceControl endpoint for that matter) returns a large list (greater than 200), it will get cropped.

**Comment by Scooletz** [comment]
I see are the following possible solutions for this:
- split serializers and remove the condition from the non-sagaData case
- provide `isSagaData` or `truncateLongLists` flag to skip deserializing sagas but keep it for the rest

Also, I'm not familiar with the flow, but it looks that the entries are added anyway a few lines below: https://github.com/Particular/ServiceInsight/blob/1cc9820086de31ec752e7d7d3b5d03dca60f9ec2/src/ServiceInsight/Framework/MessageDecoders/JsonMessageDeserializer.cs#L147-L150 

If you could provide some more background, and/or select/propose a solution, it'd be awesome @HEskandari

**Comment by HEskandari** [comment]
@Scooletz If the entries are added, the I see no point on adding the missingJObject
