### ISSUE TITLE
Option to remove/disable startup splash dialog

### ISSUE THREAD

**Issue by ramonsmits** [Particular/ServiceInsight#806]
The startup dialog is pretty annoying to show. It adds an unneeded startup delay of several seconds.

It would be nice if the dialog could be suppressed and maybe only shown if there is a licensing error.

**Comment by HEskandari** [comment]
I don't think the delay is for showing the splash screen. WPF apps are in general slower to run and excruciatingly slow on a cold run. Have you tried running a debug build without the splash screen to see if that is significantly faster?

**Comment by dvdstelt** [comment]
A much worse experience would be to not see anything and just wait until the app appears. Usually I start these kinds of applications 3 to 5 times because I'm impatient.
