### ISSUE TITLE
No notification when no connection to ServiceControl

### ISSUE THREAD

**Issue by dvdstelt** [Particular/ServiceInsight#807]
## Problem description

If ServiceControl can't be reached (because it's down or in maintenance mode) there is no notification. I put SC in maintenance mode and restored it again, but forgot to start it. When SC was down (ie not started) and I tried to search, it behaved weirdly. I later figured out SC wasn't started yet and that SI did not provide a notification.

## Possible solution

A visible clue that SI can't connect to SI

**Comment by HEskandari** [comment]
Now an error message is shown in Status bar when there are connectivity issues.
