### ISSUE TITLE
Search auto-complete behaving weird

### ISSUE THREAD

**Issue by dvdstelt** [Particular/ServiceInsight#808]
## Problem Description

When trying to type in something that SI recognizes from earlier on, it tries to auto-complete it but that behaves pretty weirdly. In the animation, I'm using both arrow keys and backspace button.

![si-search](https://user-images.githubusercontent.com/1257410/44840169-cf439f80-ac40-11e8-8583-935dabcb18fa.gif)

This is ServiceInsight version 1.10.2

**Comment by HEskandari** [comment]
@dvdstelt Why is it weird? SI keeps the old search entries and tries to auto-complete what you type. When you enter over what's been auto-completed, it will erase the rest.

This is the standard behavior of the DevExpress component we're using by the way.

**Comment by dvdstelt** [comment]
It automatically selects the text that it auto-completes. From then on, I can't properly select any text anymore. Only option is to completely paste the clipboard into the search textbox and try to remove whatever it completes. It's acting really weird and maybe as intended by DevExpress, but then they build a really weird UX.

Maybe the option is to not automatically select the text when it auto-completes?

**Comment by TraGicCode** [comment]
This is definitely a bug and also very frustrating and annoying

**Comment by HEskandari** [comment]
@TraGicCode The auto-complete behavior is driven by a custom-component we are using. I will have a look to see if it can be changed, but in the absence of any customization, I'll be able to disable the whole auto-completion function. Would that work for you, or do you rely on the auto-completion function?
