### ISSUE TITLE
Error: git show -s

### ISSUE THREAD

**Issue by hmahajanHM** [Particular/ServiceInsight#818]
Not able to build the code. How do I resolve these errors? I m using VS 2107
I do also have git already installed. I tried search the error in files but could not found the relevant files.
Please help.

![image](https://user-images.githubusercontent.com/13818991/50384569-5a630c80-06ec-11e9-9565-b1a63532c9f0.png)

**Comment by HEskandari** [comment]
Any reason you _need to_ build the code?
