### ISSUE TITLE
SequenceDiagram treats scaled out instances as separate endpoints

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#820]
Currently when running endpoints as scaled out (multiple instances), the Sequence Diagram treats 'endpoint' as endpoint instances. This causes breaks in the way the diagram is rendered.

The following was generated using Monitoring Demo with Sales endpoint running in scaled out mode:

![image](https://user-images.githubusercontent.com/132117/52982692-b4a5f280-343b-11e9-9b4a-474cb36b469f.png)

Note there are two Sales endpoints in the diagram and there is a rouge event publish from the second instance to the Billing endpoint. 

The suggestion is to render the endpoints as 'logical' endpoints rather than endpoint instances.

Tested with ServiceInsight 1.12.0 and ServiceControl 3.4.0

**Comment by sergioc** [comment]
Group physical endpoints under a single logical endpoint swim lane and list all associated hosts in the tooltip
