### ISSUE TITLE
Messages sent for retry from ServiceControl show as "failed" in ServiceInsight

### ISSUE THREAD

**Issue by SzymonPobiega** [Particular/ServiceInsight#822]
They only transition to "Succeeded" once confirmation of successful processing is delivered via the audit channel.

### Steps to reproduce

- Generate a failed message in an endpoint that has `audit` disabled
- Go to ServiceInsight and list all messages. The message should have state `Failed`
- Change the code in the endpoint to successfully process the message this time
- Go to ServicePulse (or alternatively try from SI) and retry the message
- Observe the message disappear from failed messages list in SP
- Go to ServiceInsight. The message is still in the `Failed` state

### Root cause

- Without the `audits` the messages in SC are not marked as successfully retried. The remain in retry pending state forever and in that state they are not visible in SP interface.
- The retry pending state is mapped to Failed in SI so these messages continue to show as failed in SI

**Comment by HEskandari** [comment]
@SzymonPobiega Can you elaborate? How to reproduce? It is not clear if the retry is issued from SI or SP.

**Comment by SzymonPobiega** [comment]
@HEskandari sorry it took me so long to get to it. I've reproduced it using SP to retry a message but I am pretty sure the result would be the same if using SI. I'll add steps to repro to the description.

**Comment by mikeminutillo** [comment]
Fixed in ServiceControl 3.8.0 https://github.com/Particular/ServiceControl/issues/1656

**Comment by HEskandari** [comment]
This is resolved in https://github.com/Particular/ServiceControl/issues/1656. SI correctly maps the message status given by ServiceControl, so nothing to do here.
