### ISSUE TITLE
Support for isolated storage in roaming profile

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceInsight#825]
Noting this down from a customer. The customer wanted to deploy preconfigured settings over the isolated storage. I pointed out the custom link approach

https://docs.particular.net/serviceinsight/application-invocation

Which works fine for the customer for now but there was still a wish to use the isolated storage as part of the roaming profile

> A future improvement for Service Insight would be switching to “Roaming” isolated storage instead so you only have to set up these connections once per login. Just a thought though. I’ve used that strategy in a few UWP apps myself and it worked out quite well.

**Comment by HEskandari** [comment]
Resolved by #969 and #980
