### ISSUE TITLE
Messages that start multiple sagas are not visualized in Sequence Diagram and Saga view

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#832]
When a message starts multiple sagas, this is only visualized in the Message Flow view, but other views are not visualizing this in any way. When clicking the starting message in the `Message List` view:

- You can only see one of the sagas that got started in the Saga view. There's no way to know (or view) the other sagas that also got started.

- Sequence diagram currently does not show anything related to sagas (only handlers and endpoints), but it'd be helpful if it did (especially this multi-saga scenario)

**Comment by sergioc** [comment]
Closed in favor of https://github.com/Particular/ServiceInsight/issues/767
