### ISSUE TITLE
Ability to see messages sent by SendOnly endpoints

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceInsight#859]
It would be nice to be able to go to a sendonly endpoint and be able to see messages it's sending/publishing.  I assume these would need to be shown in a different way in order for the user to understand these are not messages being consume but being sent out.

**Comment by mikeminutillo** [comment]
Added to our backlog. Out of interest, what problem are you trying to solve with this feature? Are you looking for a specific message or interested in the behavior of the endpoint? Or something else?

**Comment by TraGicCode** [comment]
Hey @mikeminutillo ,

I had a use case where our endpoint was logging messages about violating messaging best practices by nservicebus.  We happened to be mixing both default and custom conventions. Unfortunately, Due to how large the application is i was hoping to utilize serviceinsight to view all the outgoing messages for our sendonly endpoint so that i could easily identify which message types were not registered correctly ( ideally it should be simple to figure out but the complexity of the legacy project has some unfortunate gotchas that need to be refactored ).  

That being said, this is more of a "nice to have" and might not make sense based on how servicecontrol is currently architected.

As a side note, Is there a special serviceinsight query syntax i can utilize using the headers since this is using ravendb under the covers?

**Comment by HEskandari** [comment]
@TraGicCode Unfortunately at the moment there's no advanced search ability / query language as SI relies on RavenDB indices to query the data.
