### ISSUE TITLE
ServiceInsight not drawing sequence diagram on duplicate messages with same MessageId

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceInsight#860]
It looks like service insight is unable to render/show a sequence diagram correctly when 2 messages are sent with the same messageid.  I would assume this would mean conversations wont render for duplicates that happen from users having the outbox feature enabled.

**Comment by HEskandari** [comment]
Would you please clarify when/how two (different?) messages have the same MessageIDs?

**Comment by TraGicCode** [comment]
Hey @HEskandari ,

You are indeed correct.  Closing this as i forgot about that detail!

**Comment by TraGicCode** [comment]
Hey @HEskandari ,

As a side note, If someone is setting the messageid to perform an idempotency check at the consumer.  I doubt anyone is really doing this though as i believe they would be more likley to use a property that on the message itself to represent the idempotency key ( like orderid )

**Comment by HEskandari** [comment]
The platform as a whole is making an assumption that `MessageID`s are unique, so it is not just ServiceInsight.

You're correct to say that you can achieve that through the message body. You can also do that via a custom header if you don't want to clutter the message bodies or doing it for all message types (e.g. a custom behavior).

I'd be keen to know the exact scenario that necessitates the usage of MessageID for that type of behavior.
