### ISSUE TITLE
ServiceInsight does not make ServiceControl status 500 errors visible 

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#880]
When a remote call to ServiceControl fails with WebException, the error is made visible on the Status bar. Similar errors, for example when ServiceControl has issues providing results and returns a 500 status request, is not made visible.

This hides the potential issues and causes perceived 'weird' behaviours in ServiceInsight.

**Comment by kbaley** [comment]
Triaged with @boblangley. Relabeled as an improvement instead of a bug as this is an edge case functional requirement.

**Comment by WojcikMike** [comment]
Fixed in https://github.com/Particular/ServiceInsight/pull/1217
