### ISSUE TITLE
When starting SI and sorting data by a unsupported column, no data is displayed

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#881]
Related to #880 

The core of the issue is that the Messages window in SI has some columns that ServiceControl does not support sorting on. ServiceInsight does client-side sorting. When there is no data to sort (for example cold run) and the last sort column is on one of these unsupported columns, no data is loaded as ServiceControl returns a 500 status (Internal Server Error). 

The lack of error visibility makes this harder to understand and user wouldn't know the sorting is the issue.

A potential solution is to fall back to a sort-supported column (e.g. at start) or apply a default sort (e.g. message ID).

**Comment by sergioc** [comment]
Agreed on:

1) Greying out labels from columns that aren't sortable server-side
2) Showing tooltip on those labels indicating that sorting isn't supported ATM

**Comment by seanfarmar** [comment]
Iv'e disabled sorting on these columns, I'm not sure about the tool tips @sergioc, let me know if you want to add them?

**Comment by sergioc** [comment]
> It seems pretty natural that the column does not sort...

Why?

**Comment by sergioc** [comment]
A couple of things have been left:

1) Greying out the unsortable column labels
2) Adding tooltips that explain why the columns cannot be sorted
