### ISSUE TITLE
Messages window show 'ghost' rows as selected as user scrolls through data

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#882]
When a row is selected in the Messages window, and then the user scrolls further down the list (without clicking on any other row), you can see that the same row index will appear as selected as it scrolls into the view. 

For example, if the 3rd row from the top is selected, as you scroll the 3rd row out of the view and scroll other rows from the bottom of the table, the 3rd row that appears is also shown as selected. The selection is however not applied or changed since the row is not really selected, but it appears as such.

This appears to be a bug with the GridView component. To resolve we may have to upgrade to the latest version of the component.

**Comment by kbaley** [comment]
We have triaged this issue and will be considering it for inclusion in one of the upcoming maintenance releases for this package.
