### ISSUE TITLE
Retried message has no status icon

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceInsight#900]
Version:
2.2.0

Summary:
Retried message that succeeds has missing status icon

![image](https://user-images.githubusercontent.com/6224270/93288941-a5fff880-f7a2-11ea-92f4-10e96aa8d134.png)

**Comment by HEskandari** [comment]
Thanks for reporting it @TraGicCode. I have fixed the bug. The successful retries should look like this to distinguish them from messages without retries:

![Screen Shot 2020-09-17 at 12 58 52 pm](https://user-images.githubusercontent.com/132117/93414966-cbe1e600-f8e5-11ea-8ceb-32ce2410a452.png)

Will be released shortly in version 2.3.
