### ISSUE TITLE
Successful messages sometimes showing yellow Exclamation mark in bottom right corner

### ISSUE THREAD

**Issue by TraGicCode** [Particular/ServiceInsight#904]
Hello,

For some reasons some successful messages are showing a yellow exclamation mark at the bottom right of the status icon.  Is this a bug?  The message wasn't retried via servicepulse/servicecontrol.  IF i were to guess the message is being processed so quickly the determination as to if a retried happened is kicking in.

![image](https://user-images.githubusercontent.com/6224270/93827005-0cb36500-fc2e-11ea-86b8-334884c94b80.png)

**Comment by HEskandari** [comment]
@TraGicCode if you hover over the warning icon on the processing time column, it will tell you what the issue is. We have added an extra insight in message list window, which shows cases of clock-drift (where sending/processing endpoints clocks are out of sync so the times are incorrect). 

You can also add other columns (right-click the table and use Column Chooser) to get additional columns. I think that will help you get a better picture.

**Comment by TraGicCode** [comment]
> if you hover over the warning icon on the processing time column, it will tell you what the issue is.

I see no tooltip showing up when i hover over the warning icon on the processing time column.

> We have added an extra insight in message list window, which shows cases of clock-drift (where sending/processing endpoints clocks are out of sync so the times are incorrect).

You are indeed correct the times are slightly off.  I will reach out to our cloud infrastructure team to see if the NTP settings on each machine are configured differently.

![image](https://user-images.githubusercontent.com/6224270/93835042-96b9f880-fc43-11ea-9dbd-30bf902f3d19.png)

**Comment by HEskandari** [comment]
@TraGicCode the negative critical and delivery times are exactly the reason of the warning (clock-drift).

**Comment by TraGicCode** [comment]
Hey @HEskandari ,

Are there any rules of thumb on what is and is not acceptable clock skew?  I knew this would come up eventually in my journeys with distributed computing :)

**Comment by HEskandari** [comment]
@TraGicCode as with anything sensible, it all depends on other factors, like if you use expired/TTBR and the underlying business. I looked at our documentation and found we have only this [documented](https://docs.particular.net/monitoring/metrics/definitions):

>Due to the fact that the critical time is calculated based on timestamps taken on two different machines (the sender and the receiver of a message), it is affected by the clock drift problem. In cases where the clocks of the machines differ significantly, the critical time may be reported as a negative value. Use well-known clock synchronization solutions such as NTP to mitigate the issue.
