### ISSUE TITLE
Ability to jump on a page by number

### ISSUE THREAD

**Issue by danielmarbach** [Particular/ServiceInsight#958]
A customer requested the ability to jump to a page by number instead of clicking next, next

**Comment by mauroservienti** [comment]
I played a bit with this, and UI wise is not a big deal, the search bar can be tweaked to be something like

![image](https://user-images.githubusercontent.com/1325611/101049043-6ff13a00-3583-11eb-90e9-7046da7f7091.png)

And the current page can act as a placeholder to display the current page or as an input box (+ENTER for example) to move to a specific page within the subset of pages.

The biggest blocker is the way SI moves to a page. It does by using rel links coming from ServiceControl. So either we build a custom link by guessing how the ServiceControl returned one is or we change ServiceControl to return also a new rel link in the form of `"messages/?include_system_messages=False&per_page=50&page={placeholder-to-be-replaced-by-si}"`

@HEskandari thoughts?

**Comment by mauroservienti** [comment]
Raised https://github.com/Particular/ServiceInsight/pull/971 to demo a possible way forward.
