### ISSUE TITLE
Show microseconds for TimeSent and ProcessingStarted/Ended

### ISSUE THREAD

**Issue by eiki25** [Particular/ServiceInsight#988]
Please add microseconds to TimeSent and ProcessingStarted/Ended

**Comment by SzymonPobiega** [comment]
Hi @eiki25 

Why do you need such a high precision in the timestamps?

**Comment by eiki25** [comment]
To identify in which order the messages are created. Now i have multiple messages with the same timestamp

**Comment by SzymonPobiega** [comment]
I don't think it would give you the information you need. Processing started / ended is set by the processing endpoint, not the sending endpoint. So does not reflect when the messages have been sent/created.

**Comment by eiki25** [comment]
If the time is synchronized on the machines it will.
Is there alternative way to see the ordering?

**Comment by SzymonPobiega** [comment]
To my knowledge it a significant challenge to get single microsecond precision in NTP. By default the error is in the millisecond range.

That said, could you elaborate what do you want to achieve? In distributed systems it is rarely necessary to get absolute ordering and when it is, the way to guarantee is to use consensus protocol. Maybe in your case the causation relation would be enough i.e. knowing which message causes which message?

**Comment by eiki25** [comment]
I,m trying to optimize retry mechanism of one message handler because data used in that message is being saved in a another message. So if comparison of the data creation time (date created by the endpoint) vs processing time is beneficial from a debugging perspective to see which comes first.

**Comment by SzymonPobiega** [comment]
Well, you can't really reliably based on the clock determine which message has been processed first, but you can synchronize on some persistent data structure. Here an example:

Have a table with a single row and column defined as `autoincrement`. If both message handlers access the same database when they process messages, increment the value in that table and add the incremented value to audit headers. This way when the message gets to SI, it would include a header containing the counter and you will be able to compere the counters. Higher value means the handler executed later. 

This approach is only guaranteed to be bullet proof if both handlers access the same database and that they execute their business logic inside a database transaction.

**Comment by SzymonPobiega** [comment]
It is also going to work only for messages that succeed processing. The ones that fail and go through retries do not leave any traces (or better -- should not leave any traces).

**Comment by ramonsmits** [comment]
@SzymonPobiega we have microseconds: https://github.com/Particular/NServiceBus/blob/master/src/NServiceBus.Core/DateTimeOffsetHelper.cs#L119 we also use DateTime.UtcNow which captures microseconds dependant on the environment.

I'm not sure if ServiceControl stores the values with microsecond precisions but if it does then this is only a formatting constraint in ServiceInsight.
