### ISSUE TITLE
ServiceInsight does not check for duplicate connections at startup

### ISSUE THREAD

**Issue by HEskandari** [Particular/ServiceInsight#990]
When a second instance of SI is executed, passing startup parameters such as connection to SC to the first instance, the connection need to be de-duplicated (check for existing connection):

- When connection doesn't exist, the connection should be added to endpoint Explorer.
- When the connection does exist, the existing connection/endpoint need to get selected in the Explorer window.

When invoking `View in ServiceInsight` functionality from ServicePulse, the right message need to be displayed (as it currently is).

**Comment by kbaley** [comment]
We have triaged this issue and will be considering it for inclusion in one of the upcoming maintenance releases for this package.

**Comment by mauroservienti** [comment]
Raised https://github.com/Particular/ServiceInsight/pull/1209 to fix the missing connection deduplication
